Vasum: vasum::InputMonitor Class Reference
vasum::InputMonitor Class Reference
#include <input-monitor.hpp>
Public Types
typedef std::function< void()> NotifyCallback
Public Member Functions
InputMonitor (const InputConfig &inputConfig, const NotifyCallback &notifyCallback)
~InputMonitor ()
Private Types
typedef std::function< void(GIOChannel
*gio)> ReadDeviceCallback
Private Member Functions
std::string getDevicePath () const
void createGIOChannel (const std::string &devicePath)
bool isExpectedEventSequence (const struct input_event &)
void readDevice (GIOChannel *)
Static Private Member Functions
static gboolean readDeviceCallback (GIOChannel *, GIOCondition, gpointer)
Private Attributes
InputConfig mConfig
NotifyCallback mNotifyCallback
std::list< struct timeval > mEventTimes
GIOChannel * mChannelPtr
utils::CallbackGuard mGuard
guint mSourceId
Detailed Description
Definition at line 42 of file input-monitor.hpp.
Member Typedef Documentation
typedef std::function<void()> vasum::InputMonitor::NotifyCallback
Definition at line 44 of file input-monitor.hpp.
typedef std::function<void(GIOChannel* gio)> vasum::InputMonitor::ReadDeviceCallback private
Definition at line 51 of file input-monitor.hpp.
Constructor & Destructor Documentation
vasum::InputMonitor::InputMonitor (const InputConfig & inputConfig, const NotifyCallback & notifyCallback)
Definition at line 67 of file input-monitor.cpp.
References vasum::InputConfig::code, createGIOChannel(), vasum::InputConfig::device, vasum::InputConfig::enabled, getDevicePath(), mConfig, vasum::InputConfig::numberOfEvents, and vasum::InputConfig::timeWindowMs.
vasum::InputMonitor::~InputMonitor ()
Definition at line 97 of file input-monitor.cpp.
References mChannelPtr, and mSourceId.
Member Function Documentation
void vasum::InputMonitor::createGIOChannel (const std::string & devicePath) private
Definition at line 179 of file input-monitor.cpp.
References utils::createCallbackWrapper(), mChannelPtr, mGuard, mSourceId, readDevice(), readDeviceCallback(), and utils::CallbackGuard::spawn().
Referenced by InputMonitor().
std::string vasum::InputMonitor::getDevicePath () const private
Definition at line 151 of file input-monitor.cpp.
References vasum::InputConfig::device, and mConfig.
Referenced by InputMonitor().
bool vasum::InputMonitor::isExpectedEventSequence (const struct input_event & ie) private
Definition at line 254 of file input-monitor.cpp.
References vasum::InputConfig::code, vasum::InputConfig::device, mConfig, mEventTimes, vasum::InputConfig::numberOfEvents, and vasum::InputConfig::timeWindowMs.
Referenced by readDevice().
void vasum::InputMonitor::readDevice (GIOChannel * gio) private
Definition at line 223 of file input-monitor.cpp.
References isExpectedEventSequence(), and mNotifyCallback.
Referenced by createGIOChannel().
gboolean vasum::InputMonitor::readDeviceCallback (GIOChannel * gio, GIOCondition , gpointer data) static private
Definition at line 214 of file input-monitor.cpp.
References data.
Referenced by createGIOChannel().
Member Data Documentation
GIOChannel* vasum::InputMonitor::mChannelPtr private
Definition at line 57 of file input-monitor.hpp.
Referenced by createGIOChannel(), and ~InputMonitor().
InputConfig vasum::InputMonitor::mConfig private
Definition at line 53 of file input-monitor.hpp.
Referenced by getDevicePath(), InputMonitor(), and isExpectedEventSequence().
std::list<struct timeval> vasum::InputMonitor::mEventTimes private
Definition at line 56 of file input-monitor.hpp.
Referenced by isExpectedEventSequence().
utils::CallbackGuard vasum::InputMonitor::mGuard private
Definition at line 66 of file input-monitor.hpp.
Referenced by createGIOChannel().
NotifyCallback vasum::InputMonitor::mNotifyCallback private
Definition at line 54 of file input-monitor.hpp.
Referenced by readDevice().
guint vasum::InputMonitor::mSourceId private
Definition at line 67 of file input-monitor.hpp.
Referenced by createGIOChannel(), and ~InputMonitor().
The documentation for this class was generated from the following files:
/home/lkostyra/eclipse_workspaces/code/vasum/server/input-monitor.hpp
/home/lkostyra/eclipse_workspaces/code/vasum/server/input-monitor.cpp