Vasum: vasum::netlink::Netlink Class Reference
vasum::netlink::Netlink Class Reference
#include <netlink.hpp>
Public Member Functions
Netlink ()
~Netlink ()
Netlink (const Netlink &other)=delete
Netlink & operator= (const Netlink &other)=delete
void open (int netNsPid=0)
void close ()
unsigned int send (const void *nlmsg)
std::unique_ptr< std::vector
< char > > rcv (unsigned int nlmsgSeq)
Private Attributes
int mFd
Detailed Description
Netlink class is responsible for communicating with kernel through netlink interface
Definition at line 38 of file netlink.hpp.
Constructor & Destructor Documentation
vasum::netlink::Netlink::Netlink ()
Definition at line 89 of file netlink.cpp.
vasum::netlink::Netlink::~Netlink ()
Definition at line 93 of file netlink.cpp.
References close().
vasum::netlink::Netlink::Netlink (const Netlink & other) delete
Member Function Documentation
void vasum::netlink::Netlink::close ()
Close connection
Definition at line 126 of file netlink.cpp.
References mFd.
Referenced by open(), vasum::netlink::send(), and ~Netlink().
void vasum::netlink::Netlink::open (int netNsPid = 0)
Open connnection
Parameters
netNsPid pid which defines net namespace
Definition at line 98 of file netlink.cpp.
References close(), utils::getSystemErrorMessage(), mFd, and utils::passNamespacedFd().
Referenced by vasum::netlink::send().
Netlink& vasum::netlink::Netlink::operator= (const Netlink & other) delete
std::unique_ptr< std::vector< char > > vasum::netlink::Netlink::rcv (unsigned int nlmsgSeq)
Receive message
It is not thread safe and even you shouldn't call this function on different instances at the same time
Parameters
nlmsgSeq sequence number
Returns
received data
Definition at line 152 of file netlink.cpp.
References utils::getSystemErrorMessage(), and mFd.
Referenced by vasum::netlink::send().
unsigned int vasum::netlink::Netlink::send (const void * nlmsg)
Send message
It is not thread safe and even you shouldn't call this function on different instances at the same time
Parameters
nlmsg pointer to message
Returns
sequence number
Definition at line 134 of file netlink.cpp.
References mFd.
Referenced by vasum::netlink::send().
Member Data Documentation
int vasum::netlink::Netlink::mFd private
Definition at line 80 of file netlink.hpp.
Referenced by close(), open(), rcv(), and send().
The documentation for this class was generated from the following files:
/home/lkostyra/eclipse_workspaces/code/vasum/common/netlink/netlink.hpp
/home/lkostyra/eclipse_workspaces/code/vasum/common/netlink/netlink.cpp