Vasum: vasum::ipc::Socket Class Reference
vasum::ipc::Socket Class Reference
#include <socket.hpp>
Public Types
typedef std::unique_lock
< std::recursive_mutex > Guard
Public Member Functions
Socket (int socketFD=-1)
Socket (Socket &&socket) noexcept
~Socket () noexcept
Socket (const Socket &)=delete
Socket & operator= (const Socket &)=delete
Socket & operator= (Socket &&)=delete
int getFD () const
void write (const void *bufferPtr, const size_t size) const
void read (void *bufferPtr, const size_t size) const
std::shared_ptr< Socket > accept ()
Socket::Guard getGuard () const
Static Public Member Functions
static Socket createSocket (const std::string &path)
static Socket connectSocket (const std::string &path)
Static Private Member Functions
static int createZoneSocket (const std::string &path)
static int getSystemdSocket (const std::string &path)
Private Attributes
int mFD
std::recursive_mutex mCommunicationMutex
Detailed Description
This class wraps all operations possible to do with a socket.
It has operations both for client and server application.
Definition at line 40 of file socket.hpp.
Member Typedef Documentation
typedef std::unique_lock<std::recursive_mutex> vasum::ipc::Socket::Guard
Definition at line 43 of file socket.hpp.
Constructor & Destructor Documentation
vasum::ipc::Socket::Socket (int socketFD = -1) explicit
Default constructor. If socketFD is passed then it's passed by the Socket
Parameters
socketFD socket obtained outside the class.
Definition at line 49 of file socket.cpp.
Referenced by connectSocket(), and createSocket().
vasum::ipc::Socket::Socket (Socket && socket) noexcept
Definition at line 54 of file socket.cpp.
vasum::ipc::Socket::~Socket () noexcept
Definition at line 60 of file socket.cpp.
References vasum::utils::close(), and mFD.
vasum::ipc::Socket::Socket (const Socket &) delete
Member Function Documentation
std::shared_ptr< Socket > vasum::ipc::Socket::accept ()
Accepts connection. Used by a server application. Blocking, called by a server.
Definition at line 79 of file socket.cpp.
References mFD.
Referenced by vasum::ipc::Acceptor::handleConnection().
Socket vasum::ipc::Socket::connectSocket (const std::string & path) static
Connects to a socket. Called as a client.
Parameters
path path to the socket
Returns
connected socket
Definition at line 170 of file socket.cpp.
References vasum::utils::close(), and Socket().
Referenced by vasum::ipc::Client::start().
Socket vasum::ipc::Socket::createSocket (const std::string & path) static
Prepares socket for accepting connections. Called by a server.
Parameters
path path to the socket
Returns
created socket
Definition at line 161 of file socket.cpp.
References createZoneSocket(), getSystemdSocket(), and Socket().
int vasum::ipc::Socket::createZoneSocket (const std::string & path) static private
Definition at line 120 of file socket.cpp.
References vasum::utils::close().
Referenced by createSocket().
int vasum::ipc::Socket::getFD () const
Returns
reference to the socket's file descriptor
Definition at line 74 of file socket.cpp.
References mFD.
Referenced by vasum::ipc::Acceptor::getConnectionFD(), vasum::ipc::Processor::onMethodRequest(), vasum::ipc::Processor::onSendResultRequest(), and vasum::ipc::Processor::onSignalRequest().
Socket::Guard vasum::ipc::Socket::getGuard () const
Definition at line 69 of file socket.cpp.
References mCommunicationMutex.
Referenced by vasum::ipc::Processor::handleInput(), vasum::ipc::Processor::onMethodRequest(), vasum::ipc::Processor::onSendResultRequest(), and vasum::ipc::Processor::onSignalRequest().
int vasum::ipc::Socket::getSystemdSocket (const std::string & path) static private
Definition at line 101 of file socket.cpp.
Referenced by createSocket().
Socket& vasum::ipc::Socket::operator= (const Socket &) delete
Socket& vasum::ipc::Socket::operator= (Socket &&) delete
void vasum::ipc::Socket::read (void * bufferPtr, const size_t size) const
Reads a value of the given type.
Parameters
bufferPtr buffer with the data
size size of the buffer
Definition at line 95 of file socket.cpp.
References mCommunicationMutex, mFD, and vasum::utils::read().
Referenced by vasum::ipc::Processor::handleInput().
void vasum::ipc::Socket::write (const void * bufferPtr, const size_t size) const
Write data using the file descriptor
Parameters
bufferPtr buffer with the data
size size of the buffer
Definition at line 89 of file socket.cpp.
References mCommunicationMutex, mFD, and vasum::utils::write().
Referenced by vasum::ipc::Processor::onMethodRequest(), vasum::ipc::Processor::onSendResultRequest(), and vasum::ipc::Processor::onSignalRequest().
Member Data Documentation
std::recursive_mutex vasum::ipc::Socket::mCommunicationMutex mutable private
Definition at line 110 of file socket.hpp.
Referenced by getGuard(), read(), and write().
int vasum::ipc::Socket::mFD private
Definition at line 109 of file socket.hpp.
Referenced by accept(), getFD(), read(), write(), and ~Socket().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/common/ipc/internals/socket.hpp
/home/dariusz/task/security-containers/common/ipc/internals/socket.cpp