Vasum: vasum::lxc::LxcZone Class Reference
vasum::lxc::LxcZone Class Reference
#include <zone.hpp>
Public Types
enum State {
State::STOPPED, State::STARTING, State::RUNNING, State::STOPPING,
State::ABORTING, State::FREEZING, State::FROZEN, State::THAWED
}
typedef std::function< int()> Call
Public Member Functions
LxcZone (const std::string &lxcPath, const std::string &zoneName)
~LxcZone ()
LxcZone (const LxcZone &)=delete
LxcZone & operator= (const LxcZone &)=delete
std::string getName () const
std::string getConfigItem (const std::string &key)
bool isDefined ()
State getState ()
bool waitForState (State state, int timeout)
bool create (const std::string &templatePath, const char *const *argv)
bool destroy ()
bool start (const char *const *argv)
bool stop ()
bool reboot ()
bool shutdown (int timeout)
bool freeze ()
bool unfreeze ()
pid_t getInitPid () const
bool runInZone (Call &call)
bool createFile (const std::string &path, const std::int32_t flags, const std::int32_t mode, int *fdPtr)
Static Public Member Functions
static std::string toString (State state)
Private Member Functions
bool setRunLevel (int runLevel)
void refresh ()
Private Attributes
lxc_container * mLxcContainer
Detailed Description
A class wrapping lxc container
Definition at line 42 of file zone.hpp.
Member Typedef Documentation
typedef std::function<int()> vasum::lxc::LxcZone::Call
Definition at line 44 of file zone.hpp.
Member Enumeration Documentation
enum vasum::lxc::LxcZone::State strong
Enumerator
STOPPED
STARTING
RUNNING
STOPPING
ABORTING
FREEZING
FROZEN
THAWED
Definition at line 46 of file zone.hpp.
Constructor & Destructor Documentation
vasum::lxc::LxcZone::LxcZone (const std::string & lxcPath, const std::string & zoneName)
LxcZone constructor
Parameters
lxcPath path where zones lives
zoneName name of zone
Definition at line 99 of file zone.cpp.
References mLxcContainer.
vasum::lxc::LxcZone::~LxcZone ()
Definition at line 109 of file zone.cpp.
References mLxcContainer.
vasum::lxc::LxcZone::LxcZone (const LxcZone &) delete
Member Function Documentation
bool vasum::lxc::LxcZone::create (const std::string & templatePath, const char *const * argv)
Create zone
Parameters
templatePath template from which zone will be created
argv additional template arguments
Definition at line 141 of file zone.cpp.
References utils::CArrayBuilder< T >::add(), utils::CArrayBuilder< T >::c_array(), utils::executeAndWait(), getName(), mLxcContainer, and refresh().
Referenced by vasum::Zone::Zone().
bool vasum::lxc::LxcZone::createFile (const std::string & path, const std::int32_t flags, const std::int32_t mode, int * fdPtr)
Create a file inside the zone and return it's file descriptor
Parameters
[in] path Path in container where file shall be created
[in] flags Flags used when creating file. Note that the method already provides O_CREAT and O_EXCL flags. User must provide the function with O_RDWR/O_RDONLY/O_WRONLY flag explicitly.
[in] mode Permissions with which file is created
[out] fdPtr Pointer to opened file descriptor.
Returns
True on success, false on failure.
Definition at line 378 of file zone.cpp.
References utils::close(), utils::fdRecv(), utils::fdSend(), utils::getSystemErrorMessage(), and runInZone().
Referenced by vasum::Zone::createFile().
bool vasum::lxc::LxcZone::destroy ()
Destroy zone
Definition at line 177 of file zone.cpp.
References getName(), and mLxcContainer.
Referenced by vasum::Zone::~Zone().
bool vasum::lxc::LxcZone::freeze ()
Freeze (pause/lock) zone
Definition at line 303 of file zone.cpp.
References getName(), and mLxcContainer.
Referenced by vasum::Zone::suspend().
std::string vasum::lxc::LxcZone::getConfigItem (const std::string & key)
Get item from lxc config file
Exceptions
LxcException if key not found
Definition at line 119 of file zone.cpp.
References getName(), and mLxcContainer.
pid_t vasum::lxc::LxcZone::getInitPid () const
Get pid of init process
Definition at line 330 of file zone.cpp.
References mLxcContainer.
Referenced by vasum::Zone::createNetdevMacvlan(), vasum::Zone::createNetdevVeth(), vasum::Zone::deleteNetdevIpAddress(), vasum::Zone::destroyNetdev(), vasum::Zone::getNetdevAttrs(), vasum::Zone::getNetdevList(), vasum::Zone::moveNetdev(), and vasum::Zone::setNetdevAttrs().
std::string vasum::lxc::LxcZone::getName () const
Get zone name
Definition at line 114 of file zone.cpp.
References mLxcContainer.
Referenced by create(), destroy(), freeze(), getConfigItem(), reboot(), shutdown(), start(), stop(), unfreeze(), and waitForState().
LxcZone::State vasum::lxc::LxcZone::getState ()
Get zone state
Definition at line 135 of file zone.cpp.
References mLxcContainer.
Referenced by vasum::Zone::isPaused(), vasum::Zone::isRunning(), vasum::Zone::isStopped(), and shutdown().
bool vasum::lxc::LxcZone::isDefined ()
Is zone defined (created)?
Definition at line 130 of file zone.cpp.
References mLxcContainer.
Referenced by vasum::Zone::Zone().
LxcZone& vasum::lxc::LxcZone::operator= (const LxcZone &) delete
bool vasum::lxc::LxcZone::reboot ()
Reboot zone
Definition at line 247 of file zone.cpp.
References getName(), and mLxcContainer.
void vasum::lxc::LxcZone::refresh () private
Definition at line 343 of file zone.cpp.
References mLxcContainer.
Referenced by create(), shutdown(), and start().
bool vasum::lxc::LxcZone::runInZone (Call & call)
Attach to the Zone and run the call
This call will fork, so ensure the call object will withstand this
Parameters
call function object to run
Definition at line 352 of file zone.cpp.
References mLxcContainer, and utils::waitPid().
Referenced by createFile(), and setRunLevel().
bool vasum::lxc::LxcZone::setRunLevel (int runLevel) private
Definition at line 335 of file zone.cpp.
References runInZone(), and utils::setRunLevel().
Referenced by shutdown().
bool vasum::lxc::LxcZone::shutdown (int timeout)
Gracefully shutdown zone.
Definition at line 256 of file zone.cpp.
References utils::CArrayBuilder< T >::add(), utils::CArrayBuilder< T >::c_array(), utils::executeAndWait(), getName(), getState(), mLxcContainer, refresh(), utils::RUNLEVEL_POWEROFF, RUNNING, setRunLevel(), STOPPED, and waitForState().
Referenced by vasum::Zone::stop().
bool vasum::lxc::LxcZone::start (const char *const * argv)
Start zone
Parameters
argv init process with arguments
Definition at line 186 of file zone.cpp.
References utils::CArrayBuilder< T >::add(), utils::CArrayBuilder< T >::c_array(), utils::executeAndWait(), getName(), mLxcContainer, and refresh().
Referenced by vasum::Zone::start().
bool vasum::lxc::LxcZone::stop ()
Immediate stop the zone It kills all processes within this zone
Definition at line 238 of file zone.cpp.
References getName(), and mLxcContainer.
Referenced by vasum::Zone::stop(), and vasum::Zone::~Zone().
std::string vasum::lxc::LxcZone::toString (State state) static
String representation of state
Definition at line 83 of file zone.cpp.
References ABORTING, CASE, FREEZING, FROZEN, RUNNING, STARTING, STOPPED, STOPPING, and THAWED.
Referenced by waitForState().
bool vasum::lxc::LxcZone::unfreeze ()
Unfreeze zone
Definition at line 312 of file zone.cpp.
References getName(), and mLxcContainer.
Referenced by vasum::Zone::resume().
bool vasum::lxc::LxcZone::waitForState (State state, int timeout)
Wait till zone is in specified state
Returns
false on timeout
Definition at line 321 of file zone.cpp.
References getName(), mLxcContainer, and toString().
Referenced by shutdown().
Member Data Documentation
lxc_container* vasum::lxc::LxcZone::mLxcContainer private
Definition at line 176 of file zone.hpp.
Referenced by create(), destroy(), freeze(), getConfigItem(), getInitPid(), getName(), getState(), isDefined(), LxcZone(), reboot(), refresh(), runInZone(), shutdown(), start(), stop(), unfreeze(), waitForState(), and ~LxcZone().
The documentation for this class was generated from the following files:
/home/lkostyra/eclipse_workspaces/code/vasum/common/lxc/zone.hpp
/home/lkostyra/eclipse_workspaces/code/vasum/common/lxc/zone.cpp