Vasum: vasum::epoll::GlibDispatcher Class Reference
vasum::epoll::GlibDispatcher Class Reference
#include <glib-dispatcher.hpp>
Public Member Functions
GlibDispatcher ()
~GlibDispatcher ()
EventPoll & getPoll ()
Private Attributes
EventPoll mPoll
utils::CallbackGuard mGuard
GIOChannel * mChannel
guint mWatchId
Detailed Description
Will dispatch poll events in glib thread
Definition at line 39 of file glib-dispatcher.hpp.
Constructor & Destructor Documentation
vasum::epoll::GlibDispatcher::GlibDispatcher ()
Definition at line 32 of file glib-dispatcher.cpp.
References vasum::utils::createCallbackWrapper(), data, vasum::utils::deleteCallbackWrapper(), vasum::epoll::EventPoll::dispatchIteration(), vasum::epoll::EventPoll::getPollFD(), mChannel, mGuard, mPoll, mWatchId, and vasum::utils::CallbackGuard::spawn().
vasum::epoll::GlibDispatcher::~GlibDispatcher ()
Definition at line 53 of file glib-dispatcher.cpp.
References mChannel, and mWatchId.
Member Function Documentation
EventPoll & vasum::epoll::GlibDispatcher::getPoll ()
Definition at line 60 of file glib-dispatcher.cpp.
References mPoll.
Member Data Documentation
GIOChannel* vasum::epoll::GlibDispatcher::mChannel private
Definition at line 48 of file glib-dispatcher.hpp.
Referenced by GlibDispatcher(), and ~GlibDispatcher().
utils::CallbackGuard vasum::epoll::GlibDispatcher::mGuard private
Definition at line 47 of file glib-dispatcher.hpp.
Referenced by GlibDispatcher().
EventPoll vasum::epoll::GlibDispatcher::mPoll private
Definition at line 46 of file glib-dispatcher.hpp.
Referenced by getPoll(), and GlibDispatcher().
guint vasum::epoll::GlibDispatcher::mWatchId private
Definition at line 49 of file glib-dispatcher.hpp.
Referenced by GlibDispatcher(), and ~GlibDispatcher().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/common/epoll/glib-dispatcher.hpp
/home/dariusz/task/security-containers/common/epoll/glib-dispatcher.cpp