Vasum: vasum::Server Class Reference
vasum::Server Class Reference
#include <server.hpp>
Public Member Functions
Server (const std::string &configPath)
void run (bool asRoot)
void reloadIfRequired (char *argv[])
void terminate ()
Static Public Member Functions
static bool checkEnvironment ()
Static Private Member Functions
static bool prepareEnvironment (const std::string &configPath, bool runAsRoot)
Private Attributes
std::string mConfigPath
ipc::epoll::ThreadDispatcher mDispatcher
Detailed Description
Definition at line 38 of file server.hpp.
Constructor & Destructor Documentation
vasum::Server::Server (const std::string & configPath)
Definition at line 82 of file server.cpp.
Member Function Documentation
bool vasum::Server::checkEnvironment () static
Check server runtime environment
Definition at line 154 of file server.cpp.
References utils::close().
bool vasum::Server::prepareEnvironment (const std::string & configPath, bool runAsRoot) static private
Set needed caps, groups and drop root privileges.
Definition at line 221 of file server.cpp.
References utils::createDir(), utils::dropRoot(), vasum::ZonesManagerConfig::runMountPointPrefix, and utils::setSuppGroups().
Referenced by run().
void vasum::Server::reloadIfRequired (char * argv[])
Reload the server by launching execve on itself if SIGUSR1 was sent to server.
Definition at line 140 of file server.cpp.
References environ, and utils::getSystemErrorMessage().
Referenced by main().
void vasum::Server::run (bool asRoot)
Starts all the zones and blocks until SIGINT, SIGTERM or SIGUSR1
Definition at line 107 of file server.cpp.
References mConfigPath, mDispatcher, prepareEnvironment(), utils::signalBlock(), and utils::Latch::wait().
Referenced by main().
void vasum::Server::terminate ()
Terminates the server. Equivalent of sending SIGINT or SIGTERM signal
Definition at line 148 of file server.cpp.
References utils::Latch::set().
Member Data Documentation
std::string vasum::Server::mConfigPath private
Definition at line 64 of file server.hpp.
Referenced by run().
ipc::epoll::ThreadDispatcher vasum::Server::mDispatcher private
Definition at line 65 of file server.hpp.
Referenced by run().
The documentation for this class was generated from the following files:
/home/lkostyra/eclipse_workspaces/code/vasum/server/server.hpp
/home/lkostyra/eclipse_workspaces/code/vasum/server/server.cpp