Vasum: vasum::cli::CommandLineInterface Class Reference
vasum::cli::CommandLineInterface Class Reference
#include <command-line-interface.hpp>
Public Types
typedef std::function< void(const
Args &argv)> ExecutorCallback
typedef std::vector< std::pair
< std::string, std::string > > ArgsSpec
Public Member Functions
CommandLineInterface ()
CommandLineInterface (const ExecutorCallback &executorCallback, const std::string &name, const std::string &description, const unsigned int &availability, const ArgsSpec &argsSpec)
const std::string & getName () const
const std::string & getDescription () const
void printUsage (std::ostream &out) const
bool isAvailable (unsigned int mode) const
void execute (const Args &argv)
Static Public Member Functions
static void connect ()
static void disconnect ()
static void executeCallback (const std::function< VsmStatus(VsmClient)> &fun)
Private Attributes
const ExecutorCallback mExecutorCallback
const std::string mName
const std::string mDescription
const unsigned int mAvailability
const ArgsSpec mArgsSpec
Static Private Attributes
static VsmClient client = NULL
Detailed Description
Class that implements command pattern.
Definition at line 46 of file command-line-interface.hpp.
Member Typedef Documentation
typedef std::vector<std::pair<std::string, std::string> > vasum::cli::CommandLineInterface::ArgsSpec
See Also
CommandLineInterface::CommandLineInterface
Definition at line 57 of file command-line-interface.hpp.
typedef std::function<void(const Args& argv)> vasum::cli::CommandLineInterface::ExecutorCallback
See Also
CommandLineInterface::execute
Definition at line 52 of file command-line-interface.hpp.
Constructor & Destructor Documentation
vasum::cli::CommandLineInterface::CommandLineInterface () inline
Dummy constructor (for stl usage)
Definition at line 62 of file command-line-interface.hpp.
vasum::cli::CommandLineInterface::CommandLineInterface (const ExecutorCallback & executorCallback, const std::string & name, const std::string & description, const unsigned int & availability, const ArgsSpec & argsSpec) inline
Construct command
Parameters
executorCallback Callback function that will do the job
name Command name
description Command Description
availability Command availability (bit field)
argsSpec Description of arguments
Remarks
Possible bits for availability: MODE_COMMAND_LINE, MODE_INTERACTIVE
Definition at line 75 of file command-line-interface.hpp.
Member Function Documentation
void vasum::cli::CommandLineInterface::connect () static
Set the class (static) in a connected state. This persistent connection to the vasum client is required for calls like lock/unlock queue to work.
Definition at line 150 of file command-line-interface.cpp.
References vsm_client_create(), vsm_client_free(), vsm_connect(), vsm_get_status_message(), and VSMCLIENT_SUCCESS.
void vasum::cli::CommandLineInterface::disconnect () static
Disconnect the class from a vasum client.
Definition at line 174 of file command-line-interface.cpp.
References vsm_client_free(), vsm_disconnect(), vsm_get_status_message(), and VSMCLIENT_SUCCESS.
void vasum::cli::CommandLineInterface::execute (const Args & argv)
Do the work
It calls the callback passed in constructor
Parameters
argv Command line arguments
Definition at line 241 of file command-line-interface.cpp.
void vasum::cli::CommandLineInterface::executeCallback (const std::function< VsmStatus(VsmClient)> & fun) static
Execute a callback passing the connected VsmClient.
Parameters
fun A callback to execute
Definition at line 192 of file command-line-interface.cpp.
References vsm_get_status_message(), and VSMCLIENT_SUCCESS.
const std::string & vasum::cli::CommandLineInterface::getDescription () const
Get the command description
Definition at line 211 of file command-line-interface.cpp.
const std::string & vasum::cli::CommandLineInterface::getName () const
Get the command name
Definition at line 206 of file command-line-interface.cpp.
bool vasum::cli::CommandLineInterface::isAvailable (unsigned int mode) const
Check if the command is available in specific mode
Parameters
mode A mode to check the command's availability in
Definition at line 236 of file command-line-interface.cpp.
void vasum::cli::CommandLineInterface::printUsage (std::ostream & out) const
Print usage to stream
Parameters
out Output stream
Definition at line 216 of file command-line-interface.cpp.
Member Data Documentation
VsmClient vasum::cli::CommandLineInterface::client = NULL static private
Definition at line 140 of file command-line-interface.hpp.
const ArgsSpec vasum::cli::CommandLineInterface::mArgsSpec private
Definition at line 146 of file command-line-interface.hpp.
const unsigned int vasum::cli::CommandLineInterface::mAvailability private
Definition at line 145 of file command-line-interface.hpp.
const std::string vasum::cli::CommandLineInterface::mDescription private
Definition at line 144 of file command-line-interface.hpp.
const ExecutorCallback vasum::cli::CommandLineInterface::mExecutorCallback private
Definition at line 142 of file command-line-interface.hpp.
const std::string vasum::cli::CommandLineInterface::mName private
Definition at line 143 of file command-line-interface.hpp.
The documentation for this class was generated from the following files:
/home/lkostyra/eclipse_workspaces/code/vasum/cli/command-line-interface.hpp
/home/lkostyra/eclipse_workspaces/code/vasum/cli/command-line-interface.cpp