Vasum: vasum::utils::CArrayBuilder< T > Class Template Reference
vasum::utils::CArrayBuilder< T > Class Template Reference
#include <c-array.hpp>
Public Member Functions
CArrayBuilder ()
CArrayBuilder & add (const T &v)
const T * c_array () const
size_t size () const
bool empty () const
const T * begin () const
const T * end () const
Private Attributes
std::vector< T > mArray
Detailed Description
template<typename T>
class vasum::utils::CArrayBuilder< T >
Definition at line 34 of file c-array.hpp.
Constructor & Destructor Documentation
template<typename T > vasum::utils::CArrayBuilder< T >::CArrayBuilder () inline
Definition at line 36 of file c-array.hpp.
Member Function Documentation
template<typename T > CArrayBuilder& vasum::utils::CArrayBuilder< T >::add (const T & v) inline
Definition at line 38 of file c-array.hpp.
References vasum::utils::CArrayBuilder< T >::mArray.
Referenced by vasum::lxc::LxcZone::create(), vasum::lxc::LxcZone::shutdown(), vasum::ZoneAdmin::start(), vasum::lxc::LxcZone::start(), and vasum::ZoneAdmin::ZoneAdmin().
template<typename T > const T* vasum::utils::CArrayBuilder< T >::begin () const inline
Definition at line 56 of file c-array.hpp.
References vasum::utils::CArrayBuilder< T >::mArray.
template<typename T > const T* vasum::utils::CArrayBuilder< T >::c_array () const inline
Definition at line 44 of file c-array.hpp.
References vasum::utils::CArrayBuilder< T >::mArray.
Referenced by vasum::lxc::LxcZone::create(), vasum::lxc::LxcZone::shutdown(), vasum::ZoneAdmin::start(), vasum::lxc::LxcZone::start(), and vasum::ZoneAdmin::ZoneAdmin().
template<typename T > bool vasum::utils::CArrayBuilder< T >::empty () const inline
Definition at line 52 of file c-array.hpp.
References vasum::utils::CArrayBuilder< T >::size().
Referenced by vasum::ZoneAdmin::start().
template<typename T > const T* vasum::utils::CArrayBuilder< T >::end () const inline
Definition at line 60 of file c-array.hpp.
References vasum::utils::CArrayBuilder< T >::mArray.
template<typename T > size_t vasum::utils::CArrayBuilder< T >::size () const inline
Definition at line 48 of file c-array.hpp.
References vasum::utils::CArrayBuilder< T >::mArray.
Referenced by vasum::utils::CArrayBuilder< T >::empty().
Member Data Documentation
template<typename T > std::vector<T> vasum::utils::CArrayBuilder< T >::mArray private
Definition at line 64 of file c-array.hpp.
Referenced by vasum::utils::CArrayBuilder< T >::add(), vasum::utils::CArrayBuilder< T >::begin(), vasum::utils::CArrayBuilder< T >::c_array(), vasum::utils::CArrayBuilder< T >::end(), and vasum::utils::CArrayBuilder< T >::size().
The documentation for this class was generated from the following file:
/home/dariusz/task/security-containers/common/utils/c-array.hpp