Vasum: utils::SignalFD Class Reference
utils::SignalFD Class Reference
#include <signalfd.hpp>
Public Types
typedef std::function< void(const
int sigNum)> Callback
Public Member Functions
SignalFD (ipc::epoll::EventPoll &eventPoll)
~SignalFD ()
SignalFD (const SignalFD &signalfd)=delete
SignalFD & operator= (const SignalFD &)=delete
void setHandler (const int sigNum, const Callback &&callback)
void setHandlerAndBlock (const int sigNum, const Callback &&callback)
int getFD () const
Private Types
typedef std::unique_lock
< std::mutex > Lock
Private Member Functions
void handleInternal ()
Private Attributes
int mFD
std::mutex mMutex
ipc::epoll::EventPoll & mEventPoll
std::unordered_map< int, Callback > mCallbacks
Detailed Description
SignalFD takes control over handling signals sent to the thread.
It should be the only place where signal masks are modified.
Definition at line 46 of file signalfd.hpp.
Member Typedef Documentation
typedef std::function<void(const int sigNum)> utils::SignalFD::Callback
Definition at line 48 of file signalfd.hpp.
typedef std::unique_lock<std::mutex> utils::SignalFD::Lock private
Definition at line 80 of file signalfd.hpp.
Constructor & Destructor Documentation
utils::SignalFD::SignalFD (ipc::epoll::EventPoll & eventPoll)
Definition at line 35 of file signalfd.cpp.
References utils::getSignalMask(), utils::getSystemErrorMessage(), handleInternal(), mEventPoll, and mFD.
utils::SignalFD::~SignalFD ()
Definition at line 50 of file signalfd.cpp.
References utils::close(), mEventPoll, and mFD.
utils::SignalFD::SignalFD (const SignalFD & signalfd) delete
Member Function Documentation
int utils::SignalFD::getFD () const
Returns
signal file descriptor
Definition at line 56 of file signalfd.cpp.
References mFD.
void utils::SignalFD::handleInternal () private
Definition at line 101 of file signalfd.cpp.
References mCallbacks, mFD, mMutex, and utils::read().
Referenced by SignalFD().
SignalFD& utils::SignalFD::operator= (const SignalFD &) delete
void utils::SignalFD::setHandler (const int sigNum, const Callback && callback)
Add a callback for a specified signal. Doesn't block the signal.
Parameters
sigNum number of the signal
callback handler callback
Definition at line 61 of file signalfd.cpp.
References utils::getSignalMask(), utils::getSystemErrorMessage(), mCallbacks, mFD, and mMutex.
Referenced by vasum::Server::Server().
void utils::SignalFD::setHandlerAndBlock (const int sigNum, const Callback && callback)
Add a callback for a specified signal Blocks the asynchronous signal handling.
Parameters
sigNum number of the signal
callback handler callback
Definition at line 77 of file signalfd.cpp.
References utils::getSignalMask(), utils::getSystemErrorMessage(), utils::isSignalBlocked(), mCallbacks, mFD, mMutex, utils::signalBlock(), and utils::signalUnblock().
Referenced by vasum::Server::Server().
Member Data Documentation
std::unordered_map<int, Callback> utils::SignalFD::mCallbacks private
Definition at line 85 of file signalfd.hpp.
Referenced by handleInternal(), setHandler(), and setHandlerAndBlock().
ipc::epoll::EventPoll& utils::SignalFD::mEventPoll private
Definition at line 84 of file signalfd.hpp.
Referenced by SignalFD(), and ~SignalFD().
int utils::SignalFD::mFD private
Definition at line 82 of file signalfd.hpp.
Referenced by getFD(), handleInternal(), setHandler(), setHandlerAndBlock(), SignalFD(), and ~SignalFD().
std::mutex utils::SignalFD::mMutex private
Definition at line 83 of file signalfd.hpp.
Referenced by handleInternal(), setHandler(), and setHandlerAndBlock().
The documentation for this class was generated from the following files:
/home/lkostyra/eclipse_workspaces/code/vasum/common/utils/signalfd.hpp
/home/lkostyra/eclipse_workspaces/code/vasum/common/utils/signalfd.cpp