Vasum: vasum::utils::Worker Class Reference
vasum::utils::Worker Class Reference
#include <worker.hpp>
Classes
class WorkerQueue
Public Types
typedef std::shared_ptr< Worker > Pointer
typedef std::function< void()> Task
Public Member Functions
~Worker ()
Pointer createSubWorker ()
void addTask (const Task &task)
Static Public Member Functions
static Pointer create ()
Private Types
typedef unsigned int GroupID
Private Member Functions
Worker (const std::shared_ptr< WorkerQueue > &workerQueue)
Private Attributes
const std::shared_ptr
< WorkerQueue > mWorkerQueue
const GroupID mGroupID
Detailed Description
A queue with tasks executed in a dedicated thread. Current implementation creates a thread on the first use.
Definition at line 38 of file worker.hpp.
Member Typedef Documentation
typedef unsigned int vasum::utils::Worker::GroupID private
Definition at line 61 of file worker.hpp.
typedef std::shared_ptr<Worker> vasum::utils::Worker::Pointer
Definition at line 40 of file worker.hpp.
typedef std::function<void()> vasum::utils::Worker::Task
Definition at line 41 of file worker.hpp.
Constructor & Destructor Documentation
vasum::utils::Worker::~Worker ()
Definition at line 169 of file worker.cpp.
References mGroupID, and mWorkerQueue.
vasum::utils::Worker::Worker (const std::shared_ptr< WorkerQueue > & workerQueue) private
Definition at line 164 of file worker.cpp.
Referenced by create(), and createSubWorker().
Member Function Documentation
void vasum::utils::Worker::addTask (const Task & task)
Adds a task to the queue.
Definition at line 179 of file worker.cpp.
References mGroupID, and mWorkerQueue.
Worker::Pointer vasum::utils::Worker::create () static
Creates a worker with its own thread
Definition at line 159 of file worker.cpp.
References Worker().
Worker::Pointer vasum::utils::Worker::createSubWorker ()
Creates a worker that share a thread with its parent
Definition at line 174 of file worker.cpp.
References mWorkerQueue, and Worker().
Member Data Documentation
const GroupID vasum::utils::Worker::mGroupID private
Definition at line 65 of file worker.hpp.
Referenced by addTask(), and ~Worker().
const std::shared_ptr<WorkerQueue> vasum::utils::Worker::mWorkerQueue private
Definition at line 62 of file worker.hpp.
Referenced by addTask(), createSubWorker(), and ~Worker().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/common/utils/worker.hpp
/home/dariusz/task/security-containers/common/utils/worker.cpp