Vasum: vasum::ipc::Acceptor Class Reference
vasum::ipc::Acceptor Class Reference
#include <acceptor.hpp>
Public Types
typedef std::function< void(std::shared_ptr
< Socket > &socketPtr)> NewConnectionCallback
Public Member Functions
Acceptor (const std::string &socketPath, const NewConnectionCallback &newConnectionCallback)
~Acceptor ()
Acceptor (const Acceptor &acceptor)=delete
Acceptor & operator= (const Acceptor &)=delete
void handleConnection ()
FileDescriptor getConnectionFD ()
Private Attributes
NewConnectionCallback mNewConnectionCallback
Socket mSocket
Detailed Description
Accepts new connections and passes the new socket to a callback.
Definition at line 41 of file acceptor.hpp.
Member Typedef Documentation
typedef std::function<void(std::shared_ptr<Socket>& socketPtr)> vasum::ipc::Acceptor::NewConnectionCallback
Definition at line 44 of file acceptor.hpp.
Constructor & Destructor Documentation
vasum::ipc::Acceptor::Acceptor (const std::string & socketPath, const NewConnectionCallback & newConnectionCallback)
Class for accepting new connections.
Parameters
socketPath path to the socket
newConnectionCallback called on new connections
Definition at line 33 of file acceptor.cpp.
vasum::ipc::Acceptor::~Acceptor ()
Definition at line 40 of file acceptor.cpp.
vasum::ipc::Acceptor::Acceptor (const Acceptor & acceptor) delete
Member Function Documentation
FileDescriptor vasum::ipc::Acceptor::getConnectionFD ()
Returns
file descriptor for the connection socket
Definition at line 51 of file acceptor.cpp.
References vasum::ipc::Socket::getFD(), and mSocket.
Referenced by vasum::ipc::Service::start(), and vasum::ipc::Service::stop().
void vasum::ipc::Acceptor::handleConnection ()
Handle one incoming connection. Used with external polling
Definition at line 45 of file acceptor.cpp.
References vasum::ipc::Socket::accept(), mNewConnectionCallback, and mSocket.
Referenced by vasum::ipc::Service::start().
Acceptor& vasum::ipc::Acceptor::operator= (const Acceptor &) delete
Member Data Documentation
NewConnectionCallback vasum::ipc::Acceptor::mNewConnectionCallback private
Definition at line 71 of file acceptor.hpp.
Referenced by handleConnection().
Socket vasum::ipc::Acceptor::mSocket private
Definition at line 72 of file acceptor.hpp.
Referenced by getConnectionFD(), and handleConnection().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/common/ipc/internals/acceptor.hpp
/home/dariusz/task/security-containers/common/ipc/internals/acceptor.cpp