Vasum: utils::Worker Class Reference
utils::Worker Class Reference
#include <worker.hpp>
Classes
class WorkerQueue
Public Types
typedef std::shared_ptr< Worker > Pointer
typedef std::function< void()> Task
Public Member Functions
~Worker ()
Pointer createSubWorker ()
void addTask (const Task &task)
void addTaskAndWait (const Task &task)
Static Public Member Functions
static Pointer create ()
Private Types
typedef unsigned int GroupID
Private Member Functions
Worker (const std::shared_ptr< WorkerQueue > &workerQueue)
Private Attributes
const std::shared_ptr
< WorkerQueue > mWorkerQueue
const GroupID mGroupID
Detailed Description
A queue with tasks executed in a dedicated thread. Current implementation creates a thread on the first use.
Definition at line 37 of file worker.hpp.
Member Typedef Documentation
typedef unsigned int utils::Worker::GroupID private
Definition at line 61 of file worker.hpp.
typedef std::shared_ptr<Worker> utils::Worker::Pointer
Definition at line 39 of file worker.hpp.
typedef std::function<void()> utils::Worker::Task
Definition at line 40 of file worker.hpp.
Constructor & Destructor Documentation
utils::Worker::~Worker ()
Definition at line 172 of file worker.cpp.
References mGroupID, and mWorkerQueue.
utils::Worker::Worker (const std::shared_ptr< WorkerQueue > & workerQueue) private
Definition at line 167 of file worker.cpp.
Referenced by create(), and createSubWorker().
Member Function Documentation
void utils::Worker::addTask (const Task & task)
Adds a task to the queue.
Definition at line 182 of file worker.cpp.
References mGroupID, and mWorkerQueue.
void utils::Worker::addTaskAndWait (const Task & task)
Definition at line 187 of file worker.cpp.
References mGroupID, mWorkerQueue, and utils::Latch::wait().
Worker::Pointer utils::Worker::create () static
Creates a worker with its own thread
Definition at line 162 of file worker.cpp.
References Worker().
Worker::Pointer utils::Worker::createSubWorker ()
Creates a worker that share a thread with its parent
Definition at line 177 of file worker.cpp.
References mWorkerQueue, and Worker().
Member Data Documentation
const GroupID utils::Worker::mGroupID private
Definition at line 65 of file worker.hpp.
Referenced by addTask(), addTaskAndWait(), and ~Worker().
const std::shared_ptr<WorkerQueue> utils::Worker::mWorkerQueue private
Definition at line 62 of file worker.hpp.
Referenced by addTask(), addTaskAndWait(), createSubWorker(), and ~Worker().
The documentation for this class was generated from the following files:
/home/lkostyra/eclipse_workspaces/code/vasum/common/utils/worker.hpp
/home/lkostyra/eclipse_workspaces/code/vasum/common/utils/worker.cpp