Vasum: vasum::ZoneProvision Class Reference
vasum::ZoneProvision Class Reference
#include <zone-provision.hpp>
Public Member Functions
ZoneProvision (const std::string &rootPath, const std::string &configPath, const std::string &dbPath, const std::string &dbPrefix, const std::vector< std::string > &validLinkPrefixes)
~ZoneProvision ()
ZoneProvision (const ZoneProvision &)=delete
ZoneProvision & operator= (const ZoneProvision &)=delete
ZoneProvision (ZoneProvision &&)=default
std::string declareFile (const int32_t &type, const std::string &path, const int32_t &flags, const int32_t &mode)
std::string declareMount (const std::string &source, const std::string &target, const std::string &type, const int64_t &flags, const std::string &data)
std::string declareLink (const std::string &source, const std::string &target)
void start () noexcept
void stop () noexcept
std::vector< std::string > list () const
void remove (const std::string &item)
Private Member Functions
void saveProvisioningConfig ()
std::string declareProvision (ZoneProvisioningConfig::Provision &&provision)
void mount (const ZoneProvisioningConfig::Mount &config)
void umount (const ZoneProvisioningConfig::Mount &config)
void file (const ZoneProvisioningConfig::File &config)
void link (const ZoneProvisioningConfig::Link &config)
std::string getId (const ZoneProvisioningConfig::File &file) const
std::string getId (const ZoneProvisioningConfig::Mount &mount) const
std::string getId (const ZoneProvisioningConfig::Link &link) const
std::string getId (const ZoneProvisioningConfig::Provision &provision) const
Private Attributes
ZoneProvisioningConfig mProvisioningConfig
std::string mRootPath
std::string mDbPath
std::string mDbPrefix
std::vector< std::string > mValidLinkPrefixes
std::list
< ZoneProvisioningConfig::Provision > mProvisioned
Detailed Description
Class is responsible for prepare filesystem for zone It allows to create directories, files, mount points and copying files from host
Definition at line 42 of file zone-provision.hpp.
Constructor & Destructor Documentation
vasum::ZoneProvision::ZoneProvision (const std::string & rootPath, const std::string & configPath, const std::string & dbPath, const std::string & dbPrefix, const std::vector< std::string > & validLinkPrefixes)
ZoneProvision constructor
Parameters
rootPath zone root path
configPath path to config with defaults
dbPath path to database
dbPrefix database prefix
validLinkPrefixes valid link prefixes
Definition at line 48 of file zone-provision.cpp.
References mProvisioningConfig.
vasum::ZoneProvision::~ZoneProvision ()
Definition at line 61 of file zone-provision.cpp.
References stop().
vasum::ZoneProvision::ZoneProvision (const ZoneProvision &) delete
vasum::ZoneProvision::ZoneProvision (ZoneProvision &&) default
Member Function Documentation
std::string vasum::ZoneProvision::declareFile (const int32_t & type, const std::string & path, const int32_t & flags, const int32_t & mode)
Declare file, directory or pipe that will be created while zone startup
Definition at line 88 of file zone-provision.cpp.
References declareProvision().
std::string vasum::ZoneProvision::declareLink (const std::string & source, const std::string & target)
Declare link that will be created while zone startup
Definition at line 111 of file zone-provision.cpp.
References declareProvision().
std::string vasum::ZoneProvision::declareMount (const std::string & source, const std::string & target, const std::string & type, const int64_t & flags, const std::string & data)
Declare mount that will be created while zone startup
Definition at line 99 of file zone-provision.cpp.
References declareProvision().
std::string vasum::ZoneProvision::declareProvision (ZoneProvisioningConfig::Provision && provision) private
Definition at line 71 of file zone-provision.cpp.
References getId(), mProvisioningConfig, vasum::ZoneProvisioningConfig::provisions, and saveProvisioningConfig().
Referenced by declareFile(), declareLink(), and declareMount().
void vasum::ZoneProvision::file (const ZoneProvisioningConfig::File & config) private
Definition at line 180 of file zone-provision.cpp.
References utils::copyFile(), utils::createDirs(), utils::createFifo(), utils::createFile(), vasum::ZoneProvisioningConfig::File::flags, vasum::ZoneProvisioningConfig::File::mode, vasum::ZoneProvisioningConfig::File::path, vasum::ZoneProvisioningConfig::File::type, VSMFILE_DIRECTORY, VSMFILE_FIFO, and VSMFILE_REGULAR.
Referenced by start().
std::string vasum::ZoneProvision::getId (const ZoneProvisioningConfig::File & file) const private
Definition at line 258 of file zone-provision.cpp.
References vasum::ZoneProvisioningConfig::File::flags, vasum::ZoneProvisioningConfig::File::mode, vasum::ZoneProvisioningConfig::File::path, and vasum::ZoneProvisioningConfig::File::type.
Referenced by declareProvision().
std::string vasum::ZoneProvision::getId (const ZoneProvisioningConfig::Mount & mount) const private
Definition at line 268 of file zone-provision.cpp.
References vasum::ZoneProvisioningConfig::Mount::data, vasum::ZoneProvisioningConfig::Mount::flags, vasum::ZoneProvisioningConfig::Mount::source, vasum::ZoneProvisioningConfig::Mount::target, and vasum::ZoneProvisioningConfig::Mount::type.
std::string vasum::ZoneProvision::getId (const ZoneProvisioningConfig::Link & link) const private
Definition at line 279 of file zone-provision.cpp.
References vasum::ZoneProvisioningConfig::Link::source, and vasum::ZoneProvisioningConfig::Link::target.
std::string vasum::ZoneProvision::getId (const ZoneProvisioningConfig::Provision & provision) const private
Definition at line 284 of file zone-provision.cpp.
void vasum::ZoneProvision::link (const ZoneProvisioningConfig::Link & config) private
Definition at line 237 of file zone-provision.cpp.
References utils::createLink(), vasum::ZoneProvisioningConfig::Link::source, and vasum::ZoneProvisioningConfig::Link::target.
Referenced by start().
std::vector< std::string > vasum::ZoneProvision::list () const
List all provisioned resources
Definition at line 155 of file zone-provision.cpp.
void vasum::ZoneProvision::mount (const ZoneProvisioningConfig::Mount & config) private
Definition at line 215 of file zone-provision.cpp.
References vasum::ZoneProvisioningConfig::Mount::data, vasum::ZoneProvisioningConfig::Mount::flags, utils::mount(), vasum::ZoneProvisioningConfig::Mount::source, vasum::ZoneProvisioningConfig::Mount::target, and vasum::ZoneProvisioningConfig::Mount::type.
Referenced by start().
ZoneProvision& vasum::ZoneProvision::operator= (const ZoneProvision &) delete
void vasum::ZoneProvision::remove (const std::string & item)
Remove resource
Parameters
item resource to be removed (as in list())
Definition at line 164 of file zone-provision.cpp.
void vasum::ZoneProvision::saveProvisioningConfig () private
Definition at line 66 of file zone-provision.cpp.
References mDbPath, mDbPrefix, and mProvisioningConfig.
Referenced by declareProvision().
void vasum::ZoneProvision::start () noexcept
Definition at line 120 of file zone-provision.cpp.
References file(), link(), mount(), mProvisioned, mProvisioningConfig, and vasum::ZoneProvisioningConfig::provisions.
void vasum::ZoneProvision::stop () noexcept
Definition at line 139 of file zone-provision.cpp.
References mProvisioned, and umount().
Referenced by ~ZoneProvision().
void vasum::ZoneProvision::umount (const ZoneProvisioningConfig::Mount & config) private
Definition at line 228 of file zone-provision.cpp.
References vasum::ZoneProvisioningConfig::Mount::target, and utils::umount().
Referenced by stop().
Member Data Documentation
std::string vasum::ZoneProvision::mDbPath private
Definition at line 103 of file zone-provision.hpp.
Referenced by saveProvisioningConfig().
std::string vasum::ZoneProvision::mDbPrefix private
Definition at line 104 of file zone-provision.hpp.
Referenced by saveProvisioningConfig().
std::list<ZoneProvisioningConfig::Provision> vasum::ZoneProvision::mProvisioned private
Definition at line 106 of file zone-provision.hpp.
Referenced by start(), and stop().
ZoneProvisioningConfig vasum::ZoneProvision::mProvisioningConfig private
Definition at line 101 of file zone-provision.hpp.
Referenced by declareProvision(), saveProvisioningConfig(), start(), and ZoneProvision().
std::string vasum::ZoneProvision::mRootPath private
Definition at line 102 of file zone-provision.hpp.
std::vector<std::string> vasum::ZoneProvision::mValidLinkPrefixes private
Definition at line 105 of file zone-provision.hpp.
The documentation for this class was generated from the following files:
/home/lkostyra/eclipse_workspaces/code/vasum/server/zone-provision.hpp
/home/lkostyra/eclipse_workspaces/code/vasum/server/zone-provision.cpp