Vasum: vasum::utils::CountingMap< Key > Class Template Reference
vasum::utils::CountingMap< Key > Class Template Reference
#include <counting-map.hpp>
Public Member Functions
size_t increment (const Key &key)
size_t decrement (const Key &key)
void clear ()
size_t get (const Key &key) const
bool empty () const
Private Types
typedef std::unordered_map
< Key, size_t > Map
Private Attributes
Map mMap
Detailed Description
template<class Key>
class vasum::utils::CountingMap< Key >
Structure used to count elements. It's like multiset + count but is more efficient.
Definition at line 39 of file counting-map.hpp.
Member Typedef Documentation
template<class Key> typedef std::unordered_map<Key, size_t> vasum::utils::CountingMap< Key >::Map private
Definition at line 79 of file counting-map.hpp.
Member Function Documentation
template<class Key> void vasum::utils::CountingMap< Key >::clear () inline
Definition at line 63 of file counting-map.hpp.
template<class Key> size_t vasum::utils::CountingMap< Key >::decrement (const Key & key) inline
Definition at line 50 of file counting-map.hpp.
Referenced by vasum::utils::Worker::WorkerQueue::workerProc().
template<class Key> bool vasum::utils::CountingMap< Key >::empty () const inline
Definition at line 74 of file counting-map.hpp.
Referenced by vasum::utils::Worker::WorkerQueue::~WorkerQueue().
template<class Key> size_t vasum::utils::CountingMap< Key >::get (const Key & key) const inline
Definition at line 68 of file counting-map.hpp.
Referenced by vasum::utils::Worker::WorkerQueue::waitForGroupEmpty().
template<class Key> size_t vasum::utils::CountingMap< Key >::increment (const Key & key) inline
Definition at line 41 of file counting-map.hpp.
Referenced by vasum::utils::Worker::WorkerQueue::addTask().
Member Data Documentation
template<class Key> Map vasum::utils::CountingMap< Key >::mMap private
Definition at line 80 of file counting-map.hpp.
Referenced by vasum::utils::CountingMap< GroupID >::clear(), vasum::utils::CountingMap< GroupID >::decrement(), vasum::utils::CountingMap< GroupID >::empty(), vasum::utils::CountingMap< GroupID >::get(), and vasum::utils::CountingMap< GroupID >::increment().
The documentation for this class was generated from the following file:
/home/dariusz/task/security-containers/common/utils/counting-map.hpp