var hierarchy =
[
    [ "any", null, [
      [ "DisableMoveAnyWrapper", "classDisableMoveAnyWrapper.html", null ]
    ] ],
    [ "Client", "classClient.html", null ],
    [ "Client::Status", "structClient_1_1Status.html", null ],
    [ "config::check_union< X >::checker__< T, const,, >", "structconfig_1_1check__union_1_1checker____.html", null ],
    [ "config::FDStore", "classconfig_1_1FDStore.html", null ],
    [ "config::FileDescriptor", "structconfig_1_1FileDescriptor.html", null ],
    [ "config::FromFDStoreVisitor", "classconfig_1_1FromFDStoreVisitor.html", null ],
    [ "config::FromGVariantVisitor", "classconfig_1_1FromGVariantVisitor.html", null ],
    [ "config::FromJsonVisitor", "classconfig_1_1FromJsonVisitor.html", null ],
    [ "config::FromKVJsonVisitor", "classconfig_1_1FromKVJsonVisitor.html", null ],
    [ "config::FromKVStoreVisitor", "classconfig_1_1FromKVStoreVisitor.html", null ],
    [ "config::has_member_impl< T, F >", "structconfig_1_1has__member__impl.html", null ],
    [ "config::isVisitableHelper__< T >", "structconfig_1_1isVisitableHelper____.html", null ],
    [ "config::isVisitableHelper__< T >::Visitor", "structconfig_1_1isVisitableHelper_____1_1Visitor.html", null ],
    [ "config::KVStore", "classconfig_1_1KVStore.html", null ],
    [ "config::KVStore::Transaction", "classconfig_1_1KVStore_1_1Transaction.html", null ],
    [ "config::sqlite3::Connection", "structconfig_1_1sqlite3_1_1Connection.html", null ],
    [ "config::sqlite3::Statement", "structconfig_1_1sqlite3_1_1Statement.html", null ],
    [ "config::ToFDStoreVisitor", "classconfig_1_1ToFDStoreVisitor.html", null ],
    [ "config::ToGVariantVisitor", "classconfig_1_1ToGVariantVisitor.html", null ],
    [ "config::ToJsonVisitor", "classconfig_1_1ToJsonVisitor.html", null ],
    [ "config::ToKVStoreVisitor", "classconfig_1_1ToKVStoreVisitor.html", null ],
    [ "utils::CountingMap< GroupID >", "classutils_1_1CountingMap.html", null ],
    [ "dbus::AsyncMethodCallResult", "classdbus_1_1AsyncMethodCallResult.html", null ],
    [ "dbus::DbusConnection", "classdbus_1_1DbusConnection.html", null ],
    [ "dbus::DbusConnection::MethodCallbacks", "structdbus_1_1DbusConnection_1_1MethodCallbacks.html", null ],
    [ "dbus::DbusConnection::NameCallbacks", "structdbus_1_1DbusConnection_1_1NameCallbacks.html", null ],
    [ "dbus::DbusConnection::VanishedCallbacks", "structdbus_1_1DbusConnection_1_1VanishedCallbacks.html", null ],
    [ "dbus::MethodResultBuilder", "classdbus_1_1MethodResultBuilder.html", null ],
    [ "InetAddr", "structInetAddr.html", null ],
    [ "ipc::Acceptor", "classipc_1_1Acceptor.html", null ],
    [ "ipc::AddPeerRequest", "classipc_1_1AddPeerRequest.html", null ],
    [ "ipc::Client", "classipc_1_1Client.html", null ],
    [ "ipc::epoll::EventPoll", "classipc_1_1epoll_1_1EventPoll.html", null ],
    [ "ipc::epoll::GlibDispatcher", "classipc_1_1epoll_1_1GlibDispatcher.html", null ],
    [ "ipc::epoll::ThreadDispatcher", "classipc_1_1epoll_1_1ThreadDispatcher.html", null ],
    [ "ipc::EventQueue< MessageType >", "classipc_1_1EventQueue.html", null ],
    [ "ipc::FinishRequest", "classipc_1_1FinishRequest.html", null ],
    [ "ipc::hash< T >", "classipc_1_1hash.html", null ],
    [ "ipc::hash< ipc::UniqueID >", "classipc_1_1hash_3_01ipc_1_1UniqueID_01_4.html", null ],
    [ "ipc::IPCGSource", "structipc_1_1IPCGSource.html", null ],
    [ "ipc::MethodHandler< SentDataType, ReceivedDataType >", "structipc_1_1MethodHandler.html", null ],
    [ "ipc::MethodRequest", "classipc_1_1MethodRequest.html", null ],
    [ "ipc::MethodResult", "classipc_1_1MethodResult.html", null ],
    [ "ipc::Processor", "classipc_1_1Processor.html", null ],
    [ "ipc::Processor::EmptyData", "structipc_1_1Processor_1_1EmptyData.html", null ],
    [ "ipc::Processor::ErrorProtocolMessage", "structipc_1_1Processor_1_1ErrorProtocolMessage.html", null ],
    [ "ipc::Processor::MessageHeader", "structipc_1_1Processor_1_1MessageHeader.html", null ],
    [ "ipc::Processor::MethodHandlers", "structipc_1_1Processor_1_1MethodHandlers.html", null ],
    [ "ipc::Processor::PeerInfo", "structipc_1_1Processor_1_1PeerInfo.html", null ],
    [ "ipc::Processor::RegisterSignalsProtocolMessage", "structipc_1_1Processor_1_1RegisterSignalsProtocolMessage.html", null ],
    [ "ipc::Processor::ReturnCallbacks", "structipc_1_1Processor_1_1ReturnCallbacks.html", null ],
    [ "ipc::Processor::SignalHandlers", "structipc_1_1Processor_1_1SignalHandlers.html", null ],
    [ "ipc::RemovePeerRequest", "classipc_1_1RemovePeerRequest.html", null ],
    [ "ipc::RequestQueue< RequestIdType >", "classipc_1_1RequestQueue.html", null ],
    [ "ipc::RequestQueue< RequestIdType >::Request", "structipc_1_1RequestQueue_1_1Request.html", null ],
    [ "ipc::Result< Data >", "classipc_1_1Result.html", null ],
    [ "ipc::ResultBuilder", "classipc_1_1ResultBuilder.html", null ],
    [ "ipc::ResultHandler< Data >", "structipc_1_1ResultHandler.html", null ],
    [ "ipc::SendResultRequest", "classipc_1_1SendResultRequest.html", null ],
    [ "ipc::Service", "classipc_1_1Service.html", null ],
    [ "ipc::SignalHandler< ReceivedDataType >", "structipc_1_1SignalHandler.html", null ],
    [ "ipc::SignalRequest", "classipc_1_1SignalRequest.html", null ],
    [ "ipc::Socket", "classipc_1_1Socket.html", null ],
    [ "ipc::UniqueID", "classipc_1_1UniqueID.html", null ],
    [ "logger::LogBackend", "classlogger_1_1LogBackend.html", [
      [ "logger::FileBackend", "classlogger_1_1FileBackend.html", null ],
      [ "logger::NullLogger", "classlogger_1_1NullLogger.html", null ],
      [ "logger::PersistentFileBackend", "classlogger_1_1PersistentFileBackend.html", null ],
      [ "logger::StderrBackend", "classlogger_1_1StderrBackend.html", null ],
      [ "logger::SyslogBackend", "classlogger_1_1SyslogBackend.html", null ],
      [ "logger::SystemdJournalBackend", "classlogger_1_1SystemdJournalBackend.html", null ]
    ] ],
    [ "logger::LogFormatter", "classlogger_1_1LogFormatter.html", null ],
    [ "logger::Logger", "classlogger_1_1Logger.html", null ],
    [ "logger::LoggerScope", "classlogger_1_1LoggerScope.html", null ],
    [ "logger::SStreamWrapper", "classlogger_1_1SStreamWrapper.html", null ],
    [ "lxcpp::AttachConfig", "structlxcpp_1_1AttachConfig.html", null ],
    [ "lxcpp::AttachHelper", "classlxcpp_1_1AttachHelper.html", null ],
    [ "lxcpp::Attr", "structlxcpp_1_1Attr.html", null ],
    [ "lxcpp::Command", "classlxcpp_1_1Command.html", [
      [ "lxcpp::Attach", "classlxcpp_1_1Attach.html", null ],
      [ "lxcpp::NetCreateAll", "classlxcpp_1_1NetCreateAll.html", null ],
      [ "lxcpp::PrepGuestTerminal", "classlxcpp_1_1PrepGuestTerminal.html", null ],
      [ "lxcpp::PrepHostTerminal", "classlxcpp_1_1PrepHostTerminal.html", null ],
      [ "lxcpp::Start", "classlxcpp_1_1Start.html", null ]
    ] ],
    [ "lxcpp::Container", "classlxcpp_1_1Container.html", [
      [ "lxcpp::ContainerImpl", "classlxcpp_1_1ContainerImpl.html", null ]
    ] ],
    [ "lxcpp::ContainerConfig", "structlxcpp_1_1ContainerConfig.html", null ],
    [ "lxcpp::InetAddr", "structlxcpp_1_1InetAddr.html", null ],
    [ "lxcpp::LoggerConfig", "structlxcpp_1_1LoggerConfig.html", null ],
    [ "lxcpp::NetworkConfig", "structlxcpp_1_1NetworkConfig.html", null ],
    [ "lxcpp::NetworkInterface", "classlxcpp_1_1NetworkInterface.html", null ],
    [ "lxcpp::NetworkInterfaceConfig", "classlxcpp_1_1NetworkInterfaceConfig.html", null ],
    [ "lxcpp::NetworkInterfaceInfo", "structlxcpp_1_1NetworkInterfaceInfo.html", null ],
    [ "lxcpp::TerminalConfig", "structlxcpp_1_1TerminalConfig.html", null ],
    [ "lxcpp::TerminalsConfig", "structlxcpp_1_1TerminalsConfig.html", null ],
    [ "ipc::MethodHandler< void, void >", "structipc_1_1MethodHandler.html", null ],
    [ "NetdevStructure", "structNetdevStructure.html", null ],
    [ "ipc::RequestQueue< Event >", "classipc_1_1RequestQueue.html", null ],
    [ "ipc::SignalHandler< void >", "structipc_1_1SignalHandler.html", null ],
    [ "std::exception", null, [
      [ "std::runtime_error", null, [
        [ "config::ConfigException", "structconfig_1_1ConfigException.html", null ],
        [ "dbus::DbusException", "structdbus_1_1DbusException.html", [
          [ "dbus::DbusCustomException", "structdbus_1_1DbusCustomException.html", null ],
          [ "dbus::DbusInvalidArgumentException", "structdbus_1_1DbusInvalidArgumentException.html", null ],
          [ "dbus::DbusIOException", "structdbus_1_1DbusIOException.html", null ],
          [ "dbus::DbusOperationException", "structdbus_1_1DbusOperationException.html", null ]
        ] ],
        [ "ipc::IPCException", "structipc_1_1IPCException.html", [
          [ "ipc::IPCClosingException", "structipc_1_1IPCClosingException.html", null ],
          [ "ipc::IPCNaughtyPeerException", "structipc_1_1IPCNaughtyPeerException.html", null ],
          [ "ipc::IPCParsingException", "structipc_1_1IPCParsingException.html", null ],
          [ "ipc::IPCPeerDisconnectedException", "structipc_1_1IPCPeerDisconnectedException.html", null ],
          [ "ipc::IPCRemovedPeerException", "structipc_1_1IPCRemovedPeerException.html", null ],
          [ "ipc::IPCSerializationException", "structipc_1_1IPCSerializationException.html", null ],
          [ "ipc::IPCTimeoutException", "structipc_1_1IPCTimeoutException.html", null ],
          [ "ipc::IPCUserException", "structipc_1_1IPCUserException.html", null ]
        ] ],
        [ "lxcpp::Exception", "structlxcpp_1_1Exception.html", [
          [ "lxcpp::BadArgument", "structlxcpp_1_1BadArgument.html", null ],
          [ "lxcpp::CapabilitySetupException", "structlxcpp_1_1CapabilitySetupException.html", null ],
          [ "lxcpp::ConfigureException", "structlxcpp_1_1ConfigureException.html", null ],
          [ "lxcpp::CredentialSetupException", "structlxcpp_1_1CredentialSetupException.html", null ],
          [ "lxcpp::EnvironmentSetupException", "structlxcpp_1_1EnvironmentSetupException.html", null ],
          [ "lxcpp::FileSystemSetupException", "structlxcpp_1_1FileSystemSetupException.html", null ],
          [ "lxcpp::NetworkException", "structlxcpp_1_1NetworkException.html", null ],
          [ "lxcpp::NoSuchValue", "structlxcpp_1_1NoSuchValue.html", null ],
          [ "lxcpp::NotImplementedException", "structlxcpp_1_1NotImplementedException.html", null ],
          [ "lxcpp::ProcessSetupException", "structlxcpp_1_1ProcessSetupException.html", null ],
          [ "lxcpp::TerminalException", "structlxcpp_1_1TerminalException.html", null ],
          [ "lxcpp::UtilityException", "structlxcpp_1_1UtilityException.html", null ]
        ] ],
        [ "utils::UtilsException", "structutils_1_1UtilsException.html", [
          [ "utils::ProvisionExistsException", "structutils_1_1ProvisionExistsException.html", null ]
        ] ],
        [ "vasum::VasumException", "structvasum_1_1VasumException.html", [
          [ "vasum::cli::CliException", "structvasum_1_1cli_1_1CliException.html", [
            [ "vasum::cli::IOException", "structvasum_1_1cli_1_1IOException.html", null ]
          ] ],
          [ "vasum::ClientException", "structvasum_1_1ClientException.html", [
            [ "vasum::InvalidArgumentException", "structvasum_1_1InvalidArgumentException.html", null ],
            [ "vasum::InvalidResponseException", "structvasum_1_1InvalidResponseException.html", null ],
            [ "vasum::IOException", "structvasum_1_1IOException.html", null ],
            [ "vasum::OperationFailedException", "structvasum_1_1OperationFailedException.html", null ]
          ] ],
          [ "vasum::LxcException", "structvasum_1_1LxcException.html", [
            [ "vasum::KeyNotFoundException", "structvasum_1_1KeyNotFoundException.html", null ]
          ] ],
          [ "vasum::ServerException", "structvasum_1_1ServerException.html", [
            [ "vasum::HostConnectionException", "structvasum_1_1HostConnectionException.html", null ],
            [ "vasum::InputMonitorException", "structvasum_1_1InputMonitorException.html", [
              [ "vasum::TimeoutException", "structvasum_1_1TimeoutException.html", null ]
            ] ],
            [ "vasum::InvalidZoneIdException", "structvasum_1_1InvalidZoneIdException.html", null ],
            [ "vasum::ZoneConnectionException", "structvasum_1_1ZoneConnectionException.html", null ],
            [ "vasum::ZoneOperationException", "structvasum_1_1ZoneOperationException.html", null ]
          ] ]
        ] ]
      ] ]
    ] ],
    [ "integral_constant", null, [
      [ "config::has_member< T, F >", "structconfig_1_1has__member.html", null ],
      [ "config::isVisitable< T >", "structconfig_1_1isVisitable.html", null ],
      [ "config::has_member< T, check_union< T > >", "structconfig_1_1has__member.html", [
        [ "config::isUnion< T >", "structconfig_1_1isUnion.html", null ]
      ] ],
      [ "config::isVisitable< X >", "structconfig_1_1isVisitable.html", [
        [ "config::check_union< X >", "structconfig_1_1check__union.html", null ]
      ] ]
    ] ],
    [ "utils::CallbackGuard", "classutils_1_1CallbackGuard.html", null ],
    [ "utils::CallbackGuard::SharedState", "classutils_1_1CallbackGuard_1_1SharedState.html", null ],
    [ "utils::CallbackWrapper< Callback >", "classutils_1_1CallbackWrapper.html", null ],
    [ "utils::CArrayBuilder< T >", "classutils_1_1CArrayBuilder.html", null ],
    [ "utils::Channel", "classutils_1_1Channel.html", null ],
    [ "utils::CountingMap< Key >", "classutils_1_1CountingMap.html", null ],
    [ "utils::EventFD", "classutils_1_1EventFD.html", null ],
    [ "utils::Glib", "classutils_1_1Glib.html", null ],
    [ "utils::Latch", "classutils_1_1Latch.html", null ],
    [ "utils::SameThreadGuard", "classutils_1_1SameThreadGuard.html", null ],
    [ "utils::ScopedGError", "classutils_1_1ScopedGError.html", null ],
    [ "utils::ScopedGlibLoop", "classutils_1_1ScopedGlibLoop.html", null ],
    [ "utils::SignalFD", "classutils_1_1SignalFD.html", null ],
    [ "utils::ValueLatch< T >", "classutils_1_1ValueLatch.html", null ],
    [ "utils::Worker", "classutils_1_1Worker.html", null ],
    [ "utils::Worker::WorkerQueue", "classutils_1_1Worker_1_1WorkerQueue.html", null ],
    [ "utils::Worker::WorkerQueue::TaskInfo", "structutils_1_1Worker_1_1WorkerQueue_1_1TaskInfo.html", null ],
    [ "vasum::api::CreateFileIn", "structvasum_1_1api_1_1CreateFileIn.html", null ],
    [ "vasum::api::CreateFileOut", "structvasum_1_1api_1_1CreateFileOut.html", null ],
    [ "vasum::api::CreateNetDevMacvlanIn", "structvasum_1_1api_1_1CreateNetDevMacvlanIn.html", null ],
    [ "vasum::api::CreateNetDevVethIn", "structvasum_1_1api_1_1CreateNetDevVethIn.html", null ],
    [ "vasum::api::DeclareFileIn", "structvasum_1_1api_1_1DeclareFileIn.html", null ],
    [ "vasum::api::DeclareLinkIn", "structvasum_1_1api_1_1DeclareLinkIn.html", null ],
    [ "vasum::api::DeclareMountIn", "structvasum_1_1api_1_1DeclareMountIn.html", null ],
    [ "vasum::api::DeleteNetdevIpAddressIn", "structvasum_1_1api_1_1DeleteNetdevIpAddressIn.html", null ],
    [ "vasum::api::GrantDeviceIn", "structvasum_1_1api_1_1GrantDeviceIn.html", null ],
    [ "vasum::api::MethodResultBuilder", "classvasum_1_1api_1_1MethodResultBuilder.html", [
      [ "vasum::api::DbusMethodResultBuilder< Data >", "classvasum_1_1api_1_1DbusMethodResultBuilder.html", null ],
      [ "vasum::api::IPCMethodResultBuilder", "classvasum_1_1api_1_1IPCMethodResultBuilder.html", null ]
    ] ],
    [ "vasum::api::SetNetDevAttrsIn", "structvasum_1_1api_1_1SetNetDevAttrsIn.html", null ],
    [ "vasum::api::String", "structvasum_1_1api_1_1String.html", null ],
    [ "vasum::api::StringPair", "structvasum_1_1api_1_1StringPair.html", null ],
    [ "vasum::api::VectorOfStringPairs", "structvasum_1_1api_1_1VectorOfStringPairs.html", null ],
    [ "vasum::api::VectorOfStrings", "structvasum_1_1api_1_1VectorOfStrings.html", null ],
    [ "vasum::api::Void", "structvasum_1_1api_1_1Void.html", null ],
    [ "vasum::api::ZoneInfoOut", "structvasum_1_1api_1_1ZoneInfoOut.html", null ],
    [ "vasum::cli::ArgSpec", "structvasum_1_1cli_1_1ArgSpec.html", null ],
    [ "vasum::cli::CommandLineInterface", "classvasum_1_1cli_1_1CommandLineInterface.html", null ],
    [ "vasum::HostDbusConnection", "classvasum_1_1HostDbusConnection.html", null ],
    [ "vasum::HostIPCConnection", "classvasum_1_1HostIPCConnection.html", null ],
    [ "vasum::HostIPCConnection::Method< ArgIn, ArgOut >", "classvasum_1_1HostIPCConnection_1_1Method.html", null ],
    [ "vasum::HostIPCConnection::Signal< ArgIn >", "classvasum_1_1HostIPCConnection_1_1Signal.html", null ],
    [ "vasum::InputConfig", "structvasum_1_1InputConfig.html", null ],
    [ "vasum::InputMonitor", "classvasum_1_1InputMonitor.html", null ],
    [ "vasum::IPCMethodWrapper< ArgIn, ArgOut >", "classvasum_1_1IPCMethodWrapper.html", null ],
    [ "vasum::IPCMethodWrapper< ArgOut, typename std::enable_if<!std::is_const< ArgOut >::value, api::Void >::type >", "classvasum_1_1IPCMethodWrapper_3_01ArgOut_00_01typename_01std_1_1enable__if_3_9std_1_1is__const_7b769e9522b2a885961b4da102ba4fa8.html", null ],
    [ "vasum::IPCSignalWrapper< ArgIn >", "classvasum_1_1IPCSignalWrapper.html", null ],
    [ "vasum::IPCSignalWrapper< const api::Void >", "classvasum_1_1IPCSignalWrapper_3_01const_01api_1_1Void_01_4.html", null ],
    [ "vasum::lxc::LxcZone", "classvasum_1_1lxc_1_1LxcZone.html", null ],
    [ "vasum::netlink::Netlink", "classvasum_1_1netlink_1_1Netlink.html", null ],
    [ "vasum::netlink::NetlinkMessage", "classvasum_1_1netlink_1_1NetlinkMessage.html", null ],
    [ "vasum::netlink::NetlinkResponse", "classvasum_1_1netlink_1_1NetlinkResponse.html", null ],
    [ "vasum::ProxyCallPolicy", "classvasum_1_1ProxyCallPolicy.html", null ],
    [ "vasum::ProxyCallRule", "structvasum_1_1ProxyCallRule.html", null ],
    [ "vasum::Server", "classvasum_1_1Server.html", null ],
    [ "vasum::Zone", "classvasum_1_1Zone.html", null ],
    [ "vasum::ZoneConfig", "structvasum_1_1ZoneConfig.html", null ],
    [ "vasum::ZoneDynamicConfig", "structvasum_1_1ZoneDynamicConfig.html", null ],
    [ "vasum::ZoneProvision", "classvasum_1_1ZoneProvision.html", null ],
    [ "vasum::ZoneProvisioningConfig", "structvasum_1_1ZoneProvisioningConfig.html", null ],
    [ "vasum::ZoneProvisioningConfig::File", "structvasum_1_1ZoneProvisioningConfig_1_1File.html", null ],
    [ "vasum::ZoneProvisioningConfig::Link", "structvasum_1_1ZoneProvisioningConfig_1_1Link.html", null ],
    [ "vasum::ZoneProvisioningConfig::Mount", "structvasum_1_1ZoneProvisioningConfig_1_1Mount.html", null ],
    [ "vasum::ZoneProvisioningConfig::Provision", "structvasum_1_1ZoneProvisioningConfig_1_1Provision.html", null ],
    [ "vasum::ZonesManager", "classvasum_1_1ZonesManager.html", null ],
    [ "vasum::ZonesManagerConfig", "structvasum_1_1ZonesManagerConfig.html", null ],
    [ "vasum::ZonesManagerDynamicConfig", "structvasum_1_1ZonesManagerDynamicConfig.html", null ],
    [ "vasum::ZoneTemplatePathConfig", "structvasum_1_1ZoneTemplatePathConfig.html", null ],
    [ "ZoneStructure", "structZoneStructure.html", null ]
];