var namespacevasum =
[
    [ "api", "namespacevasum_1_1api.html", "namespacevasum_1_1api" ],
    [ "cli", "namespacevasum_1_1cli.html", "namespacevasum_1_1cli" ],
    [ "lxc", "namespacevasum_1_1lxc.html", "namespacevasum_1_1lxc" ],
    [ "netdev", "namespacevasum_1_1netdev.html", null ],
    [ "netlink", "namespacevasum_1_1netlink.html", "namespacevasum_1_1netlink" ],
    [ "VasumException", "structvasum_1_1VasumException.html", "structvasum_1_1VasumException" ],
    [ "LxcException", "structvasum_1_1LxcException.html", "structvasum_1_1LxcException" ],
    [ "ClientException", "structvasum_1_1ClientException.html", "structvasum_1_1ClientException" ],
    [ "IOException", "structvasum_1_1IOException.html", "structvasum_1_1IOException" ],
    [ "OperationFailedException", "structvasum_1_1OperationFailedException.html", "structvasum_1_1OperationFailedException" ],
    [ "InvalidArgumentException", "structvasum_1_1InvalidArgumentException.html", "structvasum_1_1InvalidArgumentException" ],
    [ "InvalidResponseException", "structvasum_1_1InvalidResponseException.html", "structvasum_1_1InvalidResponseException" ],
    [ "ServerException", "structvasum_1_1ServerException.html", "structvasum_1_1ServerException" ],
    [ "ZoneOperationException", "structvasum_1_1ZoneOperationException.html", "structvasum_1_1ZoneOperationException" ],
    [ "InvalidZoneIdException", "structvasum_1_1InvalidZoneIdException.html", "structvasum_1_1InvalidZoneIdException" ],
    [ "ZoneConnectionException", "structvasum_1_1ZoneConnectionException.html", "structvasum_1_1ZoneConnectionException" ],
    [ "HostConnectionException", "structvasum_1_1HostConnectionException.html", "structvasum_1_1HostConnectionException" ],
    [ "InputMonitorException", "structvasum_1_1InputMonitorException.html", "structvasum_1_1InputMonitorException" ],
    [ "HostDbusConnection", "classvasum_1_1HostDbusConnection.html", "classvasum_1_1HostDbusConnection" ],
    [ "HostIPCConnection", "classvasum_1_1HostIPCConnection.html", "classvasum_1_1HostIPCConnection" ],
    [ "InputConfig", "structvasum_1_1InputConfig.html", "structvasum_1_1InputConfig" ],
    [ "InputMonitor", "classvasum_1_1InputMonitor.html", "classvasum_1_1InputMonitor" ],
    [ "IPCSignalWrapper", "classvasum_1_1IPCSignalWrapper.html", "classvasum_1_1IPCSignalWrapper" ],
    [ "IPCSignalWrapper< const api::Void >", "classvasum_1_1IPCSignalWrapper_3_01const_01api_1_1Void_01_4.html", "classvasum_1_1IPCSignalWrapper_3_01const_01api_1_1Void_01_4" ],
    [ "IPCMethodWrapper", "classvasum_1_1IPCMethodWrapper.html", "classvasum_1_1IPCMethodWrapper" ],
    [ "IPCMethodWrapper< ArgOut, typename std::enable_if<!std::is_const< ArgOut >::value, api::Void >::type >", "classvasum_1_1IPCMethodWrapper_3_01ArgOut_00_01typename_01std_1_1enable__if_3_9std_1_1is__const_7b769e9522b2a885961b4da102ba4fa8.html", "classvasum_1_1IPCMethodWrapper_3_01ArgOut_00_01typename_01std_1_1enable__if_3_9std_1_1is__const_7b769e9522b2a885961b4da102ba4fa8" ],
    [ "ProxyCallRule", "structvasum_1_1ProxyCallRule.html", "structvasum_1_1ProxyCallRule" ],
    [ "ProxyCallPolicy", "classvasum_1_1ProxyCallPolicy.html", "classvasum_1_1ProxyCallPolicy" ],
    [ "Server", "classvasum_1_1Server.html", "classvasum_1_1Server" ],
    [ "ZoneConfig", "structvasum_1_1ZoneConfig.html", "structvasum_1_1ZoneConfig" ],
    [ "ZoneDynamicConfig", "structvasum_1_1ZoneDynamicConfig.html", "structvasum_1_1ZoneDynamicConfig" ],
    [ "ZoneTemplatePathConfig", "structvasum_1_1ZoneTemplatePathConfig.html", "structvasum_1_1ZoneTemplatePathConfig" ],
    [ "ZoneProvisioningConfig", "structvasum_1_1ZoneProvisioningConfig.html", "structvasum_1_1ZoneProvisioningConfig" ],
    [ "ZoneProvision", "classvasum_1_1ZoneProvision.html", "classvasum_1_1ZoneProvision" ],
    [ "Zone", "classvasum_1_1Zone.html", "classvasum_1_1Zone" ],
    [ "ZonesManagerConfig", "structvasum_1_1ZonesManagerConfig.html", "structvasum_1_1ZonesManagerConfig" ],
    [ "ZonesManagerDynamicConfig", "structvasum_1_1ZonesManagerDynamicConfig.html", "structvasum_1_1ZonesManagerDynamicConfig" ],
    [ "ZonesManager", "classvasum_1_1ZonesManager.html", "classvasum_1_1ZonesManager" ]
];