Vasum: vasum Namespace Reference
vasum Namespace Reference
Namespaces
api
cli
lxc
netdev
netlink
Classes
struct VasumException
struct LxcException
struct ClientException
struct IOException
struct OperationFailedException
struct InvalidArgumentException
struct InvalidResponseException
struct ServerException
struct ZoneOperationException
struct InvalidZoneIdException
struct ZoneConnectionException
struct HostConnectionException
struct InputMonitorException
class HostDbusConnection
class HostIPCConnection
struct InputConfig
class InputMonitor
class IPCSignalWrapper
class IPCSignalWrapper< const api::Void >
class IPCMethodWrapper
class IPCMethodWrapper< ArgOut, typename std::enable_if<!std::is_const< ArgOut >::value, api::Void >::type >
struct ProxyCallRule
class ProxyCallPolicy
class Server
struct ZoneConfig
struct ZoneDynamicConfig
struct ZoneTemplatePathConfig
struct ZoneProvisioningConfig
class ZoneProvision
class Zone
struct ZonesManagerConfig
struct ZonesManagerDynamicConfig
class ZonesManager
Enumerations
enum SchedulerLevel { SchedulerLevel::FOREGROUND, SchedulerLevel::BACKGROUND }
Functions
std::string getVasumDbPrefix ()
std::string getZoneDbPrefix (const std::string &id)
Variables
const std::string INVALID_CONNECTION_ID = "invalid://"
Enumeration Type Documentation
enum vasum::SchedulerLevel strong
Enumerator
FOREGROUND
BACKGROUND
Definition at line 45 of file zone.hpp.
Function Documentation
std::string vasum::getVasumDbPrefix () inline
Gets db prefix for vasum config
Definition at line 36 of file dynamic-config-scheme.hpp.
Referenced by vasum::ZonesManager::saveDynamicConfig(), and vasum::ZonesManager::ZonesManager().
std::string vasum::getZoneDbPrefix (const std::string & id) inline
Gets db prefix for zone config
Definition at line 44 of file dynamic-config-scheme.hpp.
Referenced by vasum::ZonesManager::generateNewConfig(), vasum::ZonesManager::getTemplatePathForExistingZone(), vasum::Zone::saveDynamicConfig(), and vasum::Zone::Zone().
Variable Documentation
const std::string vasum::INVALID_CONNECTION_ID = "invalid://"
Definition at line 49 of file zones-manager.hpp.
Referenced by vasum::ZonesManager::disconnectedCallback(), vasum::ZonesManager::handleLockQueueCall(), vasum::ZonesManager::handleUnlockQueueCall(), and vasum::ZonesManager::tryAddTask().