var namespaceipc =
[
    [ "epoll", "namespaceipc_1_1epoll.html", "namespaceipc_1_1epoll" ],
    [ "Acceptor", "classipc_1_1Acceptor.html", "classipc_1_1Acceptor" ],
    [ "AddPeerRequest", "classipc_1_1AddPeerRequest.html", "classipc_1_1AddPeerRequest" ],
    [ "Client", "classipc_1_1Client.html", "classipc_1_1Client" ],
    [ "EventQueue", "classipc_1_1EventQueue.html", "classipc_1_1EventQueue" ],
    [ "FinishRequest", "classipc_1_1FinishRequest.html", "classipc_1_1FinishRequest" ],
    [ "IPCClosingException", "structipc_1_1IPCClosingException.html", "structipc_1_1IPCClosingException" ],
    [ "IPCException", "structipc_1_1IPCException.html", "structipc_1_1IPCException" ],
    [ "IPCGSource", "structipc_1_1IPCGSource.html", "structipc_1_1IPCGSource" ],
    [ "IPCNaughtyPeerException", "structipc_1_1IPCNaughtyPeerException.html", "structipc_1_1IPCNaughtyPeerException" ],
    [ "IPCParsingException", "structipc_1_1IPCParsingException.html", "structipc_1_1IPCParsingException" ],
    [ "IPCPeerDisconnectedException", "structipc_1_1IPCPeerDisconnectedException.html", "structipc_1_1IPCPeerDisconnectedException" ],
    [ "IPCRemovedPeerException", "structipc_1_1IPCRemovedPeerException.html", "structipc_1_1IPCRemovedPeerException" ],
    [ "IPCSerializationException", "structipc_1_1IPCSerializationException.html", "structipc_1_1IPCSerializationException" ],
    [ "IPCTimeoutException", "structipc_1_1IPCTimeoutException.html", "structipc_1_1IPCTimeoutException" ],
    [ "IPCUserException", "structipc_1_1IPCUserException.html", "structipc_1_1IPCUserException" ],
    [ "MethodHandler", "structipc_1_1MethodHandler.html", "structipc_1_1MethodHandler" ],
    [ "MethodRequest", "classipc_1_1MethodRequest.html", "classipc_1_1MethodRequest" ],
    [ "MethodResult", "classipc_1_1MethodResult.html", "classipc_1_1MethodResult" ],
    [ "Processor", "classipc_1_1Processor.html", "classipc_1_1Processor" ],
    [ "RemovePeerRequest", "classipc_1_1RemovePeerRequest.html", "classipc_1_1RemovePeerRequest" ],
    [ "RequestQueue", "classipc_1_1RequestQueue.html", "classipc_1_1RequestQueue" ],
    [ "Result", "classipc_1_1Result.html", "classipc_1_1Result" ],
    [ "ResultBuilder", "classipc_1_1ResultBuilder.html", "classipc_1_1ResultBuilder" ],
    [ "ResultHandler", "structipc_1_1ResultHandler.html", "structipc_1_1ResultHandler" ],
    [ "SendResultRequest", "classipc_1_1SendResultRequest.html", "classipc_1_1SendResultRequest" ],
    [ "Service", "classipc_1_1Service.html", "classipc_1_1Service" ],
    [ "SignalHandler", "structipc_1_1SignalHandler.html", "structipc_1_1SignalHandler" ],
    [ "SignalRequest", "classipc_1_1SignalRequest.html", "classipc_1_1SignalRequest" ],
    [ "Socket", "classipc_1_1Socket.html", "classipc_1_1Socket" ]
];