var namespacecargo_1_1ipc =
[
    [ "epoll", "namespacecargo_1_1ipc_1_1epoll.html", "namespacecargo_1_1ipc_1_1epoll" ],
    [ "Client", "classcargo_1_1ipc_1_1Client.html", "classcargo_1_1ipc_1_1Client" ],
    [ "IPCException", "structcargo_1_1ipc_1_1IPCException.html", "structcargo_1_1ipc_1_1IPCException" ],
    [ "IPCParsingException", "structcargo_1_1ipc_1_1IPCParsingException.html", "structcargo_1_1ipc_1_1IPCParsingException" ],
    [ "IPCSerializationException", "structcargo_1_1ipc_1_1IPCSerializationException.html", "structcargo_1_1ipc_1_1IPCSerializationException" ],
    [ "IPCPeerDisconnectedException", "structcargo_1_1ipc_1_1IPCPeerDisconnectedException.html", "structcargo_1_1ipc_1_1IPCPeerDisconnectedException" ],
    [ "IPCNaughtyPeerException", "structcargo_1_1ipc_1_1IPCNaughtyPeerException.html", "structcargo_1_1ipc_1_1IPCNaughtyPeerException" ],
    [ "IPCRemovedPeerException", "structcargo_1_1ipc_1_1IPCRemovedPeerException.html", "structcargo_1_1ipc_1_1IPCRemovedPeerException" ],
    [ "IPCClosingException", "structcargo_1_1ipc_1_1IPCClosingException.html", "structcargo_1_1ipc_1_1IPCClosingException" ],
    [ "IPCTimeoutException", "structcargo_1_1ipc_1_1IPCTimeoutException.html", "structcargo_1_1ipc_1_1IPCTimeoutException" ],
    [ "IPCSocketException", "structcargo_1_1ipc_1_1IPCSocketException.html", "structcargo_1_1ipc_1_1IPCSocketException" ],
    [ "IPCUserException", "structcargo_1_1ipc_1_1IPCUserException.html", "structcargo_1_1ipc_1_1IPCUserException" ],
    [ "Acceptor", "classcargo_1_1ipc_1_1Acceptor.html", "classcargo_1_1ipc_1_1Acceptor" ],
    [ "AddPeerRequest", "classcargo_1_1ipc_1_1AddPeerRequest.html", "classcargo_1_1ipc_1_1AddPeerRequest" ],
    [ "EventQueue", "classcargo_1_1ipc_1_1EventQueue.html", "classcargo_1_1ipc_1_1EventQueue" ],
    [ "FinishRequest", "classcargo_1_1ipc_1_1FinishRequest.html", "classcargo_1_1ipc_1_1FinishRequest" ],
    [ "MethodRequest", "classcargo_1_1ipc_1_1MethodRequest.html", "classcargo_1_1ipc_1_1MethodRequest" ],
    [ "Processor", "classcargo_1_1ipc_1_1Processor.html", "classcargo_1_1ipc_1_1Processor" ],
    [ "RemoveMethodRequest", "classcargo_1_1ipc_1_1RemoveMethodRequest.html", "classcargo_1_1ipc_1_1RemoveMethodRequest" ],
    [ "RemovePeerRequest", "classcargo_1_1ipc_1_1RemovePeerRequest.html", "classcargo_1_1ipc_1_1RemovePeerRequest" ],
    [ "RequestQueue", "classcargo_1_1ipc_1_1RequestQueue.html", "classcargo_1_1ipc_1_1RequestQueue" ],
    [ "ResultBuilder", "classcargo_1_1ipc_1_1ResultBuilder.html", "classcargo_1_1ipc_1_1ResultBuilder" ],
    [ "SendResultRequest", "classcargo_1_1ipc_1_1SendResultRequest.html", "classcargo_1_1ipc_1_1SendResultRequest" ],
    [ "SignalRequest", "classcargo_1_1ipc_1_1SignalRequest.html", "classcargo_1_1ipc_1_1SignalRequest" ],
    [ "Socket", "classcargo_1_1ipc_1_1Socket.html", "classcargo_1_1ipc_1_1Socket" ],
    [ "IPCGSource", "structcargo_1_1ipc_1_1IPCGSource.html", "structcargo_1_1ipc_1_1IPCGSource" ],
    [ "MethodResult", "classcargo_1_1ipc_1_1MethodResult.html", "classcargo_1_1ipc_1_1MethodResult" ],
    [ "MethodHandler", "structcargo_1_1ipc_1_1MethodHandler.html", "structcargo_1_1ipc_1_1MethodHandler" ],
    [ "Result", "classcargo_1_1ipc_1_1Result.html", "classcargo_1_1ipc_1_1Result" ],
    [ "ResultHandler", "structcargo_1_1ipc_1_1ResultHandler.html", "structcargo_1_1ipc_1_1ResultHandler" ],
    [ "Service", "classcargo_1_1ipc_1_1Service.html", "classcargo_1_1ipc_1_1Service" ],
    [ "SignalHandler", "structcargo_1_1ipc_1_1SignalHandler.html", "structcargo_1_1ipc_1_1SignalHandler" ],
    [ "UniqueID", "classcargo_1_1ipc_1_1UniqueID.html", "classcargo_1_1ipc_1_1UniqueID" ],
    [ "hash", "classcargo_1_1ipc_1_1hash.html", null ],
    [ "hash< cargo::ipc::UniqueID >", "classcargo_1_1ipc_1_1hash_3_01cargo_1_1ipc_1_1UniqueID_01_4.html", "classcargo_1_1ipc_1_1hash_3_01cargo_1_1ipc_1_1UniqueID_01_4" ]
];