Vasum: vasum::cli Namespace Reference
vasum::cli Namespace Reference
Classes
class CommandLineInterface
Typedefs
typedef std::vector< std::string > Args
Functions
void lock_queue (const Args &)
void unlock_queue (const Args &)
void set_active_zone (const Args &argv)
void create_zone (const Args &argv)
void destroy_zone (const Args &argv)
void shutdown_zone (const Args &argv)
void start_zone (const Args &argv)
void lock_zone (const Args &argv)
void unlock_zone (const Args &argv)
void get_zones_status (const Args &)
void get_zone_ids (const Args &)
void get_active_zone_id (const Args &)
void lookup_zone_by_id (const Args &argv)
void grant_device (const Args &argv)
void revoke_device (const Args &argv)
void create_netdev_veth (const Args &argv)
void create_netdev_macvlan (const Args &argv)
void create_netdev_phys (const Args &argv)
void lookup_netdev_by_name (const Args &argv)
void destroy_netdev (const Args &argv)
void zone_get_netdevs (const Args &argv)
void netdev_get_ipv4_addr (const Args &argv)
void netdev_get_ipv6_addr (const Args &argv)
void netdev_set_ipv4_addr (const Args &argv)
void netdev_set_ipv6_addr (const Args &argv)
void netdev_up (const Args &argv)
void netdev_down (const Args &argv)
Typedef Documentation
typedef std::vector<std::string> vasum::cli::Args
Definition at line 41 of file command-line-interface.hpp.
Function Documentation
void vasum::cli::create_netdev_macvlan (const Args & argv)
Parses command line arguments and call vsm_create_netdev_macvlan
See Also
vsm_create_netdev_macvlan
Definition at line 440 of file command-line-interface.cpp.
References vsm_create_netdev_macvlan().
void vasum::cli::create_netdev_phys (const Args & argv)
Parses command line arguments and call vsm_create_netdev_phys
See Also
vsm_create_netdev_phys
Definition at line 455 of file command-line-interface.cpp.
References vsm_create_netdev_phys().
void vasum::cli::create_netdev_veth (const Args & argv)
Parses command line arguments and call vsm_create_netdev_veth
See Also
vsm_create_netdev_veth
Definition at line 426 of file command-line-interface.cpp.
References vsm_create_netdev_veth().
void vasum::cli::create_zone (const Args & argv)
Parses command line arguments and call vsm_create_zone
See Also
vsm_create_zone
Definition at line 268 of file command-line-interface.cpp.
References vsm_create_zone().
void vasum::cli::destroy_netdev (const Args & argv)
Parses command line arguments and call vsm_destroy_netdev
See Also
vsm_destroy_netdev
Definition at line 486 of file command-line-interface.cpp.
References vsm_destroy_netdev().
void vasum::cli::destroy_zone (const Args & argv)
Parses command line arguments and call vsm_destroy_zone
See Also
vsm_destroy_zone
Definition at line 283 of file command-line-interface.cpp.
References vsm_destroy_zone().
void vasum::cli::get_active_zone_id (const Args & argv)
Parses command line arguments and call vsm_get_active_zone_id
See Also
vsm_get_active_zone_id
Definition at line 380 of file command-line-interface.cpp.
References vsm_get_active_zone_id(), and vsm_string_free().
void vasum::cli::get_zone_ids (const Args & argv)
Parses command line arguments and call vsm_get_zone_ids
See Also
vsm_get_zone_ids
Definition at line 365 of file command-line-interface.cpp.
References vsm_array_string_free(), and vsm_get_zone_ids().
void vasum::cli::get_zones_status (const Args & argv)
Parses command line arguments and prints list of zone with some useful informations (id, state, terminal, root path)
Definition at line 338 of file command-line-interface.cpp.
References VsmZoneStructure::id, VsmZoneStructure::rootfs_path, VsmZoneStructure::state, VsmZoneStructure::terminal, vsm_array_string_free(), vsm_get_active_zone_id(), vsm_get_zone_ids(), vsm_lookup_zone_by_id(), vsm_string_free(), and vsm_zone_free().
void vasum::cli::grant_device (const Args & argv)
Parses command line arguments and call vsm_grant_device
See Also
vsm_grant_device
Definition at line 403 of file command-line-interface.cpp.
References vsm_grant_device().
void vasum::cli::lock_queue (const Args & argv)
Parses command line arguments and call vsm_set_active_zone
See Also
vsm_set_active_zone
Definition at line 247 of file command-line-interface.cpp.
References vsm_lock_queue().
void vasum::cli::lock_zone (const Args & argv)
Parses command line arguments and call vsm_lock_zone
See Also
vsm_lock_zone
Definition at line 316 of file command-line-interface.cpp.
References vsm_lock_zone().
void vasum::cli::lookup_netdev_by_name (const Args & argv)
Parses command line arguments and call vsm_lookup_netdev_by_name
See Also
vsm_lookup_netdev_by_name
Definition at line 468 of file command-line-interface.cpp.
References vsm_lookup_netdev_by_name(), and vsm_netdev_free().
void vasum::cli::lookup_zone_by_id (const Args & argv)
Parses command line arguments and call vsm_lookup_zone_by_id
See Also
vsm_lookup_zone_by_id
Definition at line 390 of file command-line-interface.cpp.
References vsm_lookup_zone_by_id(), and vsm_zone_free().
void vasum::cli::netdev_down (const Args & argv)
Parses command line arguments and call vsm_netdev_down
See Also
vsm_netdev_down
Definition at line 614 of file command-line-interface.cpp.
References vsm_netdev_down().
void vasum::cli::netdev_get_ipv4_addr (const Args & argv)
Parses command line arguments and prints result of vsm_netdev_get_ipv4_addr
See Also
vsm_netdev_get_ipv4_addr
Definition at line 523 of file command-line-interface.cpp.
References vsm_netdev_get_ipv4_addr().
void vasum::cli::netdev_get_ipv6_addr (const Args & argv)
Parses command line arguments and and prints result of vsm_netdev_get_ipv6_addr
See Also
vsm_netdev_get_ipv6_addr
Definition at line 543 of file command-line-interface.cpp.
References vsm_netdev_get_ipv6_addr().
void vasum::cli::netdev_set_ipv4_addr (const Args & argv)
Parses command line arguments and call vsm_netdev_set_ipv4_addr
See Also
vsm_netdev_set_ipv4_addr
Definition at line 563 of file command-line-interface.cpp.
References vsm_netdev_set_ipv4_addr().
void vasum::cli::netdev_set_ipv6_addr (const Args & argv)
Parses command line arguments and call vsm_netdev_set_ipv6_addr
See Also
vsm_netdev_set_ipv6_addr
Definition at line 582 of file command-line-interface.cpp.
References vsm_netdev_set_ipv6_addr().
void vasum::cli::netdev_up (const Args & argv)
Parses command line arguments and call vsm_netdev_up
See Also
vsm_netdev_up
Definition at line 601 of file command-line-interface.cpp.
References vsm_netdev_up().
void vasum::cli::revoke_device (const Args & argv)
Parses command line arguments and call vsm_revoke_device
See Also
vsm_revoke_device
Definition at line 415 of file command-line-interface.cpp.
References vsm_revoke_device().
void vasum::cli::set_active_zone (const Args & argv)
Parses command line arguments and call vsm_set_active_zone
See Also
vsm_set_active_zone
Definition at line 257 of file command-line-interface.cpp.
References vsm_set_active_zone().
void vasum::cli::shutdown_zone (const Args & argv)
Parses command line arguments and call vsm_shutdown_zone
See Also
vsm_shutdown_zone
Definition at line 294 of file command-line-interface.cpp.
References vsm_shutdown_zone().
void vasum::cli::start_zone (const Args & argv)
Parses command line arguments and call vsm_start_zone
See Also
vsm_start_zone
Definition at line 305 of file command-line-interface.cpp.
References vsm_start_zone().
void vasum::cli::unlock_queue (const Args & argv)
Parses command line arguments and call vsm_set_active_zone
See Also
vsm_set_active_zone
Definition at line 252 of file command-line-interface.cpp.
References vsm_unlock_queue().
void vasum::cli::unlock_zone (const Args & argv)
Parses command line arguments and call vsm_unlock_zone
See Also
vsm_unlock_zone
Definition at line 327 of file command-line-interface.cpp.
References vsm_unlock_zone().
void vasum::cli::zone_get_netdevs (const Args & argv)
Parses command line arguments and prints result of vsm_zone_get_netdevs
See Also
vsm_zone_get_netdevs
Definition at line 499 of file command-line-interface.cpp.
References vsm_array_string_free(), and vsm_zone_get_netdevs().