Vasum: vasum::netdev Namespace Reference
vasum::netdev Namespace Reference
Typedefs
typedef std::vector
< std::tuple< std::string,
std::string > > Attrs
Functions
void createVeth (const pid_t &nsPid, const string &nsDev, const string &hostDev)
void createMacvlan (const pid_t &nsPid, const string &nsDev, const string &hostDev, const macvlan_mode &mode)
void movePhys (const pid_t &nsPid, const string &devId)
std::vector< std::string > listNetdev (const pid_t &nsPid)
void destroyNetdev (const string &netdev, const pid_t pid)
void createBridge (const string &netdev)
Attrs getAttrs (const pid_t nsPid, const std::string &netdev)
void setAttrs (const pid_t nsPid, const std::string &netdev, const Attrs &attrs)
void deleteIpAddress (const pid_t nsPid, const std::string &netdev, const std::string &ip)
Typedef Documentation
typedef std::vector<std::tuple<std::string, std::string> > vasum::netdev::Attrs
Definition at line 38 of file netdev.hpp.
Function Documentation
void vasum::netdev::createBridge (const std::string & netdev)
Create bridge
Bridge are in BRIDGE_MODE_VEB (loopback) mode and it is software bridge (BRIDGE_FLAGS_MASTER)
Parameters
netdev bridge name
Definition at line 448 of file netdev.cpp.
References vasum::netlink::NetlinkMessage::beginNested(), BRIDGE_FLAGS_MASTER, vasum::netlink::NetlinkMessage::endNested(), IFLA_BRIDGE_FLAGS, vasum::netlink::NetlinkMessage::put(), and vasum::netlink::send().
void vasum::netdev::createMacvlan (const pid_t & nsPid, const string & nsDev, const string & hostDev, const macvlan_mode & mode)
Definition at line 390 of file netdev.cpp.
References destroyNetdev().
Referenced by vasum::Zone::createNetdevMacvlan().
void vasum::netdev::createVeth (const pid_t & nsPid, const string & nsDev, const string & hostDev)
Definition at line 371 of file netdev.cpp.
References destroyNetdev().
Referenced by vasum::Zone::createNetdevVeth().
void vasum::netdev::deleteIpAddress (const pid_t nsPid, const std::string & netdev, const std::string & ip)
Remove ipv4/ipv6 address from interface
Definition at line 603 of file netdev.cpp.
Referenced by vasum::Zone::deleteNetdevIpAddress().
void vasum::netdev::destroyNetdev (const string & netdev, const pid_t pid)
Definition at line 434 of file netdev.cpp.
References vasum::netlink::NetlinkMessage::put(), and vasum::netlink::send().
Referenced by createMacvlan(), createVeth(), and vasum::Zone::destroyNetdev().
Attrs vasum::netdev::getAttrs (const pid_t nsPid, const std::string & netdev)
Definition at line 470 of file netdev.cpp.
References vasum::netlink::NetlinkResponse::fetch(), vasum::netlink::NetlinkResponse::getAttributeType(), vasum::netlink::NetlinkResponse::hasAttribute(), vasum::netlink::NetlinkResponse::hasMessage(), vasum::netlink::NetlinkMessage::put(), vasum::netlink::send(), and vasum::netlink::NetlinkResponse::skipAttribute().
Referenced by vasum::Zone::getNetdevAttrs().
std::vector< std::string > vasum::netdev::listNetdev (const pid_t & nsPid)
Definition at line 416 of file netdev.cpp.
References vasum::netlink::NetlinkResponse::fetch(), vasum::netlink::NetlinkResponse::fetchNextMessage(), vasum::netlink::NetlinkResponse::hasMessage(), vasum::netlink::NetlinkMessage::put(), vasum::netlink::send(), and vasum::netlink::NetlinkResponse::skip().
Referenced by vasum::Zone::getNetdevList().
void vasum::netdev::movePhys (const pid_t & nsPid, const string & devId)
Definition at line 410 of file netdev.cpp.
Referenced by vasum::Zone::moveNetdev().
void vasum::netdev::setAttrs (const pid_t nsPid, const std::string & netdev, const Attrs & attrs)
Definition at line 527 of file netdev.cpp.
References vasum::netlink::NetlinkResponse::hasMessage(), vasum::netlink::NetlinkMessage::put(), and vasum::netlink::send().
Referenced by vasum::Zone::setNetdevAttrs().