Vasum: vasum::lxc Namespace Reference
vasum::lxc Namespace Reference
Classes
class LxcZone
Functions
bool setCgroup (const std::string &zoneName, const std::string &cgroupController, const std::string &cgroupName, const std::string &value)
bool getCgroup (const std::string &zoneName, const std::string &cgroupController, const std::string &cgroupName, std::string &value)
bool isDevice (const std::string &device)
bool setDeviceAccess (const std::string &zoneName, const std::string &device, bool grant, uint32_t flags)
Function Documentation
bool vasum::lxc::getCgroup (const std::string & zoneName, const std::string & cgroupController, const std::string & cgroupName, std::string & value)
Definition at line 81 of file cgroup.cpp.
References utils::readFirstLineOfFile().
Referenced by vasum::Zone::getSchedulerQuota().
bool vasum::lxc::isDevice (const std::string & device)
Definition at line 90 of file cgroup.cpp.
Referenced by vasum::ZonesManager::handleGrantDeviceCall(), and vasum::ZonesManager::handleRevokeDeviceCall().
bool vasum::lxc::setCgroup (const std::string & zoneName, const std::string & cgroupController, const std::string & cgroupName, const std::string & value)
Definition at line 71 of file cgroup.cpp.
References utils::saveFileContent().
Referenced by setDeviceAccess(), and vasum::Zone::setSchedulerParams().
bool vasum::lxc::setDeviceAccess (const std::string & zoneName, const std::string & device, bool grant, uint32_t flags)
Definition at line 104 of file cgroup.cpp.
References setCgroup().
Referenced by vasum::ZonesManager::handleGrantDeviceCall(), and vasum::ZonesManager::handleRevokeDeviceCall().