Vasum: vasum::ipc::IPCGSource Struct Reference
vasum::ipc::IPCGSource Struct Reference
#include <ipc-gsource.hpp>
Public Types
typedef std::function< void(FileDescriptor
fd, short pollEvent)> HandlerCallback
typedef std::shared_ptr
< IPCGSource > Pointer
Public Member Functions
~IPCGSource ()
IPCGSource ()=delete
IPCGSource (const IPCGSource &)=delete
IPCGSource & operator= (const IPCGSource &)=delete
void addFD (const FileDescriptor peerFD)
void removeFD (const FileDescriptor peerFD)
guint attach (GMainContext *context=nullptr)
void detach ()
void callHandler ()
Static Public Member Functions
static Pointer create (const HandlerCallback &handlerCallback)
static gboolean onHandlerCall (gpointer userData)
Private Types
typedef std::unique_lock
< std::recursive_mutex > Lock
Private Member Functions
IPCGSource (const HandlerCallback &handlerCallback)
Static Private Member Functions
static gboolean prepare (GSource *source, gint *timeout)
static gboolean check (GSource *source)
static gboolean dispatch (GSource *source, GSourceFunc callbacks, gpointer userData)
static void finalize (GSource *source)
Private Attributes
GSource mGSource
HandlerCallback mHandlerCallback
std::list< GPollFD > mGPollFDs
utils::CallbackGuard mGuard
std::recursive_mutex mStateMutex
Detailed Description
Class for connecting to the glib's loop. Creates a dedicated GSource.
It's supposed to be constructed ONLY with the static create method and destructed in a glib callback.
TODO:
waiting till the managed object (Client or Service) is destroyed before IPCGSource stops operating. For now programmer has to ensure this.
Definition at line 51 of file ipc-gsource.hpp.
Member Typedef Documentation
typedef std::function<void(FileDescriptor fd, short pollEvent)> vasum::ipc::IPCGSource::HandlerCallback
Definition at line 53 of file ipc-gsource.hpp.
typedef std::unique_lock<std::recursive_mutex> vasum::ipc::IPCGSource::Lock private
Definition at line 110 of file ipc-gsource.hpp.
typedef std::shared_ptr<IPCGSource> vasum::ipc::IPCGSource::Pointer
Definition at line 54 of file ipc-gsource.hpp.
Constructor & Destructor Documentation
vasum::ipc::IPCGSource::~IPCGSource ()
Definition at line 51 of file ipc-gsource.cpp.
Referenced by finalize().
vasum::ipc::IPCGSource::IPCGSource () delete
Referenced by create().
vasum::ipc::IPCGSource::IPCGSource (const IPCGSource &) delete
vasum::ipc::IPCGSource::IPCGSource (const HandlerCallback & handlerCallback) private
Definition at line 45 of file ipc-gsource.cpp.
Member Function Documentation
void vasum::ipc::IPCGSource::addFD (const FileDescriptor peerFD)
New file descriptor to listen on.
Parameters
peerFD file descriptor
Definition at line 91 of file ipc-gsource.cpp.
References mGPollFDs, mGSource, and mStateMutex.
guint vasum::ipc::IPCGSource::attach (GMainContext * context = nullptr)
Attach to the glib's GMainContext
Parameters
context where to connect
Returns
result of the g_source_attach call
Definition at line 117 of file ipc-gsource.cpp.
References mGSource.
void vasum::ipc::IPCGSource::callHandler ()
Locks the internal state mutex and calls the handler callback for each fd
Definition at line 141 of file ipc-gsource.cpp.
References mGPollFDs, mHandlerCallback, and mStateMutex.
gboolean vasum::ipc::IPCGSource::check (GSource * source) static private
GSourceFuncs' callback
Definition at line 174 of file ipc-gsource.cpp.
Referenced by create().
IPCGSource::Pointer vasum::ipc::IPCGSource::create (const HandlerCallback & handlerCallback) static
Creates the IPCGSource class in the memory allocated by glib. Calls IPCGSource's constructor
Parameters
handlerCallback event handling callback
Returns
pointer to the IPCGSource
Definition at line 56 of file ipc-gsource.cpp.
References check(), vasum::utils::createCallbackWrapper(), dispatch(), finalize(), IPCGSource(), onHandlerCall(), and prepare().
void vasum::ipc::IPCGSource::detach ()
After this method quits handlerCallback will not be called
Definition at line 124 of file ipc-gsource.cpp.
References mGPollFDs, mGSource, and mStateMutex.
gboolean vasum::ipc::IPCGSource::dispatch (GSource * source, GSourceFunc callbacks, gpointer userData) static private
GSourceFuncs' callback
Definition at line 183 of file ipc-gsource.cpp.
Referenced by create().
void vasum::ipc::IPCGSource::finalize (GSource * source) static private
GSourceFuncs' callback
Definition at line 199 of file ipc-gsource.cpp.
References ~IPCGSource().
Referenced by create().
gboolean vasum::ipc::IPCGSource::onHandlerCall (gpointer userData) static
Callback for the dispatch function
Definition at line 152 of file ipc-gsource.cpp.
Referenced by create().
IPCGSource& vasum::ipc::IPCGSource::operator= (const IPCGSource &) delete
gboolean vasum::ipc::IPCGSource::prepare (GSource * source, gint * timeout) static private
GSourceFuncs' callback
Definition at line 161 of file ipc-gsource.cpp.
Referenced by create().
void vasum::ipc::IPCGSource::removeFD (const FileDescriptor peerFD)
Removes the file descriptor from the GSource
Parameters
peerFD file descriptor
Definition at line 100 of file ipc-gsource.cpp.
References mGPollFDs, mGSource, and mStateMutex.
Member Data Documentation
std::list<GPollFD> vasum::ipc::IPCGSource::mGPollFDs private
Definition at line 139 of file ipc-gsource.hpp.
Referenced by addFD(), callHandler(), detach(), and removeFD().
GSource vasum::ipc::IPCGSource::mGSource private
Definition at line 137 of file ipc-gsource.hpp.
Referenced by addFD(), attach(), detach(), and removeFD().
utils::CallbackGuard vasum::ipc::IPCGSource::mGuard private
Definition at line 140 of file ipc-gsource.hpp.
HandlerCallback vasum::ipc::IPCGSource::mHandlerCallback private
Definition at line 138 of file ipc-gsource.hpp.
Referenced by callHandler().
std::recursive_mutex vasum::ipc::IPCGSource::mStateMutex private
Definition at line 141 of file ipc-gsource.hpp.
Referenced by addFD(), callHandler(), detach(), and removeFD().
The documentation for this struct was generated from the following files:
/home/dariusz/task/security-containers/common/ipc/ipc-gsource.hpp
/home/dariusz/task/security-containers/common/ipc/ipc-gsource.cpp