Vasum: /home/lkostyra/eclipse_workspaces/code/vasum/client/vasum-client.h File Reference
vasum-client.h File Reference
This file contains the public API for Vasum Client.
#include <stdint.h>
#include <sys/stat.h>
#include <netinet/ip.h>
#include <linux/if_link.h>
Classes
struct VsmZoneStructure
struct VsmNetdevStructure
Typedefs
typedef void * VsmClient
typedef char * VsmString
typedef VsmString * VsmArrayString
typedef unsigned int VsmSubscriptionId
typedef VsmZoneStructure * VsmZone
typedef VsmNetdevStructure * VsmNetdev
Enumerations
enum VsmStatus {
VSMCLIENT_CUSTOM_ERROR, VSMCLIENT_IO_ERROR, VSMCLIENT_OPERATION_FAILED, VSMCLIENT_INVALID_ARGUMENT,
VSMCLIENT_OTHER_ERROR, VSMCLIENT_SUCCESS
}
enum VsmZoneState {
STOPPED, STARTING, RUNNING, STOPPING,
ABORTING, FREEZING, FROZEN, THAWED,
LOCKED, MAX_STATE, ACTIVATING = 128
}
enum VsmNetdevType { VSMNETDEV_VETH, VSMNETDEV_PHYS, VSMNETDEV_MACVLAN }
enum VsmFileType { VSMFILE_DIRECTORY, VSMFILE_FIFO, VSMFILE_REGULAR }
enum VsmDispacherType { VSMDISPATCHER_EXTERNAL, VSMDISPATCHER_INTERNAL }
Functions
VsmStatus vsm_get_poll_fd (VsmClient client, int *fd)
VsmStatus vsm_enter_eventloop (VsmClient client, int flags, int timeout)
VsmStatus vsm_set_dispatcher_type (VsmClient client, VsmDispacherType dispacher)
VsmStatus vsm_get_dispatcher_type (VsmClient client, VsmDispacherType *dispacher)
VsmClient vsm_client_create ()
void vsm_client_free (VsmClient client)
VsmStatus vsm_get_status (VsmClient client)
const char * vsm_get_status_message (VsmClient client)
VsmStatus vsm_connect (VsmClient client)
VsmStatus vsm_connect_custom (VsmClient client, const char *address)
VsmStatus vsm_disconnect (VsmClient client)
void vsm_array_string_free (VsmArrayString astring)
void vsm_string_free (VsmString string)
void vsm_zone_free (VsmZone zone)
void vsm_netdev_free (VsmNetdev netdev)
Host API
Functions using org.tizen.vasum.host.manager D-Bus interface.
typedef void(* VsmZoneDbusStateCallback)(const char *zoneId, const char *address, void *data)
VsmStatus vsm_lock_queue (VsmClient client)
VsmStatus vsm_unlock_queue (VsmClient client)
VsmStatus vsm_get_zone_dbuses (VsmClient client, VsmArrayString *keys, VsmArrayString *values)
VsmStatus vsm_get_zone_ids (VsmClient client, VsmArrayString *array)
VsmStatus vsm_get_active_zone_id (VsmClient client, VsmString *id)
VsmStatus vsm_get_zone_rootpath (VsmClient client, const char *id, VsmString *rootpath)
VsmStatus vsm_lookup_zone_by_pid (VsmClient client, int pid, VsmString *id)
VsmStatus vsm_lookup_zone_by_id (VsmClient client, const char *id, VsmZone *zone)
VsmStatus vsm_lookup_zone_by_terminal_id (VsmClient client, int terminal, VsmString *id)
VsmStatus vsm_set_active_zone (VsmClient client, const char *id)
VsmStatus vsm_create_zone (VsmClient client, const char *id, const char *tname)
VsmStatus vsm_destroy_zone (VsmClient client, const char *id, int force)
VsmStatus vsm_shutdown_zone (VsmClient client, const char *id)
VsmStatus vsm_start_zone (VsmClient client, const char *id)
VsmStatus vsm_lock_zone (VsmClient client, const char *id)
VsmStatus vsm_unlock_zone (VsmClient client, const char *id)
VsmStatus vsm_add_state_callback (VsmClient client, VsmZoneDbusStateCallback zoneDbusStateCallback, void *data, VsmSubscriptionId *subscriptionId)
VsmStatus vsm_del_state_callback (VsmClient client, VsmSubscriptionId subscriptionId)
VsmStatus vsm_grant_device (VsmClient client, const char *zone, const char *device, uint32_t flags)
VsmStatus vsm_revoke_device (VsmClient client, const char *zone, const char *device)
VsmStatus vsm_zone_get_netdevs (VsmClient client, const char *zone, VsmArrayString *netdevIds)
VsmStatus vsm_netdev_get_ipv4_addr (VsmClient client, const char *zone, const char *netdevId, struct in_addr *addr)
VsmStatus vsm_netdev_get_ipv6_addr (VsmClient client, const char *zone, const char *netdevId, struct in6_addr *addr)
VsmStatus vsm_netdev_set_ipv4_addr (VsmClient client, const char *zone, const char *netdevId, struct in_addr *addr, int prefix)
VsmStatus vsm_netdev_set_ipv6_addr (VsmClient client, const char *zone, const char *netdevId, struct in6_addr *addr, int prefix)
VsmStatus vsm_netdev_del_ipv4_addr (VsmClient client, const char *zone, const char *netdevId, struct in_addr *addr, int prefix)
VsmStatus vsm_netdev_del_ipv6_addr (VsmClient client, const char *zone, const char *netdevId, struct in6_addr *addr, int prefix)
VsmStatus vsm_netdev_up (VsmClient client, const char *zone, const char *netdevId)
VsmStatus vsm_netdev_down (VsmClient client, const char *zone, const char *netdevId)
VsmStatus vsm_create_netdev_veth (VsmClient client, const char *zone, const char *zoneDev, const char *hostDev)
VsmStatus vsm_create_netdev_macvlan (VsmClient client, const char *zone, const char *zoneDev, const char *hostDev, enum macvlan_mode mode)
VsmStatus vsm_create_netdev_phys (VsmClient client, const char *zone, const char *devId)
VsmStatus vsm_lookup_netdev_by_name (VsmClient client, const char *zone, const char *netdevId, VsmNetdev *netdev)
VsmStatus vsm_destroy_netdev (VsmClient client, const char *zone, const char *devId)
VsmStatus vsm_declare_file (VsmClient client, const char *zone, VsmFileType type, const char *path, int32_t flags, mode_t mode)
VsmStatus vsm_declare_mount (VsmClient client, const char *source, const char *zone, const char *target, const char *type, uint64_t flags, const char *data)
VsmStatus vsm_declare_link (VsmClient client, const char *source, const char *zone, const char *target)
VsmStatus vsm_list_declarations (VsmClient client, const char *zone, VsmArrayString *declarations)
VsmStatus vsm_remove_declaration (VsmClient client, const char *zone, VsmString declaration)
Detailed Description
This file contains the public API for Vasum Client.
Author
Mateusz Malicki (m.mal.nosp@m.icki.nosp@m.2@sam.nosp@m.sung.nosp@m..com)
Example usage:
#include <stdio.h>
#include "client/vasum-client.h"
int main(int argc, char** argv)
{
    VsmStatus status;
    VsmClient client;
    VsmArrayString values = NULL;
    int ret = 0;
    client = vsm_client_create(); // create client handle
    if (NULL == client) {
        // error!
        ret = 1;
        goto finish;
    }
    status = vsm_connect(client); // connect to dbus
    if (VSMCLIENT_SUCCESS != status) {
        // error!
        ret = 1;
        goto finish;
    }
    status = vsm_get_zone_ids(client, &values);
    if (VSMCLIENT_SUCCESS != status) {
        // error!
        ret = 1;
        goto finish;
    }
    // print array
    for (VsmArrayString iValues = values; *iValues; iValues++) {
        printf("%s\n", *iValues);
    }
finish:
    vsm_array_string_free(values); // free memory
    vsm_client_free(client); // destroy client handle
    return ret;
}
Definition in file vasum-client.h.
Typedef Documentation
typedef VsmString* VsmArrayString
NULL-terminated array of strings type.
See Also
vsm_string_free
Definition at line 101 of file vasum-client.h.
typedef void* VsmClient
vasum-server's client pointer.
Definition at line 87 of file vasum-client.h.
typedef VsmNetdevStructure* VsmNetdev
Network device information
Definition at line 172 of file vasum-client.h.
typedef char* VsmString
NULL-terminated string type.
See Also
vsm_array_string_free
Definition at line 94 of file vasum-client.h.
typedef unsigned int VsmSubscriptionId
Subscription id
Definition at line 118 of file vasum-client.h.
typedef VsmZoneStructure* VsmZone
Zone information
Definition at line 150 of file vasum-client.h.
typedef void(* VsmZoneDbusStateCallback)(const char *zoneId, const char *address, void *data)
Zone's D-Bus state change callback function signature.
Parameters
[in] zoneId affected zone id
[in] address new D-Bus address
data custom user's data pointer passed to vsm_add_state_callback() function
Definition at line 402 of file vasum-client.h.
Enumeration Type Documentation
enum VsmDispacherType
Event dispacher types.
Example usage:
#include <pthread.h>
#include <assert.h>
#include <stdio.h>
#include <signal.h>
#include <sys/epoll.h>
#include <vasum-client.h>
volatile static sig_atomic_t running;
static int LOOP_INTERVAL = 1000; // ms
void* main_loop(void* client)
{
    int fd = -1;
    VsmStatus status = vsm_get_poll_fd(client, &fd);
    assert(VSMCLIENT_SUCCESS == status);
    while (running) {
        struct epoll_event event;
        int num = epoll_wait(fd, &event, 1, LOOP_INTERVAL);
        if (num > 0) {
            status = vsm_enter_eventloop(client, 0 , 0);
            assert(VSMCLIENT_SUCCESS == status);
        }
    }
    return NULL;
}
int main(int argc, char** argv)
{
    pthread_t loop;
    VsmStatus status;
    VsmClient client;
    int ret = 0;
    client = vsm_client_create();
    assert(client);
    status = vsm_set_dispatcher_type(client, VSMDISPATCHER_EXTERNAL);
    assert(VSMCLIENT_SUCCESS == status);
    status = vsm_connect(client);
    assert(VSMCLIENT_SUCCESS == status);
    // start event loop
    running = 1;
    ret = pthread_create(&loop, NULL, main_loop, client);
    assert(ret == 0);
    // make vsm_* calls on client
    // ...
    status = vsm_disconnect(client);
    assert(VSMCLIENT_SUCCESS == status);
    //stop event loop
    running = 0;
    ret = pthread_join(loop, NULL);
    assert(ret == 0);
    vsm_client_free(client); // destroy client handle
    return ret;
}
Enumerator
VSMDISPATCHER_EXTERNAL
User must handle dispatching messages
VSMDISPATCHER_INTERNAL
Library will take care of dispatching messages
Definition at line 252 of file vasum-client.h.
enum VsmFileType
File type
Enumerator
VSMFILE_DIRECTORY
VSMFILE_FIFO
VSMFILE_REGULAR
Definition at line 177 of file vasum-client.h.
enum VsmNetdevType
Netowrk device type
Enumerator
VSMNETDEV_VETH
VSMNETDEV_PHYS
VSMNETDEV_MACVLAN
Definition at line 155 of file vasum-client.h.
enum VsmStatus
Completion status of communication function.
Enumerator
VSMCLIENT_CUSTOM_ERROR
User specified error
VSMCLIENT_IO_ERROR
Input/Output error
VSMCLIENT_OPERATION_FAILED
Operation failed
VSMCLIENT_INVALID_ARGUMENT
Invalid argument
VSMCLIENT_OTHER_ERROR
Other error
VSMCLIENT_SUCCESS
Success
Definition at line 106 of file vasum-client.h.
enum VsmZoneState
States of zone
Enumerator
STOPPED
STARTING
RUNNING
STOPPING
ABORTING
FREEZING
FROZEN
THAWED
LOCKED
MAX_STATE
ACTIVATING
Definition at line 123 of file vasum-client.h.
Function Documentation
VsmStatus vsm_add_state_callback (VsmClient client, VsmZoneDbusStateCallback zoneDbusStateCallback, void * data, VsmSubscriptionId * subscriptionId)
Register dbus state change callback function.
Note
The callback function will be invoked on a different thread.
Parameters
[in] client vasum-server's client
[in] zoneDbusStateCallback callback function
[in] data some extra data that will be passed to callback function
[out] subscriptionId subscription identifier that can be used to unsubscribe signal, pointer can be NULL.
Returns
status of this function call
Definition at line 215 of file vasum-client.cpp.
void vsm_array_string_free (VsmArrayString astring)
Release VsmArrayString.
Parameters
[in] astring VsmArrayString
Definition at line 99 of file vasum-client.cpp.
References vsm_string_free().
Referenced by vasum::cli::get_zone_ids(), vasum::cli::get_zones_status(), and vasum::cli::zone_get_netdevs().
VsmClient vsm_client_create ()
Create a new vasum-server's client.
Returns
Created client pointer or NULL on failure.
Definition at line 78 of file vasum-client.cpp.
Referenced by vasum::cli::CommandLineInterface::connect().
void vsm_client_free (VsmClient client)
Release client resources.
Parameters
[in] client vasum-server's client
Definition at line 128 of file vasum-client.cpp.
Referenced by vasum::cli::CommandLineInterface::connect(), and vasum::cli::CommandLineInterface::disconnect().
VsmStatus vsm_connect (VsmClient client)
Connect client to the vasum-server.
Parameters
[in] client vasum-server's client
Returns
status of this function call
Definition at line 84 of file vasum-client.cpp.
Referenced by vasum::cli::CommandLineInterface::connect().
VsmStatus vsm_connect_custom (VsmClient client, const char * address)
Connect client to the vasum-server via custom address.
Parameters
[in] client vasum-server's client
[in] address dbus address
Returns
status of this function call
Definition at line 89 of file vasum-client.cpp.
VsmStatus vsm_create_netdev_macvlan (VsmClient client, const char * zone, const char * zoneDev, const char * hostDev, enum macvlan_mode mode)
Create macvlab in zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] zoneDev in host network device id
[in] hostDev in zone network device id
Returns
status of this function call
Definition at line 322 of file vasum-client.cpp.
Referenced by vasum::cli::create_netdev_macvlan().
VsmStatus vsm_create_netdev_phys (VsmClient client, const char * zone, const char * devId)
Create/move phys netdev in/to zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] devId network device id
Returns
status of this function call
Definition at line 331 of file vasum-client.cpp.
Referenced by vasum::cli::create_netdev_phys().
VsmStatus vsm_create_netdev_veth (VsmClient client, const char * zone, const char * zoneDev, const char * hostDev)
Create veth netdev in zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] zoneDev in host network device id
[in] hostDev in zone network device id
Returns
status of this function call
Definition at line 314 of file vasum-client.cpp.
Referenced by vasum::cli::create_netdev_veth().
VsmStatus vsm_create_zone (VsmClient client, const char * id, const char * tname)
Create and add zone
Parameters
[in] client vasum-server's client
[in] id zone id
[in] tname template name, NULL is equivalent to "default"
Returns
status of this function call
Definition at line 185 of file vasum-client.cpp.
Referenced by vasum::cli::create_zone().
VsmStatus vsm_declare_file (VsmClient client, const char * zone, VsmFileType type, const char * path, int32_t flags, mode_t mode)
Create file, directory or pipe in zone
Declare file, directory or pipe that will be created while zone startup
Parameters
[in] client vasum-server's client
[in] type file type
[in] zone zone id
[in] path path to file
[in] flags if O_CREAT bit is set then file will be created in zone, otherwise file will by copied from host; it is meaningful only when O_CREAT is set
[in] mode mode of file
Returns
status of this function call
Definition at line 349 of file vasum-client.cpp.
VsmStatus vsm_declare_link (VsmClient client, const char * source, const char * zone, const char * target)
Create link in zone
Declare link that will be created while zone startup Parameters are passed to link system function
Parameters
[in] client vasum-server's client
[in] source path to link source (in host)
[in] zone zone id
[in] target path to link name (in zone)
Returns
status of this function call
Definition at line 371 of file vasum-client.cpp.
VsmStatus vsm_declare_mount (VsmClient client, const char * source, const char * zone, const char * target, const char * type, uint64_t flags, const char * data)
Create mount point in zone
Declare mount that will be created while zone startup Parameters are passed to mount system function
Parameters
[in] client vasum-server's client
[in] source device path (path in host)
[in] zone zone id
[in] target mount point (path in zone)
[in] type filesystem type
[in] flags mount flags as in mount function
[in] data additional data as in mount function
Returns
status of this function call
Definition at line 360 of file vasum-client.cpp.
VsmStatus vsm_del_state_callback (VsmClient client, VsmSubscriptionId subscriptionId)
Unregister dbus state change callback function.
Parameters
[in] client vasum-server's client
[in] subscriptionId subscription identifier returned by vsm_add_state_callback
Returns
status of this function call
Definition at line 223 of file vasum-client.cpp.
VsmStatus vsm_destroy_netdev (VsmClient client, const char * zone, const char * devId)
Remove netdev from zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] devId network device id
Returns
status of this function call
Definition at line 344 of file vasum-client.cpp.
Referenced by vasum::cli::destroy_netdev().
VsmStatus vsm_destroy_zone (VsmClient client, const char * id, int force)
Remove zone
Parameters
[in] client vasum-server's client
[in] id zone id
[in] force if 0 data will be kept, otherwise data will be lost
Returns
status of this function call
Definition at line 190 of file vasum-client.cpp.
Referenced by vasum::cli::destroy_zone().
VsmStatus vsm_disconnect (VsmClient client)
Disconnect client from vasum-server.
Parameters
[in] client vasum-server's client
Returns
status of this function call
Definition at line 94 of file vasum-client.cpp.
Referenced by vasum::cli::CommandLineInterface::disconnect().
VsmStatus vsm_enter_eventloop (VsmClient client, int flags, int timeout)
Wait for an I/O event on a vsm client
vsm_enter_eventloop() waits for event on the vsm client
The call waits for a maximum time of timout milliseconds. Specifying a timeout of -1 makes vsm_enter_eventloop() wait indefinitely, while specifying a timeout equal to zero makes vsm_enter_eventloop() to return immediately even if no events are available.
Parameters
[in] client vasum-server's client
[in] flags Reserved
[in] timeout Timeout time (milisecond), -1 is infinite
Returns
status of this function call
Definition at line 63 of file vasum-client.cpp.
VsmStatus vsm_get_active_zone_id (VsmClient client, VsmString * id)
Get active (foreground) zone name.
Parameters
[in] client vasum-server's client
[out] id active zone name
Returns
status of this function call
Remarks
Use vsm_string_free() to free memory occupied by id.
Definition at line 155 of file vasum-client.cpp.
Referenced by vasum::cli::get_active_zone_id(), and vasum::cli::get_zones_status().
VsmStatus vsm_get_dispatcher_type (VsmClient client, VsmDispacherType * dispacher)
Get dispatching method
Parameters
[in] client vasum-server's client
[out] dispacher dispatching method
Returns
status of this function call
Definition at line 73 of file vasum-client.cpp.
VsmStatus vsm_get_poll_fd (VsmClient client, int * fd)
Get file descriptor associated with event dispatcher of zone client
The function vsm_get_poll_fd() returns the file descriptor associated with the event dispatcher of vsm client. The file descriptor can be bound to another I/O multiplexing facilities like epoll, select, and poll.
Parameters
[in] client vsm client
[out] fd epoll file descriptor
Returns
status of this function call
Definition at line 58 of file vasum-client.cpp.
VsmStatus vsm_get_status (VsmClient client)
Get status code of last vasum-server communication.
Parameters
[in] client vasum-server's client
Returns
status of this function call
Definition at line 140 of file vasum-client.cpp.
const char* vsm_get_status_message (VsmClient client)
Get status message of the last vasum-server communication.
Parameters
[in] client vasum-server's client
Returns
last status message from vasum-server communication
Definition at line 135 of file vasum-client.cpp.
Referenced by vasum::cli::CommandLineInterface::connect(), vasum::cli::CommandLineInterface::disconnect(), and vasum::cli::CommandLineInterface::executeCallback().
VsmStatus vsm_get_zone_dbuses (VsmClient client, VsmArrayString * keys, VsmArrayString * values)
Get dbus address of each zone.
Parameters
[in] client vasum-server's client
[out] keys array of zones name
[out] values array of zones dbus address
Returns
status of this function call
Postcondition
keys[i] corresponds to values[i]
Remarks
Use vsm_array_string_free() to free memory occupied by keys and values.
Definition at line 145 of file vasum-client.cpp.
VsmStatus vsm_get_zone_ids (VsmClient client, VsmArrayString * array)
Get zones name.
Parameters
[in] client vasum-server's client
[out] array array of zones name
Returns
status of this function call
Remarks
Use vsm_array_string_free() to free memory occupied by array.
Definition at line 150 of file vasum-client.cpp.
Referenced by vasum::cli::get_zone_ids(), and vasum::cli::get_zones_status().
VsmStatus vsm_get_zone_rootpath (VsmClient client, const char * id, VsmString * rootpath)
Get zone rootfs path.
Parameters
[in] client vasum-server's client
[in] id zone name
[out] rootpath zone rootfs path
Returns
status of this function call
Remarks
Use vsm_string_free() to free memory occupied by rootpath.
Definition at line 160 of file vasum-client.cpp.
VsmStatus vsm_grant_device (VsmClient client, const char * zone, const char * device, uint32_t flags)
Grant access to device
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] device device path
[in] flags access flags
Returns
status of this function call
Definition at line 228 of file vasum-client.cpp.
Referenced by vasum::cli::grant_device().
VsmStatus vsm_list_declarations (VsmClient client, const char * zone, VsmArrayString * declarations)
Get all declarations
Gets all declarations of resourcies (
See Also
vsm_declare_link,
vsm_declare_mount,
::vsm_declare_linki)
Parameters
[in] client vasum-server's client
[in] zone zone id
[out] declarations array of declarations id
Returns
status of this function call
Definition at line 379 of file vasum-client.cpp.
VsmStatus vsm_lock_queue (VsmClient client)
Lock the command queue exclusively.
Parameters
[in] client vasum-server's client
Returns
status of this function call
Definition at line 48 of file vasum-client.cpp.
Referenced by vasum::cli::lock_queue().
VsmStatus vsm_lock_zone (VsmClient client, const char * id)
Lock zone
Parameters
[in] client vasum-server's client
[in] id zone name
Returns
status of this function call
Definition at line 205 of file vasum-client.cpp.
Referenced by vasum::cli::lock_zone().
VsmStatus vsm_lookup_netdev_by_name (VsmClient client, const char * zone, const char * netdevId, VsmNetdev * netdev)
Get netdev informations
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId network device id
[out] netdev netdev informations
Returns
status of this function call
Remarks
Use vsm_netdev_free() to free memory occupied by netdev.
Definition at line 336 of file vasum-client.cpp.
Referenced by vasum::cli::lookup_netdev_by_name().
VsmStatus vsm_lookup_zone_by_id (VsmClient client, const char * id, VsmZone * zone)
Get zone informations of zone with given id.
Parameters
[in] client vasum-server's client
[in] id zone name
[out] zone zone informations
Returns
status of this function call
Remarks
Use vsm_zone_free() to free memory occupied by zone
Definition at line 170 of file vasum-client.cpp.
Referenced by vasum::cli::get_zones_status(), and vasum::cli::lookup_zone_by_id().
VsmStatus vsm_lookup_zone_by_pid (VsmClient client, int pid, VsmString * id)
Get zone name of process with given pid.
Parameters
[in] client vasum-server's client
[in] pid process id
[out] id active zone name
Returns
status of this function call
Remarks
Use vsm_string_free() to free memory occupied by id.
Definition at line 165 of file vasum-client.cpp.
VsmStatus vsm_lookup_zone_by_terminal_id (VsmClient client, int terminal, VsmString * id)
Get zone name with given terminal.
Parameters
[in] client vasum-server's client
[in] terminal terminal id
[out] id zone name with given terminal
Returns
status of this function call
Remarks
Use vsm_string_free() to free memory occupied by id.
Definition at line 175 of file vasum-client.cpp.
VsmStatus vsm_netdev_del_ipv4_addr (VsmClient client, const char * zone, const char * netdevId, struct in_addr * addr, int prefix)
Remove ipv4 address from netdev
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId network device id
[in] addr ipv4 address
[in] prefix bit-length of the network prefix
Returns
status of this function call
Definition at line 282 of file vasum-client.cpp.
VsmStatus vsm_netdev_del_ipv6_addr (VsmClient client, const char * zone, const char * netdevId, struct in6_addr * addr, int prefix)
Remove ipv6 address from netdev
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId network device id
[in] addr ipv6 address
[in] prefix bit-length of the network prefix
Returns
status of this function call
Definition at line 291 of file vasum-client.cpp.
VsmStatus vsm_netdev_down (VsmClient client, const char * zone, const char * netdevId)
Turn down a network device in the zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId netdev id
Returns
status of this function call
Definition at line 307 of file vasum-client.cpp.
Referenced by vasum::cli::netdev_down().
void vsm_netdev_free (VsmNetdev netdev)
Release VsmNetdev
Parameters
netdev VsmNetdev
Definition at line 122 of file vasum-client.cpp.
References VsmNetdevStructure::name.
Referenced by vasum::cli::lookup_netdev_by_name().
VsmStatus vsm_netdev_get_ipv4_addr (VsmClient client, const char * zone, const char * netdevId, struct in_addr * addr)
Get ipv4 address for given netdevId
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId netdev id
[out] addr ipv4 address
Returns
status of this function call
Definition at line 248 of file vasum-client.cpp.
Referenced by vasum::cli::netdev_get_ipv4_addr().
VsmStatus vsm_netdev_get_ipv6_addr (VsmClient client, const char * zone, const char * netdevId, struct in6_addr * addr)
Get ipv6 address for given netdevId
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId netdev id
[out] addr ipv6 address
Returns
status of this function call
Definition at line 256 of file vasum-client.cpp.
Referenced by vasum::cli::netdev_get_ipv6_addr().
VsmStatus vsm_netdev_set_ipv4_addr (VsmClient client, const char * zone, const char * netdevId, struct in_addr * addr, int prefix)
Set ipv4 address for given netdevId
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId netdev id
[in] addr ipv4 address
[in] prefix bit-length of the network prefix
Returns
status of this function call
Definition at line 264 of file vasum-client.cpp.
Referenced by vasum::cli::netdev_set_ipv4_addr().
VsmStatus vsm_netdev_set_ipv6_addr (VsmClient client, const char * zone, const char * netdevId, struct in6_addr * addr, int prefix)
Set ipv6 address for given netdevId
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId netdev id
[in] addr ipv6 address
[in] prefix bit-length of the network prefix
Returns
status of this function call
Definition at line 273 of file vasum-client.cpp.
Referenced by vasum::cli::netdev_set_ipv6_addr().
VsmStatus vsm_netdev_up (VsmClient client, const char * zone, const char * netdevId)
Turn up a network device in the zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId netdev id
Returns
status of this function call
Definition at line 300 of file vasum-client.cpp.
Referenced by vasum::cli::netdev_up().
VsmStatus vsm_remove_declaration (VsmClient client, const char * zone, VsmString declaration)
Remove declaration
Removes given declaration by its id (
See Also
vsm_list_declarations)
Parameters
[in] client vasum-server's client
[in] zone zone id
[in] declaration declaration id
Returns
status of this function call
Definition at line 386 of file vasum-client.cpp.
VsmStatus vsm_revoke_device (VsmClient client, const char * zone, const char * device)
Revoke access to device
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] device device path
Returns
status of this function call
Definition at line 236 of file vasum-client.cpp.
Referenced by vasum::cli::revoke_device().
VsmStatus vsm_set_active_zone (VsmClient client, const char * id)
Set active (foreground) zone.
Parameters
[in] client vasum-server's client
[in] id zone name
Returns
status of this function call
Definition at line 180 of file vasum-client.cpp.
Referenced by vasum::cli::set_active_zone().
VsmStatus vsm_set_dispatcher_type (VsmClient client, VsmDispacherType dispacher)
Set dispatching method
Parameters
[in] client vasum-server's client
[in] dispacher dispatching method
Returns
status of this function call
Definition at line 68 of file vasum-client.cpp.
VsmStatus vsm_shutdown_zone (VsmClient client, const char * id)
Shutdown zone
Parameters
[in] client vasum-server's client
[in] id zone name
Returns
status of this function call
Definition at line 195 of file vasum-client.cpp.
Referenced by vasum::cli::shutdown_zone().
VsmStatus vsm_start_zone (VsmClient client, const char * id)
Start zone
Parameters
[in] client vasum-server's client
[in] id zone name
Returns
status of this function call
Definition at line 200 of file vasum-client.cpp.
Referenced by vasum::cli::start_zone().
void vsm_string_free (VsmString string)
Release VsmString.
Parameters
string VsmString
Definition at line 110 of file vasum-client.cpp.
Referenced by vasum::cli::get_active_zone_id(), vasum::cli::get_zones_status(), and vsm_array_string_free().
VsmStatus vsm_unlock_queue (VsmClient client)
Unlock the command queue.
Parameters
[in] client vasum-server's client
Returns
status of this function call
Definition at line 53 of file vasum-client.cpp.
Referenced by vasum::cli::unlock_queue().
VsmStatus vsm_unlock_zone (VsmClient client, const char * id)
Unlock zone
Parameters
[in] client vasum-server's client
[in] id zone name
Returns
status of this function call
Definition at line 210 of file vasum-client.cpp.
Referenced by vasum::cli::unlock_zone().
void vsm_zone_free (VsmZone zone)
Release VsmZone
Parameters
zone VsmZone
Definition at line 115 of file vasum-client.cpp.
References VsmZoneStructure::id, and VsmZoneStructure::rootfs_path.
Referenced by vasum::cli::get_zones_status(), and vasum::cli::lookup_zone_by_id().
VsmStatus vsm_zone_get_netdevs (VsmClient client, const char * zone, VsmArrayString * netdevIds)
Get array of netdev from given zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[out] netdevIds array of netdev id
Returns
status of this function call
Remarks
Use vsm_array_string_free() to free memory occupied by netdevIds.
Definition at line 241 of file vasum-client.cpp.
Referenced by vasum::cli::zone_get_netdevs().