var searchData=
[
  ['samethreadguard',['SameThreadGuard',['../classutils_1_1SameThreadGuard.html',1,'utils']]],
  ['scopedgerror',['ScopedGError',['../classutils_1_1ScopedGError.html',1,'utils']]],
  ['scopedglibloop',['ScopedGlibLoop',['../classutils_1_1ScopedGlibLoop.html',1,'utils']]],
  ['sendresultrequest',['SendResultRequest',['../classipc_1_1SendResultRequest.html',1,'ipc']]],
  ['server',['Server',['../classvasum_1_1Server.html',1,'vasum']]],
  ['serverexception',['ServerException',['../structvasum_1_1ServerException.html',1,'vasum']]],
  ['service',['Service',['../classipc_1_1Service.html',1,'ipc']]],
  ['setnetdevattrsin',['SetNetDevAttrsIn',['../structvasum_1_1api_1_1SetNetDevAttrsIn.html',1,'vasum::api']]],
  ['sharedstate',['SharedState',['../classutils_1_1CallbackGuard_1_1SharedState.html',1,'utils::CallbackGuard']]],
  ['signal',['Signal',['../classvasum_1_1HostIPCConnection_1_1Signal.html',1,'vasum::HostIPCConnection']]],
  ['signalfd',['SignalFD',['../classutils_1_1SignalFD.html',1,'utils']]],
  ['signalhandler',['SignalHandler',['../structipc_1_1SignalHandler.html',1,'ipc']]],
  ['signalhandler_3c_20void_20_3e',['SignalHandler&lt; void &gt;',['../structipc_1_1SignalHandler.html',1,'ipc']]],
  ['signalhandlers',['SignalHandlers',['../structipc_1_1Processor_1_1SignalHandlers.html',1,'ipc::Processor']]],
  ['signalrequest',['SignalRequest',['../classipc_1_1SignalRequest.html',1,'ipc']]],
  ['socket',['Socket',['../classipc_1_1Socket.html',1,'ipc']]],
  ['sstreamwrapper',['SStreamWrapper',['../classlogger_1_1SStreamWrapper.html',1,'logger']]],
  ['start',['Start',['../classlxcpp_1_1Start.html',1,'lxcpp']]],
  ['statement',['Statement',['../structconfig_1_1sqlite3_1_1Statement.html',1,'config::sqlite3']]],
  ['status',['Status',['../structClient_1_1Status.html',1,'Client']]],
  ['stderrbackend',['StderrBackend',['../classlogger_1_1StderrBackend.html',1,'logger']]],
  ['string',['String',['../structvasum_1_1api_1_1String.html',1,'vasum::api']]],
  ['stringpair',['StringPair',['../structvasum_1_1api_1_1StringPair.html',1,'vasum::api']]],
  ['syslogbackend',['SyslogBackend',['../classlogger_1_1SyslogBackend.html',1,'logger']]],
  ['systemdjournalbackend',['SystemdJournalBackend',['../classlogger_1_1SystemdJournalBackend.html',1,'logger']]]
];
