Vasum: vasum::ZoneAdmin Class Reference
vasum::ZoneAdmin Class Reference
#include <zone-admin.hpp>
Public Types
typedef netdev::Attrs NetdevAttrs
Public Member Functions
ZoneAdmin (const std::string &zoneId, const std::string &zonesPath, const std::string &lxcTemplatePrefix, const ZoneConfig &config, const ZoneDynamicConfig &dynamicConfig)
virtual ~ZoneAdmin ()
const std::string & getId () const
void start ()
void stop ()
void destroy ()
bool isRunning ()
bool isStopped ()
void suspend ()
void resume ()
bool isPaused ()
void setSchedulerLevel (SchedulerLevel sched)
void setDetachOnExit ()
void setDestroyOnExit ()
std::int64_t getSchedulerQuota ()
void createNetdevVeth (const std::string &zoneDev, const std::string &hostDev)
void createNetdevMacvlan (const std::string &zoneDev, const std::string &hostDev, const uint32_t &mode)
void moveNetdev (const std::string &devId)
void destroyNetdev (const std::string &devId)
void setNetdevAttrs (const std::string &netdev, const NetdevAttrs &attrs)
NetdevAttrs getNetdevAttrs (const std::string &netdev)
std::vector< std::string > getNetdevList ()
void deleteNetdevIpAddress (const std::string &netdev, const std::string &ip)
Private Member Functions
void setSchedulerParams (std::uint64_t cpuShares, std::uint64_t vcpuPeriod, std::int64_t vcpuQuota)
Private Attributes
const ZoneConfig & mConfig
const ZoneDynamicConfig & mDynamicConfig
lxc::LxcZone mZone
const std::string mId
bool mDetachOnExit
bool mDestroyOnExit
Detailed Description
Definition at line 41 of file zone-admin.hpp.
Member Typedef Documentation
typedef netdev::Attrs vasum::ZoneAdmin::NetdevAttrs
Definition at line 44 of file zone-admin.hpp.
Constructor & Destructor Documentation
vasum::ZoneAdmin::ZoneAdmin (const std::string & zoneId, const std::string & zonesPath, const std::string & lxcTemplatePrefix, const ZoneConfig & config, const ZoneDynamicConfig & dynamicConfig)
ZoneAdmin constructor
Parameters
zoneId zone id
zonesPath directory where zones are defined (lxc configs, rootfs etc)
lxcTemplatePrefix directory where templates are stored
config zones config
dynamicConfig zones dynamic config
Definition at line 47 of file zone-admin.cpp.
References vasum::utils::CArrayBuilder< T >::add(), vasum::utils::CArrayBuilder< T >::c_array(), vasum::lxc::LxcZone::create(), vasum::utils::getAbsolutePath(), vasum::ZoneDynamicConfig::ipv4, vasum::ZoneDynamicConfig::ipv4Gateway, vasum::lxc::LxcZone::isDefined(), vasum::ZoneConfig::lxcTemplate, mId, mZone, and vasum::ZoneDynamicConfig::vt.
vasum::ZoneAdmin::~ZoneAdmin () virtual
Definition at line 87 of file zone-admin.cpp.
References vasum::lxc::LxcZone::destroy(), mDestroyOnExit, mDetachOnExit, mId, mZone, and vasum::lxc::LxcZone::stop().
Member Function Documentation
void vasum::ZoneAdmin::createNetdevMacvlan (const std::string & zoneDev, const std::string & hostDev, const uint32_t & mode)
Create macvlan network device
Definition at line 286 of file zone-admin.cpp.
References vasum::netdev::createMacvlan(), vasum::lxc::LxcZone::getInitPid(), and mZone.
void vasum::ZoneAdmin::createNetdevVeth (const std::string & zoneDev, const std::string & hostDev)
Create veth network device
Definition at line 280 of file zone-admin.cpp.
References vasum::netdev::createVeth(), vasum::lxc::LxcZone::getInitPid(), and mZone.
void vasum::ZoneAdmin::deleteNetdevIpAddress (const std::string & netdev, const std::string & ip)
Remove ipv4/ipv6 address from network device
Definition at line 318 of file zone-admin.cpp.
References vasum::netdev::deleteIpAddress(), vasum::lxc::LxcZone::getInitPid(), and mZone.
void vasum::ZoneAdmin::destroy ()
Destroy stopped zone. In particular it removes whole zones rootfs.
Definition at line 170 of file zone-admin.cpp.
References vasum::lxc::LxcZone::destroy(), mId, and mZone.
void vasum::ZoneAdmin::destroyNetdev (const std::string & devId)
Destroy network device in zone
Definition at line 298 of file zone-admin.cpp.
References vasum::netdev::destroyNetdev(), vasum::lxc::LxcZone::getInitPid(), and mZone.
const std::string & vasum::ZoneAdmin::getId () const
Get the zone id
Definition at line 111 of file zone-admin.cpp.
References mId.
ZoneAdmin::NetdevAttrs vasum::ZoneAdmin::getNetdevAttrs (const std::string & netdev)
Get network device attributes
Definition at line 308 of file zone-admin.cpp.
References vasum::netdev::getAttrs(), vasum::lxc::LxcZone::getInitPid(), and mZone.
std::vector< std::string > vasum::ZoneAdmin::getNetdevList ()
Get network device list
Definition at line 313 of file zone-admin.cpp.
References vasum::lxc::LxcZone::getInitPid(), vasum::netdev::listNetdev(), and mZone.
std::int64_t vasum::ZoneAdmin::getSchedulerQuota ()
Returns
Scheduler CFS quota, TODO: this function is only for UNIT TESTS
Definition at line 270 of file zone-admin.cpp.
References vasum::lxc::getCgroup(), and mId.
bool vasum::ZoneAdmin::isPaused ()
Returns
Is the zone in a paused state?
Definition at line 214 of file zone-admin.cpp.
References vasum::lxc::LxcZone::FROZEN, vasum::lxc::LxcZone::getState(), and mZone.
bool vasum::ZoneAdmin::isRunning ()
Returns
Is the zone running?
Definition at line 182 of file zone-admin.cpp.
References vasum::lxc::LxcZone::getState(), mZone, and vasum::lxc::LxcZone::RUNNING.
Referenced by setSchedulerLevel(), and start().
bool vasum::ZoneAdmin::isStopped ()
Check if the zone is stopped. It's NOT equivalent to !isRunning, because it checks different internal lxc states. There are other states, (e.g. paused) when the zone isn't running nor stopped.
Returns
Is the zone stopped?
Definition at line 188 of file zone-admin.cpp.
References vasum::lxc::LxcZone::getState(), mZone, and vasum::lxc::LxcZone::STOPPED.
Referenced by stop().
void vasum::ZoneAdmin::moveNetdev (const std::string & devId)
Move network device to zone
Definition at line 293 of file zone-admin.cpp.
References vasum::lxc::LxcZone::getInitPid(), vasum::netdev::movePhys(), and mZone.
void vasum::ZoneAdmin::resume ()
Resume the zone after suspension.
Definition at line 204 of file zone-admin.cpp.
References mId, mZone, and vasum::lxc::LxcZone::unfreeze().
void vasum::ZoneAdmin::setDestroyOnExit ()
Set if zone should be destroyed on exit.
Definition at line 265 of file zone-admin.cpp.
References mDestroyOnExit.
void vasum::ZoneAdmin::setDetachOnExit ()
Set whether zone should be detached on exit.
Definition at line 260 of file zone-admin.cpp.
References mDetachOnExit.
void vasum::ZoneAdmin::setNetdevAttrs (const std::string & netdev, const NetdevAttrs & attrs)
Set network device attributes
Definition at line 303 of file zone-admin.cpp.
References vasum::lxc::LxcZone::getInitPid(), mZone, and vasum::netdev::setAttrs().
void vasum::ZoneAdmin::setSchedulerLevel (SchedulerLevel sched)
Sets the zones scheduler CFS quota.
Definition at line 220 of file zone-admin.cpp.
References vasum::BACKGROUND, vasum::ZoneConfig::cpuQuotaBackground, vasum::ZoneConfig::cpuQuotaForeground, vasum::DEFAULT_CPU_SHARES, vasum::DEFAULT_VCPU_PERIOD_MS, vasum::FOREGROUND, isRunning(), mConfig, mId, and setSchedulerParams().
void vasum::ZoneAdmin::setSchedulerParams (std::uint64_t cpuShares, std::uint64_t vcpuPeriod, std::int64_t vcpuQuota) private
Definition at line 243 of file zone-admin.cpp.
References mId, and vasum::lxc::setCgroup().
Referenced by setSchedulerLevel().
void vasum::ZoneAdmin::start ()
Boot the zone to the background.
Definition at line 117 of file zone-admin.cpp.
References vasum::utils::CArrayBuilder< T >::add(), vasum::utils::CArrayBuilder< T >::c_array(), vasum::utils::CArrayBuilder< T >::empty(), vasum::ZoneConfig::initWithArgs, isRunning(), mConfig, mDynamicConfig, mId, mZone, vasum::lxc::LxcZone::start(), and vasum::ZoneDynamicConfig::vt.
void vasum::ZoneAdmin::stop ()
Try to shutdown the zone, if failed, kill it.
Definition at line 151 of file zone-admin.cpp.
References isStopped(), mConfig, mId, mZone, vasum::lxc::LxcZone::shutdown(), vasum::ZoneConfig::shutdownTimeout, and vasum::lxc::LxcZone::stop().
void vasum::ZoneAdmin::suspend ()
Suspends an active zone, the process is frozen without further access to CPU resources and I/O, but the memory used by the zone at the hypervisor level will stay allocated
Definition at line 194 of file zone-admin.cpp.
References vasum::lxc::LxcZone::freeze(), mId, and mZone.
Member Data Documentation
const ZoneConfig& vasum::ZoneAdmin::mConfig private
Definition at line 178 of file zone-admin.hpp.
Referenced by setSchedulerLevel(), start(), and stop().
bool vasum::ZoneAdmin::mDestroyOnExit private
Definition at line 183 of file zone-admin.hpp.
Referenced by setDestroyOnExit(), and ~ZoneAdmin().
bool vasum::ZoneAdmin::mDetachOnExit private
Definition at line 182 of file zone-admin.hpp.
Referenced by setDetachOnExit(), and ~ZoneAdmin().
const ZoneDynamicConfig& vasum::ZoneAdmin::mDynamicConfig private
Definition at line 179 of file zone-admin.hpp.
Referenced by start().
const std::string vasum::ZoneAdmin::mId private
Definition at line 181 of file zone-admin.hpp.
Referenced by destroy(), getId(), getSchedulerQuota(), resume(), setSchedulerLevel(), setSchedulerParams(), start(), stop(), suspend(), ZoneAdmin(), and ~ZoneAdmin().
lxc::LxcZone vasum::ZoneAdmin::mZone private
Definition at line 180 of file zone-admin.hpp.
Referenced by createNetdevMacvlan(), createNetdevVeth(), deleteNetdevIpAddress(), destroy(), destroyNetdev(), getNetdevAttrs(), getNetdevList(), isPaused(), isRunning(), isStopped(), moveNetdev(), resume(), setNetdevAttrs(), start(), stop(), suspend(), ZoneAdmin(), and ~ZoneAdmin().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/server/zone-admin.hpp
/home/dariusz/task/security-containers/server/zone-admin.cpp