Vasum: Client Class Reference
Client Class Reference
#include <vasum-client-impl.hpp>
Classes
struct Status
Public Member Functions
Client () noexcept
~Client () noexcept
VsmStatus connectSystem () noexcept
VsmStatus connect (const std::string &address) noexcept
VsmStatus disconnect () noexcept
VsmStatus vsm_get_poll_fd (int *fd) noexcept
VsmStatus vsm_enter_eventloop (int flags, int timeout) noexcept
VsmStatus vsm_set_dispatcher_type (VsmDispacherType dispacher) noexcept
VsmStatus vsm_get_dispatcher_type (VsmDispacherType *dispacher) noexcept
const char * vsm_get_status_message () const noexcept
VsmStatus vsm_get_status () const noexcept
VsmStatus vsm_get_zone_dbuses (VsmArrayString *keys, VsmArrayString *values) noexcept
VsmStatus vsm_lock_queue () noexcept
VsmStatus vsm_unlock_queue () noexcept
VsmStatus vsm_get_zone_ids (VsmArrayString *array) noexcept
VsmStatus vsm_get_active_zone_id (VsmString *id) noexcept
VsmStatus vsm_get_zone_rootpath (const char *id, VsmString *rootpath) noexcept
VsmStatus vsm_lookup_zone_by_pid (int pid, VsmString *id) noexcept
VsmStatus vsm_lookup_zone_by_id (const char *id, VsmZone *zone) noexcept
VsmStatus vsm_lookup_zone_by_terminal_id (int terminal, VsmString *id) noexcept
VsmStatus vsm_set_active_zone (const char *id) noexcept
VsmStatus vsm_create_zone (const char *id, const char *tname) noexcept
VsmStatus vsm_destroy_zone (const char *id) noexcept
VsmStatus vsm_shutdown_zone (const char *id) noexcept
VsmStatus vsm_start_zone (const char *id) noexcept
VsmStatus vsm_lock_zone (const char *id) noexcept
VsmStatus vsm_unlock_zone (const char *id) noexcept
VsmStatus vsm_add_state_callback (VsmZoneDbusStateFunction zoneDbusStateCallback, void *data, VsmSubscriptionId *subscriptionId) noexcept
VsmStatus vsm_del_state_callback (VsmSubscriptionId subscriptionId) noexcept
VsmStatus vsm_grant_device (const char *id, const char *device, uint32_t flags) noexcept
VsmStatus vsm_revoke_device (const char *id, const char *device) noexcept
VsmStatus vsm_zone_get_netdevs (const char *zone, VsmArrayString *netdevIds) noexcept
VsmStatus vsm_netdev_get_ipv4_addr (const char *zone, const char *netdevId, struct in_addr *addr) noexcept
VsmStatus vsm_netdev_get_ipv6_addr (const char *zone, const char *netdevId, struct in6_addr *addr) noexcept
VsmStatus vsm_netdev_set_ipv4_addr (const char *zone, const char *netdevId, struct in_addr *addr, int prefix) noexcept
VsmStatus vsm_netdev_set_ipv6_addr (const char *zone, const char *netdevId, struct in6_addr *addr, int prefix) noexcept
VsmStatus vsm_netdev_del_ipv4_addr (const char *zone, const char *netdevId, struct in_addr *addr, int prefix) noexcept
VsmStatus vsm_netdev_del_ipv6_addr (const char *zone, const char *netdevId, struct in6_addr *addr, int prefix) noexcept
VsmStatus vsm_netdev_up (const char *zone, const char *netdevId) noexcept
VsmStatus vsm_netdev_down (const char *zone, const char *netdevId) noexcept
VsmStatus vsm_create_netdev_veth (const char *zone, const char *zoneDev, const char *hostDev) noexcept
VsmStatus vsm_create_netdev_macvlan (const char *zone, const char *zoneDev, const char *hostDev, enum macvlan_mode mode) noexcept
VsmStatus vsm_create_netdev_phys (const char *zone, const char *devId) noexcept
VsmStatus vsm_lookup_netdev_by_name (const char *zone, const char *netdevId, VsmNetdev *netdev) noexcept
VsmStatus vsm_destroy_netdev (const char *zone, const char *devId) noexcept
VsmStatus vsm_declare_file (const char *zone, VsmFileType type, const char *path, int32_t flags, mode_t mode, VsmString *id) noexcept
VsmStatus vsm_declare_mount (const char *source, const char *zone, const char *target, const char *type, uint64_t flags, const char *data, VsmString *id) noexcept
VsmStatus vsm_declare_link (const char *source, const char *zone, const char *target, VsmString *id) noexcept
VsmStatus vsm_list_declarations (const char *zone, VsmArrayString *declarations) noexcept
VsmStatus vsm_remove_declaration (const char *zone, VsmString declaration) noexcept
Private Member Functions
bool isConnected () const
bool isInternalDispatcherEnabled () const
ipc::epoll::EventPoll & getEventPoll () const
VsmStatus coverException (const std::function< void(void)> &worker) noexcept
VsmStatus vsm_netdev_get_ip_addr (const char *zone, const char *netdevId, int type, void *addr) noexcept
Private Attributes
Status mStatus
std::mutex mStatusMutex
std::unique_ptr
< ipc::epoll::ThreadDispatcher > mInternalDispatcher
std::unique_ptr
< ipc::epoll::EventPoll > mEventPoll
std::unique_ptr< ipc::Client > mClient
Detailed Description
vasum's client definition.
Client uses dbus API.
Definition at line 53 of file vasum-client-impl.hpp.
Constructor & Destructor Documentation
Client::Client () noexcept
Definition at line 154 of file vasum-client-impl.cpp.
Client::~Client () noexcept
Definition at line 158 of file vasum-client-impl.cpp.
Member Function Documentation
VsmStatus Client::connect (const std::string & address) noexcept
Connect client.
Parameters
address ipc socket address
Returns
status of this function call
Definition at line 218 of file vasum-client-impl.cpp.
References coverException(), getEventPoll(), mClient, mEventPoll, mInternalDispatcher, vsm_set_dispatcher_type(), and VSMDISPATCHER_INTERNAL.
Referenced by connectSystem().
VsmStatus Client::connectSystem () noexcept
Connect client with system ipc address.
Returns
status of this function call
Definition at line 213 of file vasum-client-impl.cpp.
References connect().
VsmStatus Client::coverException (const std::function< void(void)> & worker) private noexcept
Definition at line 185 of file vasum-client-impl.cpp.
References mStatus, mStatusMutex, Client::Status::mVsmStatus, VSMCLIENT_CUSTOM_ERROR, VSMCLIENT_INVALID_ARGUMENT, VSMCLIENT_IO_ERROR, VSMCLIENT_OPERATION_FAILED, VSMCLIENT_OTHER_ERROR, and VSMCLIENT_SUCCESS.
Referenced by connect(), disconnect(), vsm_add_state_callback(), vsm_create_netdev_macvlan(), vsm_create_netdev_phys(), vsm_create_netdev_veth(), vsm_create_zone(), vsm_declare_file(), vsm_declare_link(), vsm_declare_mount(), vsm_del_state_callback(), vsm_destroy_netdev(), vsm_destroy_zone(), vsm_enter_eventloop(), vsm_get_active_zone_id(), vsm_get_dispatcher_type(), vsm_get_poll_fd(), vsm_get_zone_dbuses(), vsm_get_zone_ids(), vsm_get_zone_rootpath(), vsm_grant_device(), vsm_list_declarations(), vsm_lock_queue(), vsm_lock_zone(), vsm_lookup_netdev_by_name(), vsm_lookup_zone_by_id(), vsm_lookup_zone_by_pid(), vsm_lookup_zone_by_terminal_id(), vsm_netdev_del_ipv4_addr(), vsm_netdev_del_ipv6_addr(), vsm_netdev_down(), vsm_netdev_get_ip_addr(), vsm_netdev_set_ipv4_addr(), vsm_netdev_set_ipv6_addr(), vsm_netdev_up(), vsm_remove_declaration(), vsm_revoke_device(), vsm_set_active_zone(), vsm_set_dispatcher_type(), vsm_shutdown_zone(), vsm_start_zone(), vsm_unlock_queue(), vsm_unlock_zone(), and vsm_zone_get_netdevs().
VsmStatus Client::disconnect () noexcept
Disconnect client
Definition at line 229 of file vasum-client-impl.cpp.
References coverException(), and mClient.
ipc::epoll::EventPoll & Client::getEventPoll () const private
Definition at line 172 of file vasum-client-impl.cpp.
References isInternalDispatcherEnabled(), mEventPoll, and mInternalDispatcher.
Referenced by connect().
bool Client::isConnected () const private
Definition at line 162 of file vasum-client-impl.cpp.
References mClient.
Referenced by vsm_set_dispatcher_type().
bool Client::isInternalDispatcherEnabled () const private
Definition at line 167 of file vasum-client-impl.cpp.
References mInternalDispatcher.
Referenced by getEventPoll(), vsm_enter_eventloop(), vsm_get_dispatcher_type(), and vsm_get_poll_fd().
VsmStatus Client::vsm_add_state_callback (VsmZoneDbusStateFunction zoneDbusStateCallback, void * data, VsmSubscriptionId * subscriptionId) noexcept
See Also
vsm_add_state_callback
Definition at line 485 of file vasum-client-impl.cpp.
References coverException().
VsmStatus Client::vsm_create_netdev_macvlan (const char * zone, const char * zoneDev, const char * hostDev, enum macvlan_mode mode) noexcept
See Also
vsm_create_netdev_macvlan
Definition at line 713 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_CREATE_NETDEV_MACVLAN.
VsmStatus Client::vsm_create_netdev_phys (const char * zone, const char * devId) noexcept
See Also
vsm_create_netdev_phys
Definition at line 730 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_CREATE_NETDEV_PHYS.
VsmStatus Client::vsm_create_netdev_veth (const char * zone, const char * zoneDev, const char * hostDev) noexcept
See Also
vsm_create_netdev_veth
Definition at line 697 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_CREATE_NETDEV_VETH.
VsmStatus Client::vsm_create_zone (const char * id, const char * tname) noexcept
See Also
vsm_create_zone
Definition at line 418 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_CREATE_ZONE.
VsmStatus Client::vsm_declare_file (const char * zone, VsmFileType type, const char * path, int32_t flags, mode_t mode, VsmString * id) noexcept
See Also
vsm_declare_file
Definition at line 793 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, vasum::api::dbus::METHOD_DECLARE_FILE, and vasum::api::String::value.
VsmStatus Client::vsm_declare_link (const char * source, const char * zone, const char * target, VsmString * id) noexcept
See Also
vsm_declare_link
Definition at line 841 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, vasum::api::dbus::METHOD_DECLARE_LINK, and vasum::api::String::value.
VsmStatus Client::vsm_declare_mount (const char * source, const char * zone, const char * target, const char * type, uint64_t flags, const char * data, VsmString * id) noexcept
See Also
vsm_declare_mount
Definition at line 814 of file vasum-client-impl.cpp.
References coverException(), data, IS_SET, mClient, vasum::api::dbus::METHOD_DECLARE_MOUNT, and vasum::api::String::value.
VsmStatus Client::vsm_del_state_callback (VsmSubscriptionId subscriptionId) noexcept
See Also
vsm_del_state_callback
Definition at line 495 of file vasum-client-impl.cpp.
References coverException(), and mClient.
VsmStatus Client::vsm_destroy_netdev (const char * zone, const char * devId) noexcept
See Also
vsm_destroy_netdev
Definition at line 781 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_DESTROY_NETDEV.
VsmStatus Client::vsm_destroy_zone (const char * id) noexcept
See Also
vsm_destroy_zone
Definition at line 431 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_DESTROY_ZONE.
VsmStatus Client::vsm_enter_eventloop (int flags, int timeout) noexcept
See Also
vsm_enter_eventloop
Definition at line 247 of file vasum-client-impl.cpp.
References coverException(), isInternalDispatcherEnabled(), and mEventPoll.
VsmStatus Client::vsm_get_active_zone_id (VsmString * id) noexcept
See Also
vsm_get_active_zone_id
Definition at line 340 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, vasum::api::dbus::METHOD_GET_ACTIVE_ZONE_ID, and vasum::api::String::value.
VsmStatus Client::vsm_get_dispatcher_type (VsmDispacherType * dispacher) noexcept
See Also
vsm_get_dispatcher_type
Definition at line 278 of file vasum-client-impl.cpp.
References coverException(), IS_SET, isInternalDispatcherEnabled(), VSMDISPATCHER_EXTERNAL, and VSMDISPATCHER_INTERNAL.
VsmStatus Client::vsm_get_poll_fd (int * fd) noexcept
See Also
vsm_get_poll_fd
Definition at line 236 of file vasum-client-impl.cpp.
References coverException(), IS_SET, isInternalDispatcherEnabled(), and mEventPoll.
VsmStatus Client::vsm_get_status () const noexcept
See Also
vsm_get_status
Definition at line 296 of file vasum-client-impl.cpp.
References mStatus, mStatusMutex, and Client::Status::mVsmStatus.
const char * Client::vsm_get_status_message () const noexcept
See Also
vsm_get_status_message
Definition at line 291 of file vasum-client-impl.cpp.
References Client::Status::mMsg, and mStatus.
VsmStatus Client::vsm_get_zone_dbuses (VsmArrayString * keys, VsmArrayString * values) noexcept
See Also
vsm_get_zone_dbuses
Definition at line 302 of file vasum-client-impl.cpp.
References coverException().
VsmStatus Client::vsm_get_zone_ids (VsmArrayString * array) noexcept
See Also
vsm_get_zone_ids
Definition at line 328 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::ipc::METHOD_GET_ZONE_ID_LIST.
VsmStatus Client::vsm_get_zone_rootpath (const char * id, VsmString * rootpath) noexcept
See Also
vsm_get_zone_rootpath
Definition at line 352 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, vasum::api::dbus::METHOD_GET_ZONE_INFO, and vasum::api::ZoneInfoOut::rootPath.
VsmStatus Client::vsm_grant_device (const char * id, const char * device, uint32_t flags) noexcept
See Also
vsm_del_state_callback
Definition at line 502 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_GRANT_DEVICE.
VsmStatus Client::vsm_list_declarations (const char * zone, VsmArrayString * declarations) noexcept
See Also
vsm_list_declarations
Definition at line 860 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_GET_DECLARATIONS.
VsmStatus Client::vsm_lock_queue () noexcept
See Also
vsm_lock_queue
Definition at line 310 of file vasum-client-impl.cpp.
References coverException(), mClient, and vasum::api::ipc::METHOD_LOCK_QUEUE.
VsmStatus Client::vsm_lock_zone (const char * id) noexcept
See Also
vsm_lock_zone
Definition at line 464 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_LOCK_ZONE.
VsmStatus Client::vsm_lookup_netdev_by_name (const char * zone, const char * netdevId, VsmNetdev * netdev) noexcept
See Also
vsm_lookup_netdev_by_name
Definition at line 743 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, vasum::api::dbus::METHOD_GET_NETDEV_ATTRS, VsmNetdevStructure::name, vasum::api::VectorOfStringPairs::values, VSMNETDEV_MACVLAN, and VSMNETDEV_VETH.
VsmStatus Client::vsm_lookup_zone_by_id (const char * id, VsmZone * zone) noexcept
See Also
vsm_lookup_zone_by_id
Definition at line 386 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_GET_ZONE_INFO.
VsmStatus Client::vsm_lookup_zone_by_pid (int pid, VsmString * id) noexcept
See Also
vsm_lookup_zone_by_pid
Definition at line 365 of file vasum-client-impl.cpp.
References coverException(), IS_SET, parseZoneIdFromCpuSet(), and utils::readFirstLineOfFile().
VsmStatus Client::vsm_lookup_zone_by_terminal_id (int terminal, VsmString * id) noexcept
See Also
vsm_lookup_zone_by_terminal_id
Definition at line 399 of file vasum-client-impl.cpp.
References coverException().
VsmStatus Client::vsm_netdev_del_ipv4_addr (const char * zone, const char * netdevId, struct in_addr * addr, int prefix) noexcept
See Also
vsm_netdev_del_ipv4_addr
Definition at line 630 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_DELETE_NETDEV_IP_ADDRESS.
VsmStatus Client::vsm_netdev_del_ipv6_addr (const char * zone, const char * netdevId, struct in6_addr * addr, int prefix) noexcept
See Also
vsm_netdev_del_ipv6_addr
Definition at line 649 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_DELETE_NETDEV_IP_ADDRESS.
VsmStatus Client::vsm_netdev_down (const char * zone, const char * netdevId) noexcept
See Also
vsm_netdev_down
Definition at line 683 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_SET_NETDEV_ATTRS.
VsmStatus Client::vsm_netdev_get_ip_addr (const char * zone, const char * netdevId, int type, void * addr) private noexcept
Definition at line 539 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, vasum::api::dbus::METHOD_GET_NETDEV_ATTRS, and vasum::api::VectorOfStringPairs::values.
Referenced by vsm_netdev_get_ipv4_addr(), and vsm_netdev_get_ipv6_addr().
VsmStatus Client::vsm_netdev_get_ipv4_addr (const char * zone, const char * netdevId, struct in_addr * addr) noexcept
See Also
vsm_netdev_get_ipv4_addr
Definition at line 580 of file vasum-client-impl.cpp.
References vsm_netdev_get_ip_addr().
VsmStatus Client::vsm_netdev_get_ipv6_addr (const char * zone, const char * netdevId, struct in6_addr * addr) noexcept
See Also
vsm_netdev_get_ipv6_addr
Definition at line 587 of file vasum-client-impl.cpp.
References vsm_netdev_get_ip_addr().
VsmStatus Client::vsm_netdev_set_ipv4_addr (const char * zone, const char * netdevId, struct in_addr * addr, int prefix) noexcept
See Also
vsm_netdev_set_ipv4_addr
Definition at line 594 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_SET_NETDEV_ATTRS.
VsmStatus Client::vsm_netdev_set_ipv6_addr (const char * zone, const char * netdevId, struct in6_addr * addr, int prefix) noexcept
See Also
vsm_netdev_set_ipv6_addr
Definition at line 612 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_SET_NETDEV_ATTRS.
VsmStatus Client::vsm_netdev_up (const char * zone, const char * netdevId) noexcept
See Also
vsm_netdev_up
Definition at line 669 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_SET_NETDEV_ATTRS.
VsmStatus Client::vsm_remove_declaration (const char * zone, VsmString declaration) noexcept
See Also
vsm_remove_declaration
Definition at line 873 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_REMOVE_DECLARATION.
VsmStatus Client::vsm_revoke_device (const char * id, const char * device) noexcept
See Also
vsm_revoke_device
Definition at line 514 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_REVOKE_DEVICE.
VsmStatus Client::vsm_set_active_zone (const char * id) noexcept
See Also
vsm_set_active_zone
Definition at line 407 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_SET_ACTIVE_ZONE.
VsmStatus Client::vsm_set_dispatcher_type (VsmDispacherType dispacher) noexcept
See Also
vsm_set_dispatcher_type
Definition at line 257 of file vasum-client-impl.cpp.
References coverException(), isConnected(), mEventPoll, mInternalDispatcher, VSMDISPATCHER_EXTERNAL, and VSMDISPATCHER_INTERNAL.
Referenced by connect().
VsmStatus Client::vsm_shutdown_zone (const char * id) noexcept
See Also
vsm_shutdown_zone
Definition at line 442 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_SHUTDOWN_ZONE.
VsmStatus Client::vsm_start_zone (const char * id) noexcept
See Also
vsm_start_zone
Definition at line 453 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_START_ZONE.
VsmStatus Client::vsm_unlock_queue () noexcept
See Also
vsm_unlock_queue
Definition at line 319 of file vasum-client-impl.cpp.
References coverException(), mClient, and vasum::api::ipc::METHOD_UNLOCK_QUEUE.
VsmStatus Client::vsm_unlock_zone (const char * id) noexcept
See Also
vsm_unlock_zone
Definition at line 475 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_UNLOCK_ZONE.
VsmStatus Client::vsm_zone_get_netdevs (const char * zone, VsmArrayString * netdevIds) noexcept
See Also
vsm_zone_get_netdevs
Definition at line 526 of file vasum-client-impl.cpp.
References coverException(), IS_SET, mClient, and vasum::api::dbus::METHOD_GET_NETDEV_LIST.
Member Data Documentation
std::unique_ptr<ipc::Client> Client::mClient private
Definition at line 355 of file vasum-client-impl.hpp.
Referenced by connect(), disconnect(), isConnected(), vsm_create_netdev_macvlan(), vsm_create_netdev_phys(), vsm_create_netdev_veth(), vsm_create_zone(), vsm_declare_file(), vsm_declare_link(), vsm_declare_mount(), vsm_del_state_callback(), vsm_destroy_netdev(), vsm_destroy_zone(), vsm_get_active_zone_id(), vsm_get_zone_ids(), vsm_get_zone_rootpath(), vsm_grant_device(), vsm_list_declarations(), vsm_lock_queue(), vsm_lock_zone(), vsm_lookup_netdev_by_name(), vsm_lookup_zone_by_id(), vsm_netdev_del_ipv4_addr(), vsm_netdev_del_ipv6_addr(), vsm_netdev_down(), vsm_netdev_get_ip_addr(), vsm_netdev_set_ipv4_addr(), vsm_netdev_set_ipv6_addr(), vsm_netdev_up(), vsm_remove_declaration(), vsm_revoke_device(), vsm_set_active_zone(), vsm_shutdown_zone(), vsm_start_zone(), vsm_unlock_queue(), vsm_unlock_zone(), and vsm_zone_get_netdevs().
std::unique_ptr<ipc::epoll::EventPoll> Client::mEventPoll private
Definition at line 354 of file vasum-client-impl.hpp.
Referenced by connect(), getEventPoll(), vsm_enter_eventloop(), vsm_get_poll_fd(), and vsm_set_dispatcher_type().
std::unique_ptr<ipc::epoll::ThreadDispatcher> Client::mInternalDispatcher private
Definition at line 353 of file vasum-client-impl.hpp.
Referenced by connect(), getEventPoll(), isInternalDispatcherEnabled(), and vsm_set_dispatcher_type().
Status Client::mStatus private
Definition at line 350 of file vasum-client-impl.hpp.
Referenced by coverException(), vsm_get_status(), and vsm_get_status_message().
std::mutex Client::mStatusMutex mutable private
Definition at line 352 of file vasum-client-impl.hpp.
Referenced by coverException(), and vsm_get_status().
The documentation for this class was generated from the following files:
/home/lkostyra/eclipse_workspaces/code/vasum/client/vasum-client-impl.hpp
/home/lkostyra/eclipse_workspaces/code/vasum/client/vasum-client-impl.cpp