Vasum: utils::CountingMap< Key > Class Template Reference
utils::CountingMap< Key > Class Template Reference
#include <counting-map.hpp>
Public Member Functions
size_t increment (const Key &key)
size_t decrement (const Key &key)
void clear ()
size_t get (const Key &key) const
bool empty () const
Private Types
typedef std::unordered_map
< Key, size_t > Map
Private Attributes
Map mMap
Detailed Description
template<class Key>
class utils::CountingMap< Key >
Structure used to count elements. It's like multiset + count but is more efficient.
Definition at line 38 of file counting-map.hpp.
Member Typedef Documentation
template<class Key> typedef std::unordered_map<Key, size_t> utils::CountingMap< Key >::Map private
Definition at line 78 of file counting-map.hpp.
Member Function Documentation
template<class Key> void utils::CountingMap< Key >::clear () inline
Definition at line 62 of file counting-map.hpp.
template<class Key> size_t utils::CountingMap< Key >::decrement (const Key & key) inline
Definition at line 49 of file counting-map.hpp.
Referenced by utils::Worker::WorkerQueue::workerProc().
template<class Key> bool utils::CountingMap< Key >::empty () const inline
Definition at line 73 of file counting-map.hpp.
Referenced by utils::Worker::WorkerQueue::~WorkerQueue().
template<class Key> size_t utils::CountingMap< Key >::get (const Key & key) const inline
Definition at line 67 of file counting-map.hpp.
Referenced by utils::Worker::WorkerQueue::waitForGroupEmpty().
template<class Key> size_t utils::CountingMap< Key >::increment (const Key & key) inline
Definition at line 40 of file counting-map.hpp.
Referenced by utils::Worker::WorkerQueue::addTask().
Member Data Documentation
template<class Key> Map utils::CountingMap< Key >::mMap private
Definition at line 79 of file counting-map.hpp.
Referenced by utils::CountingMap< GroupID >::clear(), utils::CountingMap< GroupID >::decrement(), utils::CountingMap< GroupID >::empty(), utils::CountingMap< GroupID >::get(), and utils::CountingMap< GroupID >::increment().
The documentation for this class was generated from the following file:
/home/lkostyra/eclipse_workspaces/code/vasum/common/utils/counting-map.hpp