Vasum: vasum::utils::Latch Class Reference
vasum::utils::Latch Class Reference
#include <latch.hpp>
Public Member Functions
Latch ()
void set ()
void wait ()
bool wait (const unsigned int timeoutMs)
void waitForN (const unsigned int n)
bool waitForN (const unsigned int n, const unsigned int timeoutMs)
bool empty ()
Private Attributes
std::mutex mMutex
std::condition_variable mCondition
unsigned int mCount
Detailed Description
A synchronization aid that allows one thread to wait until an operation being performed in other thread completes. It has a similar function as std::promise<void> but allows multiple calls to set.
Definition at line 42 of file latch.hpp.
Constructor & Destructor Documentation
vasum::utils::Latch::Latch ()
Definition at line 35 of file latch.cpp.
Member Function Documentation
bool vasum::utils::Latch::empty ()
Check if there are no pending events.
Definition at line 76 of file latch.cpp.
void vasum::utils::Latch::set ()
Sets an event occurred.
Definition at line 40 of file latch.cpp.
References mCondition, mCount, and mMutex.
Referenced by vasum::Server::terminate().
void vasum::utils::Latch::wait ()
Waits for a single occurrence of event.
Definition at line 47 of file latch.cpp.
References waitForN().
Referenced by vasum::Server::run().
bool vasum::utils::Latch::wait (const unsigned int timeoutMs)
Waits for a single occurrence of event with timeout.
Parameters
timeoutMs timeout in ms to wait for
Returns
false on timeout
Definition at line 52 of file latch.cpp.
References waitForN().
void vasum::utils::Latch::waitForN (const unsigned int n)
Waits for n occurrences of event.
Parameters
n number of occurrences to wait for
Definition at line 57 of file latch.cpp.
References mCondition, mCount, and mMutex.
Referenced by wait().
bool vasum::utils::Latch::waitForN (const unsigned int n, const unsigned int timeoutMs)
Waits for n occurrences of event with timeout.
Parameters
n number of occurrences to wait for
timeoutMs timeout in ms to wait for
Returns
false on timeout
Definition at line 64 of file latch.cpp.
References mCondition, mCount, and mMutex.
Member Data Documentation
std::condition_variable vasum::utils::Latch::mCondition private
Definition at line 86 of file latch.hpp.
Referenced by set(), and waitForN().
unsigned int vasum::utils::Latch::mCount private
Definition at line 87 of file latch.hpp.
Referenced by set(), and waitForN().
std::mutex vasum::utils::Latch::mMutex private
Definition at line 85 of file latch.hpp.
Referenced by set(), and waitForN().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/common/utils/latch.hpp
/home/dariusz/task/security-containers/common/utils/latch.cpp