Vasum: vasum::epoll::ThreadDispatcher Class Reference
vasum::epoll::ThreadDispatcher Class Reference
#include <thread-dispatcher.hpp>
Public Member Functions
ThreadDispatcher ()
~ThreadDispatcher ()
EventPoll & getPoll ()
Private Attributes
EventPoll mPoll
utils::EventFD mStopEvent
std::atomic_bool mStopped
std::thread mThread
Detailed Description
Will dispatch poll events in a newly created thread
Definition at line 40 of file thread-dispatcher.hpp.
Constructor & Destructor Documentation
vasum::epoll::ThreadDispatcher::ThreadDispatcher ()
Definition at line 31 of file thread-dispatcher.cpp.
References vasum::epoll::EventPoll::addFD(), vasum::epoll::EventPoll::dispatchIteration(), vasum::utils::EventFD::getFD(), mPoll, mStopEvent, mStopped, mThread, and vasum::utils::EventFD::receive().
vasum::epoll::ThreadDispatcher::~ThreadDispatcher ()
Definition at line 47 of file thread-dispatcher.cpp.
References vasum::utils::EventFD::getFD(), mPoll, mStopEvent, mThread, vasum::epoll::EventPoll::removeFD(), and vasum::utils::EventFD::send().
Member Function Documentation
EventPoll & vasum::epoll::ThreadDispatcher::getPoll ()
Definition at line 54 of file thread-dispatcher.cpp.
References mPoll.
Member Data Documentation
EventPoll vasum::epoll::ThreadDispatcher::mPoll private
Definition at line 47 of file thread-dispatcher.hpp.
Referenced by getPoll(), ThreadDispatcher(), and ~ThreadDispatcher().
utils::EventFD vasum::epoll::ThreadDispatcher::mStopEvent private
Definition at line 48 of file thread-dispatcher.hpp.
Referenced by ThreadDispatcher(), and ~ThreadDispatcher().
std::atomic_bool vasum::epoll::ThreadDispatcher::mStopped private
Definition at line 49 of file thread-dispatcher.hpp.
Referenced by ThreadDispatcher().
std::thread vasum::epoll::ThreadDispatcher::mThread private
Definition at line 50 of file thread-dispatcher.hpp.
Referenced by ThreadDispatcher(), and ~ThreadDispatcher().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/common/epoll/thread-dispatcher.hpp
/home/dariusz/task/security-containers/common/epoll/thread-dispatcher.cpp