Vasum: vasum::HostConnection Class Reference
vasum::HostConnection Class Reference
#include <host-connection.hpp>
Public Types
typedef std::function< void(const
std::string &target, const
std::string &targetBusName,
const std::string
&targetObjectPath, const
std::string &targetInterface,
const std::string
&targetMethod, GVariant
*parameters,
dbus::MethodResultBuilder::Pointer
result)> ProxyCallCallback
typedef std::function< void(api::MethodResultBuilder::Pointer
result)> GetZoneDbusesCallback
typedef std::function< void(api::MethodResultBuilder::Pointer
result)> GetZoneIdsCallback
typedef std::function< void(api::MethodResultBuilder::Pointer
result)> GetActiveZoneIdCallback
typedef std::function< void(const
api::ZoneId &dataIn,
api::MethodResultBuilder::Pointer
result)> GetZoneInfoCallback
typedef std::function< void(const
api::SetNetDevAttrsIn &dataIn,
api::MethodResultBuilder::Pointer
result)> SetNetdevAttrsCallback
typedef std::function< void(const
api::GetNetDevAttrsIn &dataIn,
api::MethodResultBuilder::Pointer
result)> GetNetdevAttrsCallback
typedef std::function< void(const
api::ZoneId &dataIn,
api::MethodResultBuilder::Pointer
result)> GetNetdevListCallback
typedef std::function< void(const
api::CreateNetDevVethIn
&dataIn,
api::MethodResultBuilder::Pointer
result)> CreateNetdevVethCallback
typedef std::function< void(const
api::CreateNetDevMacvlanIn
&dataIn,
api::MethodResultBuilder::Pointer
result)> CreateNetdevMacvlanCallback
typedef std::function< void(const
api::CreateNetDevPhysIn
&dataIn,
api::MethodResultBuilder::Pointer
result)> CreateNetdevPhysCallback
typedef std::function< void(const
api::DeleteNetdevIpAddressIn
&dataIn,
api::MethodResultBuilder::Pointer
result)> DeleteNetdevIpAddressCallback
typedef std::function< void(const
api::DestroyNetDevIn &dataIn,
api::MethodResultBuilder::Pointer
result)> DestroyNetdevCallback
typedef std::function< void(const
api::DeclareFileIn &dataIn,
api::MethodResultBuilder::Pointer
result)> DeclareFileCallback
typedef std::function< void(const
api::DeclareMountIn &dataIn,
api::MethodResultBuilder::Pointer
result)> DeclareMountCallback
typedef std::function< void(const
api::DeclareLinkIn &dataIn,
api::MethodResultBuilder::Pointer
result)> DeclareLinkCallback
typedef std::function< void(const
api::ZoneId &dataIn,
api::MethodResultBuilder::Pointer
result)> GetDeclarationsCallback
typedef std::function< void(const
api::RemoveDeclarationIn
&dataIn,
api::MethodResultBuilder::Pointer
result)> RemoveDeclarationCallback
typedef std::function< void(const
api::ZoneId &dataIn,
api::MethodResultBuilder::Pointer
result)> SetActiveZoneCallback
typedef std::function< void(const
api::CreateZoneIn &dataIn,
api::MethodResultBuilder::Pointer
result)> CreateZoneCallback
typedef std::function< void(const
api::ZoneId &dataIn,
api::MethodResultBuilder::Pointer
result)> DestroyZoneCallback
typedef std::function< void(const
api::ZoneId &dataIn,
api::MethodResultBuilder::Pointer
result)> ShutdownZoneCallback
typedef std::function< void(const
api::ZoneId &dataIn,
api::MethodResultBuilder::Pointer
result)> StartZoneCallback
typedef std::function< void(const
api::ZoneId &dataIn,
api::MethodResultBuilder::Pointer
result)> LockZoneCallback
typedef std::function< void(const
api::ZoneId &dataIn,
api::MethodResultBuilder::Pointer
result)> UnlockZoneCallback
typedef std::function< void(const
api::GrantDeviceIn &dataIn,
api::MethodResultBuilder::Pointer
result)> GrantDeviceCallback
typedef std::function< void(const
api::RevokeDeviceIn &dataIn,
api::MethodResultBuilder::Pointer
result)> RevokeDeviceCallback
Public Member Functions
HostConnection ()
~HostConnection ()
void setProxyCallCallback (const ProxyCallCallback &callback)
void setGetZoneDbusesCallback (const GetZoneDbusesCallback &callback)
void signalZoneDbusState (const std::string &zoneId, const std::string &dbusAddress)
void setGetZoneIdsCallback (const GetZoneIdsCallback &callback)
void setGetActiveZoneIdCallback (const GetActiveZoneIdCallback &callback)
void setGetZoneInfoCallback (const GetZoneInfoCallback &callback)
void setSetNetdevAttrsCallback (const SetNetdevAttrsCallback &callback)
void setGetNetdevAttrsCallback (const GetNetdevAttrsCallback &callback)
void setGetNetdevListCallback (const GetNetdevListCallback &callback)
void setCreateNetdevVethCallback (const CreateNetdevVethCallback &callback)
void setCreateNetdevMacvlanCallback (const CreateNetdevMacvlanCallback &callback)
void setCreateNetdevPhysCallback (const CreateNetdevPhysCallback &callback)
void setDestroyNetdevCallback (const DestroyNetdevCallback &callback)
void setDeleleNetdevIpAddressCallback (const DeleteNetdevIpAddressCallback &callback)
void setDeclareFileCallback (const DeclareFileCallback &callback)
void setDeclareMountCallback (const DeclareMountCallback &callback)
void setDeclareLinkCallback (const DeclareLinkCallback &callback)
void setGetDeclarationsCallback (const GetDeclarationsCallback &callback)
void setRemoveDeclarationCallback (const RemoveDeclarationCallback &callback)
void setSetActiveZoneCallback (const SetActiveZoneCallback &callback)
void setCreateZoneCallback (const CreateZoneCallback &callback)
void setDestroyZoneCallback (const DestroyZoneCallback &callback)
void setShutdownZoneCallback (const ShutdownZoneCallback &callback)
void setStartZoneCallback (const StartZoneCallback &callback)
void setLockZoneCallback (const LockZoneCallback &callback)
void setUnlockZoneCallback (const UnlockZoneCallback &callback)
void setGrantDeviceCallback (const GrantDeviceCallback &callback)
void setRevokeDeviceCallback (const RevokeDeviceCallback &callback)
void proxyCallAsync (const std::string &busName, const std::string &objectPath, const std::string &interface, const std::string &method, GVariant *parameters, const dbus::DbusConnection::AsyncMethodCallCallback &callback)
Private Member Functions
void onNameAcquired ()
void onNameLost ()
bool waitForName (const unsigned int timeoutMs)
void onMessageCall (const std::string &objectPath, const std::string &interface, const std::string &methodName, GVariant *parameters, dbus::MethodResultBuilder::Pointer result)
Private Attributes
dbus::DbusConnection::Pointer mDbusConnection
std::mutex mNameMutex
std::condition_variable mNameCondition
bool mNameAcquired
bool mNameLost
ProxyCallCallback mProxyCallCallback
GetZoneDbusesCallback mGetZoneDbusesCallback
GetZoneIdsCallback mGetZoneIdsCallback
GetActiveZoneIdCallback mGetActiveZoneIdCallback
GetZoneInfoCallback mGetZoneInfoCallback
SetNetdevAttrsCallback mSetNetdevAttrsCallback
GetNetdevAttrsCallback mGetNetdevAttrsCallback
GetNetdevListCallback mGetNetdevListCallback
CreateNetdevVethCallback mCreateNetdevVethCallback
CreateNetdevMacvlanCallback mCreateNetdevMacvlanCallback
CreateNetdevPhysCallback mCreateNetdevPhysCallback
DestroyNetdevCallback mDestroyNetdevCallback
DeleteNetdevIpAddressCallback mDeleteNetdevIpAddressCallback
DeclareFileCallback mDeclareFileCallback
DeclareMountCallback mDeclareMountCallback
DeclareLinkCallback mDeclareLinkCallback
GetDeclarationsCallback mGetDeclarationsCallback
RemoveDeclarationCallback mRemoveDeclarationCallback
SetActiveZoneCallback mSetActiveZoneCallback
CreateZoneCallback mCreateZoneCallback
DestroyZoneCallback mDestroyZoneCallback
ShutdownZoneCallback mShutdownZoneCallback
StartZoneCallback mStartZoneCallback
LockZoneCallback mLockZoneCallback
UnlockZoneCallback mUnlockZoneCallback
GrantDeviceCallback mGrantDeviceCallback
RevokeDeviceCallback mRevokeDeviceCallback
Detailed Description
Definition at line 42 of file host-connection.hpp.
Member Typedef Documentation
typedef std::function<void(const api::CreateNetDevMacvlanIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::CreateNetdevMacvlanCallback
Definition at line 81 of file host-connection.hpp.
typedef std::function<void(const api::CreateNetDevPhysIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::CreateNetdevPhysCallback
Definition at line 84 of file host-connection.hpp.
typedef std::function<void(const api::CreateNetDevVethIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::CreateNetdevVethCallback
Definition at line 78 of file host-connection.hpp.
typedef std::function<void(const api::CreateZoneIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::CreateZoneCallback
Definition at line 111 of file host-connection.hpp.
typedef std::function<void(const api::DeclareFileIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::DeclareFileCallback
Definition at line 93 of file host-connection.hpp.
typedef std::function<void(const api::DeclareLinkIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::DeclareLinkCallback
Definition at line 99 of file host-connection.hpp.
typedef std::function<void(const api::DeclareMountIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::DeclareMountCallback
Definition at line 96 of file host-connection.hpp.
typedef std::function<void(const api::DeleteNetdevIpAddressIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::DeleteNetdevIpAddressCallback
Definition at line 87 of file host-connection.hpp.
typedef std::function<void(const api::DestroyNetDevIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::DestroyNetdevCallback
Definition at line 90 of file host-connection.hpp.
typedef std::function<void(const api::ZoneId& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::DestroyZoneCallback
Definition at line 114 of file host-connection.hpp.
typedef std::function<void(api::MethodResultBuilder::Pointer result)> vasum::HostConnection::GetActiveZoneIdCallback
Definition at line 63 of file host-connection.hpp.
typedef std::function<void(const api::ZoneId& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::GetDeclarationsCallback
Definition at line 102 of file host-connection.hpp.
typedef std::function<void(const api::GetNetDevAttrsIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::GetNetdevAttrsCallback
Definition at line 72 of file host-connection.hpp.
typedef std::function<void(const api::ZoneId& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::GetNetdevListCallback
Definition at line 75 of file host-connection.hpp.
typedef std::function<void(api::MethodResultBuilder::Pointer result)> vasum::HostConnection::GetZoneDbusesCallback
Definition at line 59 of file host-connection.hpp.
typedef std::function<void(api::MethodResultBuilder::Pointer result)> vasum::HostConnection::GetZoneIdsCallback
Definition at line 61 of file host-connection.hpp.
typedef std::function<void(const api::ZoneId& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::GetZoneInfoCallback
Definition at line 66 of file host-connection.hpp.
typedef std::function<void(const api::GrantDeviceIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::GrantDeviceCallback
Definition at line 129 of file host-connection.hpp.
typedef std::function<void(const api::ZoneId& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::LockZoneCallback
Definition at line 123 of file host-connection.hpp.
typedef std::function<void(const std::string& target, const std::string& targetBusName, const std::string& targetObjectPath, const std::string& targetInterface, const std::string& targetMethod, GVariant* parameters, dbus::MethodResultBuilder::Pointer result)> vasum::HostConnection::ProxyCallCallback
Definition at line 57 of file host-connection.hpp.
typedef std::function<void(const api::RemoveDeclarationIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::RemoveDeclarationCallback
Definition at line 105 of file host-connection.hpp.
typedef std::function<void(const api::RevokeDeviceIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::RevokeDeviceCallback
Definition at line 132 of file host-connection.hpp.
typedef std::function<void(const api::ZoneId& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::SetActiveZoneCallback
Definition at line 108 of file host-connection.hpp.
typedef std::function<void(const api::SetNetDevAttrsIn& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::SetNetdevAttrsCallback
Definition at line 69 of file host-connection.hpp.
typedef std::function<void(const api::ZoneId& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::ShutdownZoneCallback
Definition at line 117 of file host-connection.hpp.
typedef std::function<void(const api::ZoneId& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::StartZoneCallback
Definition at line 120 of file host-connection.hpp.
typedef std::function<void(const api::ZoneId& dataIn, api::MethodResultBuilder::Pointer result)> vasum::HostConnection::UnlockZoneCallback
Definition at line 126 of file host-connection.hpp.
Constructor & Destructor Documentation
vasum::HostConnection::HostConnection ()
Definition at line 48 of file host-connection.cpp.
References vasum::api::host::BUS_NAME, vasum::api::host::DEFINITION, mDbusConnection, vasum::api::host::OBJECT_PATH, onMessageCall(), onNameAcquired(), onNameLost(), and waitForName().
vasum::HostConnection::~HostConnection ()
Definition at line 75 of file host-connection.cpp.
Member Function Documentation
void vasum::HostConnection::onMessageCall (const std::string & objectPath, const std::string & interface, const std::string & methodName, GVariant * parameters, dbus::MethodResultBuilder::Pointer result) private
Definition at line 246 of file host-connection.cpp.
References data, vasum::api::host::INTERFACE, mCreateNetdevMacvlanCallback, mCreateNetdevPhysCallback, mCreateNetdevVethCallback, mCreateZoneCallback, mDeclareFileCallback, mDeclareLinkCallback, mDeclareMountCallback, mDeleteNetdevIpAddressCallback, mDestroyNetdevCallback, mDestroyZoneCallback, vasum::api::host::METHOD_CREATE_NETDEV_MACVLAN, vasum::api::host::METHOD_CREATE_NETDEV_PHYS, vasum::api::host::METHOD_CREATE_NETDEV_VETH, vasum::api::host::METHOD_CREATE_ZONE, vasum::api::host::METHOD_DECLARE_FILE, vasum::api::host::METHOD_DECLARE_LINK, vasum::api::host::METHOD_DECLARE_MOUNT, vasum::api::host::METHOD_DELETE_NETDEV_IP_ADDRESS, vasum::api::host::METHOD_DESTROY_NETDEV, vasum::api::host::METHOD_DESTROY_ZONE, vasum::api::host::METHOD_GET_ACTIVE_ZONE_ID, vasum::api::host::METHOD_GET_DECLARATIONS, vasum::api::host::METHOD_GET_NETDEV_ATTRS, vasum::api::host::METHOD_GET_NETDEV_LIST, vasum::api::host::METHOD_GET_ZONE_DBUSES, vasum::api::host::METHOD_GET_ZONE_ID_LIST, vasum::api::host::METHOD_GET_ZONE_INFO, vasum::api::host::METHOD_GRANT_DEVICE, vasum::api::host::METHOD_LOCK_ZONE, vasum::api::METHOD_PROXY_CALL, vasum::api::host::METHOD_REMOVE_DECLARATION, vasum::api::host::METHOD_REVOKE_DEVICE, vasum::api::host::METHOD_SET_ACTIVE_ZONE, vasum::api::host::METHOD_SET_NETDEV_ATTRS, vasum::api::host::METHOD_SHUTDOWN_ZONE, vasum::api::host::METHOD_START_ZONE, vasum::api::host::METHOD_UNLOCK_ZONE, mGetActiveZoneIdCallback, mGetDeclarationsCallback, mGetNetdevAttrsCallback, mGetNetdevListCallback, mGetZoneDbusesCallback, mGetZoneIdsCallback, mGetZoneInfoCallback, mGrantDeviceCallback, mLockZoneCallback, mProxyCallCallback, mRemoveDeclarationCallback, mRevokeDeviceCallback, mSetActiveZoneCallback, mSetNetdevAttrsCallback, mShutdownZoneCallback, mStartZoneCallback, mUnlockZoneCallback, and vasum::api::host::OBJECT_PATH.
Referenced by HostConnection().
void vasum::HostConnection::onNameAcquired () private
Definition at line 91 of file host-connection.cpp.
References mNameAcquired, mNameCondition, and mNameMutex.
Referenced by HostConnection().
void vasum::HostConnection::onNameLost () private
Definition at line 98 of file host-connection.cpp.
References mNameAcquired, mNameCondition, mNameLost, and mNameMutex.
Referenced by HostConnection().
void vasum::HostConnection::proxyCallAsync (const std::string & busName, const std::string & objectPath, const std::string & interface, const std::string & method, GVariant * parameters, const dbus::DbusConnection::AsyncMethodCallCallback & callback)
Make a proxy call
Definition at line 556 of file host-connection.cpp.
References mDbusConnection.
Referenced by vasum::ZonesManager::handleProxyCall().
void vasum::HostConnection::setCreateNetdevMacvlanCallback (const CreateNetdevMacvlanCallback & callback)
Register a callback called to create macvlan
Definition at line 155 of file host-connection.cpp.
References mCreateNetdevMacvlanCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setCreateNetdevPhysCallback (const CreateNetdevPhysCallback & callback)
Register a callback called to create/move phys
Definition at line 160 of file host-connection.cpp.
References mCreateNetdevPhysCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setCreateNetdevVethCallback (const CreateNetdevVethCallback & callback)
Register a callback called to create veth
Definition at line 150 of file host-connection.cpp.
References mCreateNetdevVethCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setCreateZoneCallback (const CreateZoneCallback & callback)
Register a callback called to create new zone
Definition at line 205 of file host-connection.cpp.
References mCreateZoneCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setDeclareFileCallback (const DeclareFileCallback & callback)
Register a callback called to declare file
Definition at line 175 of file host-connection.cpp.
References mDeclareFileCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setDeclareLinkCallback (const DeclareLinkCallback & callback)
Register a callback called to declare link
Definition at line 185 of file host-connection.cpp.
References mDeclareLinkCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setDeclareMountCallback (const DeclareMountCallback & callback)
Register a callback called to declare mount point
Definition at line 180 of file host-connection.cpp.
References mDeclareMountCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setDeleleNetdevIpAddressCallback (const DeleteNetdevIpAddressCallback & callback)
Register a callback called to remove ip address from netdev
Definition at line 170 of file host-connection.cpp.
References mDeleteNetdevIpAddressCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setDestroyNetdevCallback (const DestroyNetdevCallback & callback)
Register a callback called to destroy netdev
Definition at line 165 of file host-connection.cpp.
References mDestroyNetdevCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setDestroyZoneCallback (const DestroyZoneCallback & callback)
Register a callback called to destroy zone
Definition at line 210 of file host-connection.cpp.
References mDestroyZoneCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setGetActiveZoneIdCallback (const GetActiveZoneIdCallback & callback)
Register a callback called to get the active zone id
Definition at line 125 of file host-connection.cpp.
References mGetActiveZoneIdCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setGetDeclarationsCallback (const GetDeclarationsCallback & callback)
Register a callback called to list declarations
Definition at line 190 of file host-connection.cpp.
References mGetDeclarationsCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setGetNetdevAttrsCallback (const GetNetdevAttrsCallback & callback)
Register a callback called to get network device attributes
Definition at line 140 of file host-connection.cpp.
References mGetNetdevAttrsCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setGetNetdevListCallback (const GetNetdevListCallback & callback)
Register a callback called to get network device list
Definition at line 145 of file host-connection.cpp.
References mGetNetdevListCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setGetZoneDbusesCallback (const GetZoneDbusesCallback & callback)
Register get zone dbuses callback
Definition at line 115 of file host-connection.cpp.
References mGetZoneDbusesCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setGetZoneIdsCallback (const GetZoneIdsCallback & callback)
Register a callback called to get a list of zone ids
Definition at line 120 of file host-connection.cpp.
References mGetZoneIdsCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setGetZoneInfoCallback (const GetZoneInfoCallback & callback)
Register a callback called to get the zone informations
Definition at line 130 of file host-connection.cpp.
References mGetZoneInfoCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setGrantDeviceCallback (const GrantDeviceCallback & callback)
Register a callback called to grant device
Definition at line 235 of file host-connection.cpp.
References mGrantDeviceCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setLockZoneCallback (const LockZoneCallback & callback)
Register a callback called to lock zone
Definition at line 225 of file host-connection.cpp.
References mLockZoneCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setProxyCallCallback (const ProxyCallCallback & callback)
Register proxy call callback
Definition at line 110 of file host-connection.cpp.
References mProxyCallCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setRemoveDeclarationCallback (const RemoveDeclarationCallback & callback)
Register a callback called to remove declarartion
Definition at line 195 of file host-connection.cpp.
References mRemoveDeclarationCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setRevokeDeviceCallback (const RevokeDeviceCallback & callback)
Register a callback called to revoke device
Definition at line 240 of file host-connection.cpp.
References mRevokeDeviceCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setSetActiveZoneCallback (const SetActiveZoneCallback & callback)
Register a callback called to set the active zone
Definition at line 200 of file host-connection.cpp.
References mSetActiveZoneCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setSetNetdevAttrsCallback (const SetNetdevAttrsCallback & callback)
Register a callback called to set network device attributes
Definition at line 135 of file host-connection.cpp.
References mSetNetdevAttrsCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setShutdownZoneCallback (const ShutdownZoneCallback & callback)
Register a callback called to shutdown zone
Definition at line 215 of file host-connection.cpp.
References mShutdownZoneCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setStartZoneCallback (const StartZoneCallback & callback)
Register a callback called to start zone
Definition at line 220 of file host-connection.cpp.
References mStartZoneCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::setUnlockZoneCallback (const UnlockZoneCallback & callback)
Register a callback called to unlock zone
Definition at line 230 of file host-connection.cpp.
References mUnlockZoneCallback.
Referenced by vasum::ZonesManager::ZonesManager().
void vasum::HostConnection::signalZoneDbusState (const std::string & zoneId, const std::string & dbusAddress)
Send signal describing dbus address state change
Definition at line 572 of file host-connection.cpp.
References vasum::api::host::INTERFACE, mDbusConnection, vasum::api::host::OBJECT_PATH, and vasum::api::host::SIGNAL_ZONE_DBUS_STATE.
Referenced by vasum::ZonesManager::handleDbusStateChanged().
bool vasum::HostConnection::waitForName (const unsigned int timeoutMs) private
Definition at line 79 of file host-connection.cpp.
References mNameAcquired, mNameCondition, mNameLost, and mNameMutex.
Referenced by HostConnection().
Member Data Documentation
CreateNetdevMacvlanCallback vasum::HostConnection::mCreateNetdevMacvlanCallback private
Definition at line 299 of file host-connection.hpp.
Referenced by onMessageCall(), and setCreateNetdevMacvlanCallback().
CreateNetdevPhysCallback vasum::HostConnection::mCreateNetdevPhysCallback private
Definition at line 300 of file host-connection.hpp.
Referenced by onMessageCall(), and setCreateNetdevPhysCallback().
CreateNetdevVethCallback vasum::HostConnection::mCreateNetdevVethCallback private
Definition at line 298 of file host-connection.hpp.
Referenced by onMessageCall(), and setCreateNetdevVethCallback().
CreateZoneCallback vasum::HostConnection::mCreateZoneCallback private
Definition at line 309 of file host-connection.hpp.
Referenced by onMessageCall(), and setCreateZoneCallback().
dbus::DbusConnection::Pointer vasum::HostConnection::mDbusConnection private
Definition at line 285 of file host-connection.hpp.
Referenced by HostConnection(), proxyCallAsync(), and signalZoneDbusState().
DeclareFileCallback vasum::HostConnection::mDeclareFileCallback private
Definition at line 303 of file host-connection.hpp.
Referenced by onMessageCall(), and setDeclareFileCallback().
DeclareLinkCallback vasum::HostConnection::mDeclareLinkCallback private
Definition at line 305 of file host-connection.hpp.
Referenced by onMessageCall(), and setDeclareLinkCallback().
DeclareMountCallback vasum::HostConnection::mDeclareMountCallback private
Definition at line 304 of file host-connection.hpp.
Referenced by onMessageCall(), and setDeclareMountCallback().
DeleteNetdevIpAddressCallback vasum::HostConnection::mDeleteNetdevIpAddressCallback private
Definition at line 302 of file host-connection.hpp.
Referenced by onMessageCall(), and setDeleleNetdevIpAddressCallback().
DestroyNetdevCallback vasum::HostConnection::mDestroyNetdevCallback private
Definition at line 301 of file host-connection.hpp.
Referenced by onMessageCall(), and setDestroyNetdevCallback().
DestroyZoneCallback vasum::HostConnection::mDestroyZoneCallback private
Definition at line 310 of file host-connection.hpp.
Referenced by onMessageCall(), and setDestroyZoneCallback().
GetActiveZoneIdCallback vasum::HostConnection::mGetActiveZoneIdCallback private
Definition at line 293 of file host-connection.hpp.
Referenced by onMessageCall(), and setGetActiveZoneIdCallback().
GetDeclarationsCallback vasum::HostConnection::mGetDeclarationsCallback private
Definition at line 306 of file host-connection.hpp.
Referenced by onMessageCall(), and setGetDeclarationsCallback().
GetNetdevAttrsCallback vasum::HostConnection::mGetNetdevAttrsCallback private
Definition at line 296 of file host-connection.hpp.
Referenced by onMessageCall(), and setGetNetdevAttrsCallback().
GetNetdevListCallback vasum::HostConnection::mGetNetdevListCallback private
Definition at line 297 of file host-connection.hpp.
Referenced by onMessageCall(), and setGetNetdevListCallback().
GetZoneDbusesCallback vasum::HostConnection::mGetZoneDbusesCallback private
Definition at line 291 of file host-connection.hpp.
Referenced by onMessageCall(), and setGetZoneDbusesCallback().
GetZoneIdsCallback vasum::HostConnection::mGetZoneIdsCallback private
Definition at line 292 of file host-connection.hpp.
Referenced by onMessageCall(), and setGetZoneIdsCallback().
GetZoneInfoCallback vasum::HostConnection::mGetZoneInfoCallback private
Definition at line 294 of file host-connection.hpp.
Referenced by onMessageCall(), and setGetZoneInfoCallback().
GrantDeviceCallback vasum::HostConnection::mGrantDeviceCallback private
Definition at line 315 of file host-connection.hpp.
Referenced by onMessageCall(), and setGrantDeviceCallback().
LockZoneCallback vasum::HostConnection::mLockZoneCallback private
Definition at line 313 of file host-connection.hpp.
Referenced by onMessageCall(), and setLockZoneCallback().
bool vasum::HostConnection::mNameAcquired private
Definition at line 288 of file host-connection.hpp.
Referenced by onNameAcquired(), onNameLost(), and waitForName().
std::condition_variable vasum::HostConnection::mNameCondition private
Definition at line 287 of file host-connection.hpp.
Referenced by onNameAcquired(), onNameLost(), and waitForName().
bool vasum::HostConnection::mNameLost private
Definition at line 289 of file host-connection.hpp.
Referenced by onNameLost(), and waitForName().
std::mutex vasum::HostConnection::mNameMutex private
Definition at line 286 of file host-connection.hpp.
Referenced by onNameAcquired(), onNameLost(), and waitForName().
ProxyCallCallback vasum::HostConnection::mProxyCallCallback private
Definition at line 290 of file host-connection.hpp.
Referenced by onMessageCall(), and setProxyCallCallback().
RemoveDeclarationCallback vasum::HostConnection::mRemoveDeclarationCallback private
Definition at line 307 of file host-connection.hpp.
Referenced by onMessageCall(), and setRemoveDeclarationCallback().
RevokeDeviceCallback vasum::HostConnection::mRevokeDeviceCallback private
Definition at line 316 of file host-connection.hpp.
Referenced by onMessageCall(), and setRevokeDeviceCallback().
SetActiveZoneCallback vasum::HostConnection::mSetActiveZoneCallback private
Definition at line 308 of file host-connection.hpp.
Referenced by onMessageCall(), and setSetActiveZoneCallback().
SetNetdevAttrsCallback vasum::HostConnection::mSetNetdevAttrsCallback private
Definition at line 295 of file host-connection.hpp.
Referenced by onMessageCall(), and setSetNetdevAttrsCallback().
ShutdownZoneCallback vasum::HostConnection::mShutdownZoneCallback private
Definition at line 311 of file host-connection.hpp.
Referenced by onMessageCall(), and setShutdownZoneCallback().
StartZoneCallback vasum::HostConnection::mStartZoneCallback private
Definition at line 312 of file host-connection.hpp.
Referenced by onMessageCall(), and setStartZoneCallback().
UnlockZoneCallback vasum::HostConnection::mUnlockZoneCallback private
Definition at line 314 of file host-connection.hpp.
Referenced by onMessageCall(), and setUnlockZoneCallback().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/server/host-connection.hpp
/home/dariusz/task/security-containers/server/host-connection.cpp