Vasum: vasum::ipc::RequestQueue< RequestIdType > Class Template Reference
vasum::ipc::RequestQueue< RequestIdType > Class Template Reference
#include <request-queue.hpp>
Classes
struct Request
Public Member Functions
RequestQueue ()=default
RequestQueue (const RequestQueue &)=delete
RequestQueue & operator= (const RequestQueue &)=delete
int getFD ()
bool isEmpty ()
void pushBack (const RequestIdType requestID, const std::shared_ptr< void > &data=nullptr)
void pushFront (const RequestIdType requestID, const std::shared_ptr< void > &data=nullptr)
Request pop ()
template<typename Predicate >
bool removeIf (Predicate predicate)
Private Types
typedef std::unique_lock
< std::mutex > Lock
Private Attributes
std::list< Request > mRequests
std::mutex mStateMutex
utils::EventFD mEventFD
Detailed Description
template<typename RequestIdType>
class vasum::ipc::RequestQueue< RequestIdType >
Class for managing a queue of Requests carrying any data
Definition at line 44 of file request-queue.hpp.
Member Typedef Documentation
template<typename RequestIdType> typedef std::unique_lock<std::mutex> vasum::ipc::RequestQueue< RequestIdType >::Lock private
Definition at line 114 of file request-queue.hpp.
Constructor & Destructor Documentation
template<typename RequestIdType> vasum::ipc::RequestQueue< RequestIdType >::RequestQueue () default
template<typename RequestIdType> vasum::ipc::RequestQueue< RequestIdType >::RequestQueue (const RequestQueue< RequestIdType > &) delete
Member Function Documentation
template<typename RequestIdType > int vasum::ipc::RequestQueue< RequestIdType >::getFD ()
Returns
event's file descriptor
Definition at line 122 of file request-queue.hpp.
Referenced by vasum::ipc::Processor::getEventFD().
template<typename RequestIdType > bool vasum::ipc::RequestQueue< RequestIdType >::isEmpty ()
Returns
is the queue empty
Definition at line 129 of file request-queue.hpp.
Referenced by vasum::ipc::Processor::onFinishRequest().
template<typename RequestIdType> RequestQueue& vasum::ipc::RequestQueue< RequestIdType >::operator= (const RequestQueue< RequestIdType > &) delete
template<typename RequestIdType > RequestQueue< RequestIdType >::Request vasum::ipc::RequestQueue< RequestIdType >::pop ()
Returns
get the data from the next request
Definition at line 156 of file request-queue.hpp.
Referenced by vasum::ipc::Processor::handleEvent(), and vasum::ipc::Processor::onFinishRequest().
template<typename RequestIdType> void vasum::ipc::RequestQueue< RequestIdType >::pushBack (const RequestIdType requestID, const std::shared_ptr< void > & data = nullptr)
Push data to back of the queue
Parameters
requestID request type
data data corresponding to the request
Definition at line 136 of file request-queue.hpp.
Referenced by vasum::ipc::Processor::addPeer(), vasum::ipc::Processor::callAsync(), vasum::ipc::Processor::removePeerSyncInternal(), vasum::ipc::Processor::signal(), and vasum::ipc::Processor::stop().
template<typename RequestIdType> void vasum::ipc::RequestQueue< RequestIdType >::pushFront (const RequestIdType requestID, const std::shared_ptr< void > & data = nullptr)
Push data to back of the queue
Parameters
requestID request type
data data corresponding to the request
Definition at line 146 of file request-queue.hpp.
Referenced by vasum::ipc::Processor::sendResult(), vasum::ipc::Processor::sendVoid(), and vasum::ipc::Processor::signalInternal().
template<typename RequestIdType > template<typename Predicate > bool vasum::ipc::RequestQueue< RequestIdType >::removeIf (Predicate predicate)
Remove elements from the queue when the predicate returns true
Parameters
predicate condition
Returns
was anything removed
Definition at line 171 of file request-queue.hpp.
Referenced by vasum::ipc::Processor::callSync(), and vasum::ipc::Processor::removePeerSyncInternal().
Member Data Documentation
template<typename RequestIdType> utils::EventFD vasum::ipc::RequestQueue< RequestIdType >::mEventFD private
Definition at line 118 of file request-queue.hpp.
template<typename RequestIdType> std::list<Request> vasum::ipc::RequestQueue< RequestIdType >::mRequests private
Definition at line 116 of file request-queue.hpp.
template<typename RequestIdType> std::mutex vasum::ipc::RequestQueue< RequestIdType >::mStateMutex private
Definition at line 117 of file request-queue.hpp.
The documentation for this class was generated from the following file:
/home/dariusz/task/security-containers/common/ipc/internals/request-queue.hpp