Vasum: vasum::ipc::Processor Class Reference
vasum::ipc::Processor Class Reference
#include <processor.hpp>
Classes
struct EmptyData
struct ErrorProtocolMessage
struct MethodHandlers
struct PeerInfo
struct RegisterSignalsProtocolMessage
struct ReturnCallbacks
struct SignalHandlers
Public Member Functions
Processor (const std::string &logName="", const PeerCallback &newPeerCallback=nullptr, const PeerCallback &removedPeerCallback=nullptr, const unsigned int maxNumberOfPeers=DEFAULT_MAX_NUMBER_OF_PEERS)
~Processor ()
Processor (const Processor &)=delete
Processor (Processor &&)=delete
Processor & operator= (const Processor &)=delete
void start ()
bool isStarted ()
void stop ()
void setNewPeerCallback (const PeerCallback &newPeerCallback)
void setRemovedPeerCallback (const PeerCallback &removedPeerCallback)
PeerID addPeer (const std::shared_ptr< Socket > &socketPtr)
template<typename SentDataType , typename ReceivedDataType >
void setMethodHandler (const MethodID methodID, const typename MethodHandler< SentDataType, ReceivedDataType >::type &process)
template<typename ReceivedDataType >
void setSignalHandler (const MethodID methodID, const typename SignalHandler< ReceivedDataType >::type &process)
void sendResult (const MethodID methodID, const PeerID peerID, const MessageID messageID, const std::shared_ptr< void > &data)
void sendError (const PeerID peerID, const MessageID messageID, const int errorCode, const std::string &message)
void sendVoid (const MethodID methodID, const PeerID peerID, const MessageID messageID)
void removeMethod (const MethodID methodID)
template<typename SentDataType , typename ReceivedDataType >
std::shared_ptr< ReceivedDataType > callSync (const MethodID methodID, const PeerID peerID, const std::shared_ptr< SentDataType > &data, unsigned int timeoutMS=500)
template<typename SentDataType , typename ReceivedDataType >
MessageID callAsync (const MethodID methodID, const PeerID peerID, const std::shared_ptr< SentDataType > &data, const typename ResultHandler< ReceivedDataType >::type &process)
template<typename SentDataType >
void signal (const MethodID methodID, const std::shared_ptr< SentDataType > &data)
bool handleLostConnection (const FileDescriptor fd)
bool handleInput (const FileDescriptor fd)
bool handleEvent ()
FileDescriptor getEventFD ()
Static Public Attributes
static const MethodID RETURN_METHOD_ID = std::numeric_limits<MethodID>::max()
static const MethodID REGISTER_SIGNAL_METHOD_ID = std::numeric_limits<MethodID>::max() - 1
static const MethodID ERROR_METHOD_ID = std::numeric_limits<MethodID>::max() - 2
Private Types
enum Event {
Event::FINISH, Event::METHOD, Event::SIGNAL, Event::ADD_PEER,
Event::REMOVE_PEER, Event::SEND_RESULT
}
typedef std::function< void(int
fd, std::shared_ptr< void >
&data)> SerializeCallback
typedef std::function
< std::shared_ptr< void >int
fd)> ParseCallback
typedef std::unique_lock
< std::mutex > Lock
typedef RequestQueue< Event >
::Request Request
typedef std::vector< PeerInfo > Peers
Private Member Functions
template<typename SentDataType , typename ReceivedDataType >
void setMethodHandlerInternal (const MethodID methodID, const typename MethodHandler< SentDataType, ReceivedDataType >::type &process)
template<typename ReceivedDataType >
void setSignalHandlerInternal (const MethodID methodID, const typename SignalHandler< ReceivedDataType >::type &handler)
template<typename SentDataType >
void signalInternal (const MethodID methodID, const PeerID peerID, const std::shared_ptr< SentDataType > &data)
bool onMethodRequest (MethodRequest &request)
bool onSignalRequest (SignalRequest &request)
bool onAddPeerRequest (AddPeerRequest &request)
bool onRemovePeerRequest (RemovePeerRequest &request)
bool onSendResultRequest (SendResultRequest &request)
bool onFinishRequest (FinishRequest &request)
bool onReturnValue (Peers::iterator &peerIt, const MessageID messageID)
bool onRemoteMethod (Peers::iterator &peerIt, const MethodID methodID, const MessageID messageID, std::shared_ptr< MethodHandlers > methodCallbacks)
bool onRemoteSignal (Peers::iterator &peerIt, const MethodID methodID, const MessageID messageID, std::shared_ptr< SignalHandlers > signalCallbacks)
void removePeerInternal (Peers::iterator peerIt, const std::exception_ptr &exceptionPtr)
void removePeerSyncInternal (const PeerID peerID, Lock &lock)
void onNewSignals (const PeerID peerID, std::shared_ptr< RegisterSignalsProtocolMessage > &data)
void onErrorSignal (const PeerID peerID, std::shared_ptr< ErrorProtocolMessage > &data)
Peers::iterator getPeerInfoIterator (const FileDescriptor fd)
Peers::iterator getPeerInfoIterator (const PeerID peerID)
Private Attributes
std::string mLogPrefix
RequestQueue< Event > mRequestQueue
bool mIsRunning
std::unordered_map< MethodID,
std::shared_ptr
< MethodHandlers > > mMethodsCallbacks
std::unordered_map< MethodID,
std::shared_ptr
< SignalHandlers > > mSignalsCallbacks
std::unordered_map< MethodID,
std::list< PeerID > > mSignalsPeers
Peers mPeerInfo
std::unordered_map< MessageID,
ReturnCallbacks > mReturnCallbacks
std::mutex mStateMutex
PeerCallback mNewPeerCallback
PeerCallback mRemovedPeerCallback
unsigned int mMaxNumberOfPeers
Friends
std::ostream & operator<< (std::ostream &os, const Processor::Event &event)
Detailed Description
This class wraps communication via UX sockets
It's intended to be used both in Client and Service classes. It uses a serialization mechanism from libConfig. Library user will only have to pass the types that each call will send and receive
Message format:
MethodID - probably casted enum. MethodID == std::numeric_limits<MethodID>::max() is reserved for return messages
MessageID - unique id of a message exchange sent by this object instance. Used to identify reply messages.
Rest: The data written in a callback. One type per method.ReturnCallbacks
TODO:
synchronous call to many peers
implement HandlerStore class for storing both signals and methods
API for removing signals
implement CallbackStore - thread safe calling/setting callbacks
helper function for removing from unordered map
new way to generate UIDs
callbacks for serialization/parsing
store Sockets in a vector, maybe SocketStore?
waiting till the EventQueue is empty before leaving stop()
no new events added after stop() called
Definition at line 87 of file processor.hpp.
Member Typedef Documentation
typedef std::unique_lock<std::mutex> vasum::ipc::Processor::Lock private
Definition at line 331 of file processor.hpp.
typedef std::function<std::shared_ptr<void>int fd)> vasum::ipc::Processor::ParseCallback private
Definition at line 330 of file processor.hpp.
typedef std::vector<PeerInfo> vasum::ipc::Processor::Peers private
Definition at line 421 of file processor.hpp.
typedef RequestQueue<Event>::Request vasum::ipc::Processor::Request private
Definition at line 332 of file processor.hpp.
typedef std::function<void(int fd, std::shared_ptr<void>& data)> vasum::ipc::Processor::SerializeCallback private
Definition at line 329 of file processor.hpp.
Member Enumeration Documentation
enum vasum::ipc::Processor::Event strong private
Enumerator
FINISH
METHOD
SIGNAL
ADD_PEER
REMOVE_PEER
SEND_RESULT
Definition at line 89 of file processor.hpp.
Constructor & Destructor Documentation
vasum::ipc::Processor::Processor (const std::string & logName = "", const PeerCallback & newPeerCallback = nullptr, const PeerCallback & removedPeerCallback = nullptr, const unsigned int maxNumberOfPeers = DEFAULT_MAX_NUMBER_OF_PEERS)
Constructs the Processor, but doesn't start it. The object is ready to add methods.
Parameters
newPeerCallback called when a new peer arrives
removedPeerCallback called when the Processor stops listening for this peer
Definition at line 55 of file processor.cpp.
References ERROR_METHOD_ID, mLogPrefix, onErrorSignal(), onNewSignals(), and REGISTER_SIGNAL_METHOD_ID.
vasum::ipc::Processor::~Processor ()
Definition at line 74 of file processor.cpp.
References mLogPrefix, and stop().
vasum::ipc::Processor::Processor (const Processor &) delete
vasum::ipc::Processor::Processor (Processor &&) delete
Member Function Documentation
PeerID vasum::ipc::Processor::addPeer (const std::shared_ptr< Socket > & socketPtr)
From now on socket is owned by the Processor object. Calls the newPeerCallback.
Parameters
socketPtr pointer to the new socket
Returns
peerID of the new user
Definition at line 189 of file processor.cpp.
References ADD_PEER, mLogPrefix, mRequestQueue, mStateMutex, and vasum::ipc::RequestQueue< RequestIdType >::pushBack().
Referenced by vasum::ipc::Client::start().
template<typename SentDataType , typename ReceivedDataType > MessageID vasum::ipc::Processor::callAsync (const MethodID methodID, const PeerID peerID, const std::shared_ptr< SentDataType > & data, const typename ResultHandler< ReceivedDataType >::type & process)
Asynchronous method call
Parameters
methodID API dependent id of the method
peerID id of the peer
data data to sent
process callback processing the return data
Template Parameters
SentDataType data type to send
ReceivedDataType data type to receive
Definition at line 595 of file processor.hpp.
References data, METHOD, mRequestQueue, mStateMutex, and vasum::ipc::RequestQueue< RequestIdType >::pushBack().
Referenced by vasum::ipc::Client::callAsync(), and vasum::ipc::Service::callAsync().
template<typename SentDataType , typename ReceivedDataType > std::shared_ptr< ReceivedDataType > vasum::ipc::Processor::callSync (const MethodID methodID, const PeerID peerID, const std::shared_ptr< SentDataType > & data, unsigned int timeoutMS = 500)
Synchronous method call.
Parameters
methodID API dependent id of the method
peerID id of the peer
data data to send
timeoutMS how long to wait for the return value before throw
Template Parameters
SentDataType data type to send
ReceivedDataType data type to receive
Definition at line 608 of file processor.hpp.
References data, vasum::ipc::Result< Data >::get(), vasum::ipc::Result< Data >::isValid(), METHOD, mLogPrefix, mRequestQueue, mReturnCallbacks, mStateMutex, vasum::ipc::RequestQueue< RequestIdType >::removeIf(), and removePeerSyncInternal().
Referenced by vasum::ipc::Client::callSync(), and vasum::ipc::Service::callSync().
FileDescriptor vasum::ipc::Processor::getEventFD ()
Returns
file descriptor for the internal event's queue
Definition at line 150 of file processor.cpp.
References vasum::ipc::RequestQueue< RequestIdType >::getFD(), mRequestQueue, and mStateMutex.
Referenced by vasum::ipc::Client::start(), vasum::ipc::Service::start(), vasum::ipc::Client::stop(), and vasum::ipc::Service::stop().
Processor::Peers::iterator vasum::ipc::Processor::getPeerInfoIterator (const FileDescriptor fd) private
Definition at line 84 of file processor.cpp.
References mPeerInfo.
Referenced by handleInput(), handleLostConnection(), onAddPeerRequest(), onMethodRequest(), onRemovePeerRequest(), onSendResultRequest(), onSignalRequest(), and removePeerSyncInternal().
Processor::Peers::iterator vasum::ipc::Processor::getPeerInfoIterator (const PeerID peerID) private
Definition at line 91 of file processor.cpp.
References mPeerInfo.
bool vasum::ipc::Processor::handleEvent ()
Handle one event from the internal event's queue
Returns
should the polling structure be rebuild
Definition at line 455 of file processor.cpp.
References ADD_PEER, FINISH, METHOD, mLogPrefix, mRequestQueue, mStateMutex, onAddPeerRequest(), onFinishRequest(), onMethodRequest(), onRemovePeerRequest(), onSendResultRequest(), onSignalRequest(), vasum::ipc::RequestQueue< RequestIdType >::pop(), REMOVE_PEER, SEND_RESULT, and SIGNAL.
Referenced by vasum::ipc::Client::start(), and vasum::ipc::Service::start().
bool vasum::ipc::Processor::handleInput (const FileDescriptor fd)
Handles input from one peer. Handler used in external polling.
Parameters
fd file description identifying the peer
Returns
should the polling structure be rebuild
Definition at line 273 of file processor.cpp.
References vasum::ipc::Socket::getGuard(), getPeerInfoIterator(), mLogPrefix, mMethodsCallbacks, mPeerInfo, mSignalsCallbacks, mStateMutex, onRemoteMethod(), onRemoteSignal(), onReturnValue(), vasum::ipc::Socket::read(), removePeerInternal(), and RETURN_METHOD_ID.
Referenced by vasum::ipc::Client::handle(), and vasum::ipc::Service::handle().
bool vasum::ipc::Processor::handleLostConnection (const FileDescriptor fd)
Removes one peer. Handler used in external polling.
Parameters
fd file description identifying the peer
Returns
should the polling structure be rebuild
Definition at line 264 of file processor.cpp.
References getPeerInfoIterator(), mStateMutex, and removePeerInternal().
Referenced by vasum::ipc::Client::handle(), and vasum::ipc::Service::handle().
bool vasum::ipc::Processor::isStarted ()
Returns
is processor running
Definition at line 98 of file processor.cpp.
References mIsRunning, and mStateMutex.
Referenced by vasum::ipc::Client::isStarted(), vasum::ipc::Service::isStarted(), vasum::ipc::Client::start(), vasum::ipc::Service::start(), vasum::ipc::Client::stop(), vasum::ipc::Service::stop(), and stop().
bool vasum::ipc::Processor::onAddPeerRequest (AddPeerRequest & request) private
Definition at line 554 of file processor.cpp.
References data, getPeerInfoIterator(), mLogPrefix, mMaxNumberOfPeers, mNewPeerCallback, mPeerInfo, mSignalsCallbacks, vasum::ipc::AddPeerRequest::peerID, REGISTER_SIGNAL_METHOD_ID, and vasum::ipc::AddPeerRequest::socketPtr.
Referenced by handleEvent().
void vasum::ipc::Processor::onErrorSignal (const PeerID peerID, std::shared_ptr< ErrorProtocolMessage > & data) private
Definition at line 336 of file processor.cpp.
References IGNORE_EXCEPTIONS, mLogPrefix, mReturnCallbacks, and vasum::ipc::Processor::ReturnCallbacks::process.
Referenced by Processor().
bool vasum::ipc::Processor::onFinishRequest (FinishRequest & request) private
Definition at line 649 of file processor.cpp.
References ADD_PEER, vasum::ipc::FinishRequest::conditionPtr, FINISH, IGNORE_EXCEPTIONS, vasum::ipc::RequestQueue< RequestIdType >::isEmpty(), METHOD, mIsRunning, mLogPrefix, mPeerInfo, mRequestQueue, onRemovePeerRequest(), onSendResultRequest(), vasum::ipc::RequestQueue< RequestIdType >::pop(), REMOVE_PEER, removePeerInternal(), SEND_RESULT, and SIGNAL.
Referenced by handleEvent().
bool vasum::ipc::Processor::onMethodRequest (MethodRequest & request) private
Definition at line 476 of file processor.cpp.
References vasum::ipc::MethodRequest::data, vasum::ipc::Socket::getFD(), vasum::ipc::Socket::getGuard(), getPeerInfoIterator(), IGNORE_EXCEPTIONS, vasum::ipc::MethodRequest::messageID, vasum::ipc::MethodRequest::methodID, mLogPrefix, mPeerInfo, mReturnCallbacks, vasum::ipc::MethodRequest::parse, vasum::ipc::MethodRequest::peerID, vasum::ipc::MethodRequest::process, removePeerInternal(), vasum::ipc::MethodRequest::serialize, and vasum::ipc::Socket::write().
Referenced by handleEvent().
void vasum::ipc::Processor::onNewSignals (const PeerID peerID, std::shared_ptr< RegisterSignalsProtocolMessage > & data) private
Definition at line 327 of file processor.cpp.
References mLogPrefix, and mSignalsPeers.
Referenced by Processor().
bool vasum::ipc::Processor::onRemoteMethod (Peers::iterator & peerIt, const MethodID methodID, const MessageID messageID, std::shared_ptr< MethodHandlers > methodCallbacks) private
Definition at line 418 of file processor.cpp.
References data, vasum::ipc::IPCUserException::getCode(), mLogPrefix, removePeerInternal(), and sendError().
Referenced by handleInput().
bool vasum::ipc::Processor::onRemoteSignal (Peers::iterator & peerIt, const MethodID methodID, const MessageID messageID, std::shared_ptr< SignalHandlers > signalCallbacks) private
Definition at line 384 of file processor.cpp.
References data, mLogPrefix, and removePeerInternal().
Referenced by handleInput().
bool vasum::ipc::Processor::onRemovePeerRequest (RemovePeerRequest & request) private
Definition at line 592 of file processor.cpp.
References vasum::ipc::RemovePeerRequest::conditionPtr, getPeerInfoIterator(), mLogPrefix, vasum::ipc::RemovePeerRequest::peerID, and removePeerInternal().
Referenced by handleEvent(), and onFinishRequest().
bool vasum::ipc::Processor::onReturnValue (Peers::iterator & peerIt, const MessageID messageID) private
Definition at line 348 of file processor.cpp.
References data, IGNORE_EXCEPTIONS, mLogPrefix, mReturnCallbacks, vasum::ipc::Processor::ReturnCallbacks::parse, vasum::ipc::Processor::ReturnCallbacks::process, and removePeerInternal().
Referenced by handleInput().
bool vasum::ipc::Processor::onSendResultRequest (SendResultRequest & request) private
Definition at line 604 of file processor.cpp.
References vasum::ipc::SendResultRequest::data, vasum::ipc::Socket::getFD(), vasum::ipc::Socket::getGuard(), getPeerInfoIterator(), IGNORE_EXCEPTIONS, vasum::ipc::SendResultRequest::messageID, vasum::ipc::SendResultRequest::methodID, mLogPrefix, mMethodsCallbacks, mPeerInfo, mReturnCallbacks, vasum::ipc::SendResultRequest::peerID, removePeerInternal(), RETURN_METHOD_ID, and vasum::ipc::Socket::write().
Referenced by handleEvent(), and onFinishRequest().
bool vasum::ipc::Processor::onSignalRequest (SignalRequest & request) private
Definition at line 525 of file processor.cpp.
References vasum::ipc::SignalRequest::data, vasum::ipc::Socket::getFD(), vasum::ipc::Socket::getGuard(), getPeerInfoIterator(), vasum::ipc::SignalRequest::messageID, vasum::ipc::SignalRequest::methodID, mLogPrefix, mPeerInfo, vasum::ipc::SignalRequest::peerID, removePeerInternal(), vasum::ipc::SignalRequest::serialize, and vasum::ipc::Socket::write().
Referenced by handleEvent().
Processor& vasum::ipc::Processor::operator= (const Processor &) delete
void vasum::ipc::Processor::removeMethod (const MethodID methodID)
Removes the callback
Parameters
methodID API dependent id of the method
Definition at line 183 of file processor.cpp.
References mMethodsCallbacks, and mStateMutex.
Referenced by vasum::ipc::Client::removeMethod(), and vasum::ipc::Service::removeMethod().
void vasum::ipc::Processor::removePeerInternal (Peers::iterator peerIt, const std::exception_ptr & exceptionPtr) private
Definition at line 225 of file processor.cpp.
References IGNORE_EXCEPTIONS, mLogPrefix, mPeerInfo, mRemovedPeerCallback, mReturnCallbacks, and mSignalsPeers.
Referenced by handleInput(), handleLostConnection(), onFinishRequest(), onMethodRequest(), onRemoteMethod(), onRemoteSignal(), onRemovePeerRequest(), onReturnValue(), onSendResultRequest(), and onSignalRequest().
void vasum::ipc::Processor::removePeerSyncInternal (const PeerID peerID, Lock & lock) private
Definition at line 203 of file processor.cpp.
References ADD_PEER, getPeerInfoIterator(), mLogPrefix, mPeerInfo, mRequestQueue, vasum::ipc::RequestQueue< RequestIdType >::pushBack(), REMOVE_PEER, and vasum::ipc::RequestQueue< RequestIdType >::removeIf().
Referenced by callSync().
void vasum::ipc::Processor::sendError (const PeerID peerID, const MessageID messageID, const int errorCode, const std::string & message)
Send error result of the method
Parameters
peerID id of the peer
messageID id of the message to which it replies
errorCode code of the error
message description of the error
Definition at line 165 of file processor.cpp.
References data, and ERROR_METHOD_ID.
Referenced by onRemoteMethod(), and vasum::ipc::MethodResult::setError().
void vasum::ipc::Processor::sendResult (const MethodID methodID, const PeerID peerID, const MessageID messageID, const std::shared_ptr< void > & data)
Send result of the method. Used for asynchronous communication, only internally.
Parameters
methodID API dependent id of the method
peerID id of the peer
messageID id of the message to which it replies
data data to send
Definition at line 156 of file processor.cpp.
References data, mRequestQueue, vasum::ipc::RequestQueue< RequestIdType >::pushFront(), and SEND_RESULT.
Referenced by vasum::ipc::MethodResult::setInternal().
void vasum::ipc::Processor::sendVoid (const MethodID methodID, const PeerID peerID, const MessageID messageID)
Indicate that the method handler finished
Parameters
methodID API dependent id of the method
peerID id of the peer
messageID id of the message to which it replies
Definition at line 174 of file processor.cpp.
References data, mRequestQueue, vasum::ipc::RequestQueue< RequestIdType >::pushFront(), and SEND_RESULT.
Referenced by vasum::ipc::MethodResult::setVoid().
template<typename SentDataType , typename ReceivedDataType > void vasum::ipc::Processor::setMethodHandler (const MethodID methodID, const typename MethodHandler< SentDataType, ReceivedDataType >::type & process)
Saves the callbacks connected to the method id. When a message with the given method id is received, the data will be passed to the serialization callback through file descriptor.
Then the process callback will be called with the parsed data.
Parameters
methodID API dependent id of the method
process data processing callback
Template Parameters
SentDataType data type to send
ReceivedDataType data type to receive
Definition at line 517 of file processor.hpp.
References mLogPrefix, mSignalsCallbacks, mStateMutex, REGISTER_SIGNAL_METHOD_ID, and RETURN_METHOD_ID.
Referenced by vasum::ipc::Client::setMethodHandler(), and vasum::ipc::Service::setMethodHandler().
template<typename SentDataType , typename ReceivedDataType > void vasum::ipc::Processor::setMethodHandlerInternal (const MethodID methodID, const typename MethodHandler< SentDataType, ReceivedDataType >::type & process) private
Definition at line 493 of file processor.hpp.
References data, vasum::ipc::Processor::MethodHandlers::method, mMethodsCallbacks, vasum::ipc::Processor::MethodHandlers::parse, and vasum::ipc::Processor::MethodHandlers::serialize.
void vasum::ipc::Processor::setNewPeerCallback (const PeerCallback & newPeerCallback)
Set the callback called for each new connection to a peer
Parameters
newPeerCallback the callback
Definition at line 138 of file processor.cpp.
References mNewPeerCallback, and mStateMutex.
Referenced by vasum::ipc::Client::setNewPeerCallback(), and vasum::ipc::Service::setNewPeerCallback().
void vasum::ipc::Processor::setRemovedPeerCallback (const PeerCallback & removedPeerCallback)
Set the callback called when connection to a peer is lost
Parameters
removedPeerCallback the callback
Definition at line 144 of file processor.cpp.
References mRemovedPeerCallback, and mStateMutex.
Referenced by vasum::ipc::Client::setRemovedPeerCallback(), and vasum::ipc::Service::setRemovedPeerCallback().
template<typename ReceivedDataType > void vasum::ipc::Processor::setSignalHandler (const MethodID methodID, const typename SignalHandler< ReceivedDataType >::type & process)
Saves the callbacks connected to the method id. When a message with the given method id is received, the data will be passed to the serialization callback through file descriptor.
Then the process callback will be called with the parsed data. There is no return data to send back.
Adding signal sends a registering message to all peers
Parameters
methodID API dependent id of the method
process data processing callback
Template Parameters
ReceivedDataType data type to receive
Definition at line 560 of file processor.hpp.
References data, mLogPrefix, mMethodsCallbacks, mPeerInfo, mStateMutex, REGISTER_SIGNAL_METHOD_ID, and RETURN_METHOD_ID.
Referenced by vasum::ipc::Client::setSignalHandler(), and vasum::ipc::Service::setSignalHandler().
template<typename ReceivedDataType > void vasum::ipc::Processor::setSignalHandlerInternal (const MethodID methodID, const typename SignalHandler< ReceivedDataType >::type & handler) private
Definition at line 539 of file processor.hpp.
References mSignalsCallbacks, vasum::ipc::Processor::SignalHandlers::parse, and vasum::ipc::Processor::SignalHandlers::signal.
template<typename SentDataType > void vasum::ipc::Processor::signal (const MethodID methodID, const std::shared_ptr< SentDataType > & data)
Send a signal to the peer. There is no return value from the peer Sends any data only if a peer registered this a signal
Parameters
methodID API dependent id of the method
data data to sent
Template Parameters
SentDataType data type to send
Definition at line 669 of file processor.hpp.
References data, mLogPrefix, mRequestQueue, mSignalsPeers, mStateMutex, vasum::ipc::RequestQueue< RequestIdType >::pushBack(), and SIGNAL.
Referenced by vasum::ipc::Client::signal(), and vasum::ipc::Service::signal().
template<typename SentDataType > void vasum::ipc::Processor::signalInternal (const MethodID methodID, const PeerID peerID, const std::shared_ptr< SentDataType > & data) private
Definition at line 660 of file processor.hpp.
References data, mRequestQueue, vasum::ipc::RequestQueue< RequestIdType >::pushFront(), and SIGNAL.
void vasum::ipc::Processor::start ()
Start processing.
Definition at line 104 of file processor.cpp.
References mIsRunning, mLogPrefix, and mStateMutex.
Referenced by vasum::ipc::Client::start(), and vasum::ipc::Service::start().
void vasum::ipc::Processor::stop ()
Stops the processing thread. No incoming data will be handled after.
Definition at line 115 of file processor.cpp.
References FINISH, isStarted(), mIsRunning, mLogPrefix, mPeerInfo, mRequestQueue, mStateMutex, and vasum::ipc::RequestQueue< RequestIdType >::pushBack().
Referenced by vasum::ipc::Client::stop(), vasum::ipc::Service::stop(), and ~Processor().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Processor::Event & event) friend
Definition at line 692 of file processor.cpp.
Member Data Documentation
const MethodID vasum::ipc::Processor::ERROR_METHOD_ID = std::numeric_limits<MethodID>::max() - 2 static
Error return message
Definition at line 114 of file processor.hpp.
Referenced by Processor(), and sendError().
bool vasum::ipc::Processor::mIsRunning private
Definition at line 427 of file processor.hpp.
Referenced by isStarted(), onFinishRequest(), start(), and stop().
std::string vasum::ipc::Processor::mLogPrefix private
Definition at line 423 of file processor.hpp.
Referenced by addPeer(), callSync(), handleEvent(), handleInput(), onAddPeerRequest(), onErrorSignal(), onFinishRequest(), onMethodRequest(), onNewSignals(), onRemoteMethod(), onRemoteSignal(), onRemovePeerRequest(), onReturnValue(), onSendResultRequest(), onSignalRequest(), Processor(), removePeerInternal(), removePeerSyncInternal(), setMethodHandler(), setSignalHandler(), signal(), start(), stop(), and ~Processor().
unsigned int vasum::ipc::Processor::mMaxNumberOfPeers private
Definition at line 443 of file processor.hpp.
Referenced by onAddPeerRequest().
std::unordered_map<MethodID, std::shared_ptr<MethodHandlers> > vasum::ipc::Processor::mMethodsCallbacks private
Definition at line 429 of file processor.hpp.
Referenced by handleInput(), onSendResultRequest(), removeMethod(), setMethodHandlerInternal(), and setSignalHandler().
PeerCallback vasum::ipc::Processor::mNewPeerCallback private
Definition at line 440 of file processor.hpp.
Referenced by onAddPeerRequest(), and setNewPeerCallback().
Peers vasum::ipc::Processor::mPeerInfo private
Definition at line 433 of file processor.hpp.
Referenced by getPeerInfoIterator(), handleInput(), onAddPeerRequest(), onFinishRequest(), onMethodRequest(), onSendResultRequest(), onSignalRequest(), removePeerInternal(), removePeerSyncInternal(), setSignalHandler(), and stop().
PeerCallback vasum::ipc::Processor::mRemovedPeerCallback private
Definition at line 441 of file processor.hpp.
Referenced by removePeerInternal(), and setRemovedPeerCallback().
RequestQueue<Event> vasum::ipc::Processor::mRequestQueue private
Definition at line 425 of file processor.hpp.
Referenced by addPeer(), callAsync(), callSync(), getEventFD(), handleEvent(), onFinishRequest(), removePeerSyncInternal(), sendResult(), sendVoid(), signal(), signalInternal(), and stop().
std::unordered_map<MessageID, ReturnCallbacks> vasum::ipc::Processor::mReturnCallbacks private
Definition at line 435 of file processor.hpp.
Referenced by callSync(), onErrorSignal(), onMethodRequest(), onReturnValue(), onSendResultRequest(), and removePeerInternal().
std::unordered_map<MethodID, std::shared_ptr<SignalHandlers> > vasum::ipc::Processor::mSignalsCallbacks private
Definition at line 430 of file processor.hpp.
Referenced by handleInput(), onAddPeerRequest(), setMethodHandler(), and setSignalHandlerInternal().
std::unordered_map<MethodID, std::list<PeerID> > vasum::ipc::Processor::mSignalsPeers private
Definition at line 431 of file processor.hpp.
Referenced by onNewSignals(), removePeerInternal(), and signal().
std::mutex vasum::ipc::Processor::mStateMutex private
Definition at line 438 of file processor.hpp.
Referenced by addPeer(), callAsync(), callSync(), getEventFD(), handleEvent(), handleInput(), handleLostConnection(), isStarted(), removeMethod(), setMethodHandler(), setNewPeerCallback(), setRemovedPeerCallback(), setSignalHandler(), signal(), start(), and stop().
const MethodID vasum::ipc::Processor::REGISTER_SIGNAL_METHOD_ID = std::numeric_limits<MethodID>::max() - 1 static
Indicates an Processor's internal request/broadcast to register a Signal
Definition at line 109 of file processor.hpp.
Referenced by onAddPeerRequest(), Processor(), setMethodHandler(), and setSignalHandler().
const MethodID vasum::ipc::Processor::RETURN_METHOD_ID = std::numeric_limits<MethodID>::max() static
Used to indicate a message with the return value.
Definition at line 104 of file processor.hpp.
Referenced by handleInput(), onSendResultRequest(), setMethodHandler(), and setSignalHandler().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/common/ipc/internals/processor.hpp
/home/dariusz/task/security-containers/common/ipc/internals/processor.cpp