Vasum: vasum::ipc::Client Class Reference
vasum::ipc::Client Class Reference
#include <client.hpp>
Public Member Functions
Client (epoll::EventPoll &eventPoll, const std::string &serverPath)
~Client ()
Client (const Client &)=delete
Client & operator= (const Client &)=delete
void start ()
bool isStarted ()
void stop ()
void setNewPeerCallback (const PeerCallback &newPeerCallback)
void setRemovedPeerCallback (const PeerCallback &removedPeerCallback)
template<typename SentDataType , typename ReceivedDataType >
void setMethodHandler (const MethodID methodID, const typename MethodHandler< SentDataType, ReceivedDataType >::type &method)
template<typename ReceivedDataType >
void setSignalHandler (const MethodID methodID, const typename SignalHandler< ReceivedDataType >::type &signal)
void removeMethod (const MethodID methodID)
template<typename SentDataType , typename ReceivedDataType >
std::shared_ptr< ReceivedDataType > callSync (const MethodID methodID, const std::shared_ptr< SentDataType > &data, unsigned int timeoutMS=500)
template<typename SentDataType , typename ReceivedDataType >
void callAsync (const MethodID methodID, const std::shared_ptr< SentDataType > &data, const typename ResultHandler< ReceivedDataType >::type &resultCallback)
template<typename SentDataType >
void signal (const MethodID methodID, const std::shared_ptr< SentDataType > &data)
Private Member Functions
void handle (const FileDescriptor fd, const epoll::Events pollEvents)
Private Attributes
epoll::EventPoll & mEventPoll
PeerID mServiceID
Processor mProcessor
std::string mSocketPath
Detailed Description
This class wraps communication via UX sockets for client applications. It uses serialization mechanism from libConfig.
For message format
See Also
ipc::Processor
Definition at line 45 of file client.hpp.
Constructor & Destructor Documentation
Client::Client (epoll::EventPoll & eventPoll, const std::string & serverPath)
Parameters
eventPoll event poll
serverPath path to the server's socket
Definition at line 34 of file client.cpp.
References setNewPeerCallback(), and setRemovedPeerCallback().
Client::~Client ()
Definition at line 44 of file client.cpp.
References stop().
vasum::ipc::Client::Client (const Client &) delete
Member Function Documentation
template<typename SentDataType , typename ReceivedDataType > void Client::callAsync (const MethodID methodID, const std::shared_ptr< SentDataType > & data, const typename ResultHandler< ReceivedDataType >::type & resultCallback)
Asynchronous method call. The return callback will be called on return data arrival. It will be run in the PROCESSOR thread.
Parameters
methodID API dependent id of the method
data data to send
resultCallback callback for result serialization and handling
Definition at line 194 of file client.hpp.
References vasum::ipc::Processor::callAsync(), data, mProcessor, and mServiceID.
template<typename SentDataType , typename ReceivedDataType > std::shared_ptr< ReceivedDataType > Client::callSync (const MethodID methodID, const std::shared_ptr< SentDataType > & data, unsigned int timeoutMS = 500)
Synchronous method call.
Parameters
methodID API dependent id of the method
data data to send
timeoutMS how long to wait for the return value before throw
Returns
result data
Definition at line 185 of file client.hpp.
References vasum::ipc::Processor::callSync(), data, mProcessor, and mServiceID.
void Client::handle (const FileDescriptor fd, const epoll::Events pollEvents) private
Definition at line 88 of file client.cpp.
References vasum::ipc::Processor::handleInput(), vasum::ipc::Processor::handleLostConnection(), isStarted(), and mProcessor.
Referenced by setNewPeerCallback().
bool Client::isStarted ()
Returns
is the communication thread running
Definition at line 72 of file client.cpp.
References vasum::ipc::Processor::isStarted(), and mProcessor.
Referenced by handle().
Client& vasum::ipc::Client::operator= (const Client &) delete
void Client::removeMethod (const MethodID methodID)
Removes the callback
Parameters
methodID API dependent id of the method
Definition at line 135 of file client.cpp.
References mProcessor, and vasum::ipc::Processor::removeMethod().
template<typename SentDataType , typename ReceivedDataType > void Client::setMethodHandler (const MethodID methodID, const typename MethodHandler< SentDataType, ReceivedDataType >::type & method)
Saves the callback connected to the method id. When a message with the given method id is received the data will be parsed and passed to this callback.
Parameters
methodID API dependent id of the method
method method handling implementation
Definition at line 169 of file client.hpp.
References mProcessor, and vasum::ipc::Processor::setMethodHandler().
void Client::setNewPeerCallback (const PeerCallback & newPeerCallback)
Set the callback called for each new connection to a peer
Parameters
newPeerCallback the callback
Definition at line 108 of file client.cpp.
References vasum::epoll::EventPoll::addFD(), handle(), mEventPoll, mProcessor, and vasum::ipc::Processor::setNewPeerCallback().
Referenced by Client().
void Client::setRemovedPeerCallback (const PeerCallback & removedPeerCallback)
Set the callback called when connection to a peer is lost
Parameters
removedPeerCallback the callback
Definition at line 123 of file client.cpp.
References mEventPoll, mProcessor, vasum::epoll::EventPoll::removeFD(), and vasum::ipc::Processor::setRemovedPeerCallback().
Referenced by Client().
template<typename ReceivedDataType > void Client::setSignalHandler (const MethodID methodID, const typename SignalHandler< ReceivedDataType >::type & signal)
Saves the callback connected to the method id. When a message with the given method id is received the data will be parsed and passed to this callback.
Parameters
methodID API dependent id of the method
signal signal handling implementation
Template Parameters
ReceivedDataType data type to serialize
Definition at line 177 of file client.hpp.
References mProcessor, and vasum::ipc::Processor::setSignalHandler().
template<typename SentDataType > void Client::signal (const MethodID methodID, const std::shared_ptr< SentDataType > & data)
Send a signal to the peer. There is no return value from the peer Sends any data only if a peer registered this a signal
Parameters
methodID API dependent id of the method
data data to sent
Template Parameters
SentDataType data type to send
Definition at line 207 of file client.hpp.
References data, mProcessor, and vasum::ipc::Processor::signal().
void Client::start ()
Starts processing
Definition at line 54 of file client.cpp.
References vasum::epoll::EventPoll::addFD(), vasum::ipc::Processor::addPeer(), vasum::ipc::Socket::connectSocket(), vasum::ipc::Processor::getEventFD(), vasum::ipc::Processor::handleEvent(), vasum::ipc::Processor::isStarted(), mEventPoll, mProcessor, mServiceID, mSocketPath, and vasum::ipc::Processor::start().
void Client::stop ()
Stops processing
Definition at line 77 of file client.cpp.
References vasum::ipc::Processor::getEventFD(), vasum::ipc::Processor::isStarted(), mEventPoll, mProcessor, vasum::epoll::EventPoll::removeFD(), and vasum::ipc::Processor::stop().
Referenced by ~Client().
Member Data Documentation
epoll::EventPoll& vasum::ipc::Client::mEventPoll private
Definition at line 159 of file client.hpp.
Referenced by setNewPeerCallback(), setRemovedPeerCallback(), start(), and stop().
Processor vasum::ipc::Client::mProcessor private
Definition at line 161 of file client.hpp.
Referenced by callAsync(), callSync(), handle(), isStarted(), removeMethod(), setMethodHandler(), setNewPeerCallback(), setRemovedPeerCallback(), setSignalHandler(), signal(), start(), and stop().
PeerID vasum::ipc::Client::mServiceID private
Definition at line 160 of file client.hpp.
Referenced by callAsync(), callSync(), and start().
std::string vasum::ipc::Client::mSocketPath private
Definition at line 162 of file client.hpp.
Referenced by start().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/common/ipc/client.hpp
/home/dariusz/task/security-containers/common/ipc/client.cpp