Vasum: vasum::utils::CallbackGuard Class Reference
vasum::utils::CallbackGuard Class Reference
#include <callback-guard.hpp>
Classes
class SharedState
Public Types
typedef std::shared_ptr< void > Tracker
Public Member Functions
CallbackGuard ()
~CallbackGuard ()
Tracker spawn () const
long getTrackersCount () const
bool waitForTrackers (const unsigned int timeoutMs)
Private Member Functions
CallbackGuard (const CallbackGuard &)=delete
CallbackGuard & operator= (const CallbackGuard &)=delete
Private Attributes
std::shared_ptr< SharedState > mSharedState
Detailed Description
Callback guard. An utility class to control and/or monitor callback lifecycle.
Definition at line 39 of file callback-guard.hpp.
Member Typedef Documentation
typedef std::shared_ptr<void> vasum::utils::CallbackGuard::Tracker
Definition at line 41 of file callback-guard.hpp.
Constructor & Destructor Documentation
vasum::utils::CallbackGuard::CallbackGuard ()
Creates a guard.
Definition at line 101 of file callback-guard.cpp.
vasum::utils::CallbackGuard::~CallbackGuard ()
Waits for all trackers.
Definition at line 106 of file callback-guard.cpp.
References waitForTrackers().
vasum::utils::CallbackGuard::CallbackGuard (const CallbackGuard &) private delete
Member Function Documentation
long vasum::utils::CallbackGuard::getTrackersCount () const
Gets trackers count
Definition at line 119 of file callback-guard.cpp.
References mSharedState.
CallbackGuard& vasum::utils::CallbackGuard::operator= (const CallbackGuard &) private delete
CallbackGuard::Tracker vasum::utils::CallbackGuard::spawn () const
Creates a tracker.
Definition at line 114 of file callback-guard.cpp.
References mSharedState.
Referenced by vasum::utils::Glib::addTimerEvent(), vasum::InputMonitor::createGIOChannel(), and vasum::epoll::GlibDispatcher::GlibDispatcher().
bool vasum::utils::CallbackGuard::waitForTrackers (const unsigned int timeoutMs)
Wait for all trackers.
Definition at line 124 of file callback-guard.cpp.
References mSharedState.
Referenced by ~CallbackGuard().
Member Data Documentation
std::shared_ptr<SharedState> vasum::utils::CallbackGuard::mSharedState private
Definition at line 68 of file callback-guard.hpp.
Referenced by getTrackersCount(), spawn(), and waitForTrackers().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/common/utils/callback-guard.hpp
/home/dariusz/task/security-containers/common/utils/callback-guard.cpp