Vasum: vasum::utils::Glib Class Reference
vasum::utils::Glib Class Reference
#include <glib-loop.hpp>
Public Types
typedef std::function< bool()> OnTimerEventCallback
Static Public Member Functions
static void addTimerEvent (const unsigned int intervalMs, const OnTimerEventCallback &callback, const CallbackGuard &guard)
Static Private Member Functions
static gboolean onTimerEvent (gpointer data)
Detailed Description
Miscellaneous helpers for the Glib library
Definition at line 62 of file glib-loop.hpp.
Member Typedef Documentation
typedef std::function<bool()> vasum::utils::Glib::OnTimerEventCallback
A user provided function that will be called succesively after an interval has passed.
Return true if the callback is supposed to be called further, false if the callback is not to be called anymore and be destroyed.
Definition at line 70 of file glib-loop.hpp.
Member Function Documentation
void vasum::utils::Glib::addTimerEvent (const unsigned int intervalMs, const OnTimerEventCallback & callback, const CallbackGuard & guard) static
Adds a timer event to the glib main loop.
Definition at line 66 of file glib-loop.cpp.
References vasum::utils::createCallbackWrapper(), onTimerEvent(), and vasum::utils::CallbackGuard::spawn().
gboolean vasum::utils::Glib::onTimerEvent (gpointer data) static private
Definition at line 77 of file glib-loop.cpp.
References data.
Referenced by addTimerEvent().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/common/utils/glib-loop.hpp
/home/dariusz/task/security-containers/common/utils/glib-loop.cpp