Vasum: vasum::HostIPCConnection Class Reference
vasum::HostIPCConnection Class Reference
#include <host-ipc-connection.hpp>
Classes
class Method
class Signal
Public Member Functions
HostIPCConnection (ipc::epoll::EventPoll &eventPoll, ZonesManager *zm)
~HostIPCConnection ()
void start ()
void signalZoneConnectionState (const api::ConnectionState &connectionState)
Private Member Functions
void setLockQueueCallback (const Method< api::Void >::type &callback)
void setUnlockQueueCallback (const Method< api::Void >::type &callback)
void setGetZoneIdsCallback (const Method< api::ZoneIds >::type &callback)
void setGetZoneConnectionsCallback (const Method< api::Connections >::type &callback)
void setGetActiveZoneIdCallback (const Method< api::ZoneId >::type &callback)
void setGetZoneInfoCallback (const Method< const api::ZoneId, api::ZoneInfoOut >::type &callback)
void setSetNetdevAttrsCallback (const Method< const api::SetNetDevAttrsIn >::type &callback)
void setGetNetdevAttrsCallback (const Method< const api::GetNetDevAttrsIn, api::GetNetDevAttrs >::type &callback)
void setGetNetdevListCallback (const Method< const api::ZoneId, api::NetDevList >::type &callback)
void setCreateNetdevVethCallback (const Method< const api::CreateNetDevVethIn >::type &callback)
void setCreateNetdevMacvlanCallback (const Method< const api::CreateNetDevMacvlanIn >::type &callback)
void setCreateNetdevPhysCallback (const Method< const api::CreateNetDevPhysIn >::type &callback)
void setDestroyNetdevCallback (const Method< const api::DestroyNetDevIn >::type &callback)
void setDeleteNetdevIpAddressCallback (const Method< const api::DeleteNetdevIpAddressIn >::type &callback)
void setDeclareFileCallback (const Method< const api::DeclareFileIn, api::Declaration >::type &callback)
void setDeclareMountCallback (const Method< const api::DeclareMountIn, api::Declaration >::type &callback)
void setDeclareLinkCallback (const Method< const api::DeclareLinkIn, api::Declaration >::type &callback)
void setGetDeclarationsCallback (const Method< const api::ZoneId, api::Declarations >::type &callback)
void setRemoveDeclarationCallback (const Method< const api::RemoveDeclarationIn >::type &callback)
void setSetActiveZoneCallback (const Method< const api::ZoneId >::type &callback)
void setCreateZoneCallback (const Method< const api::CreateZoneIn >::type &callback)
void setDestroyZoneCallback (const Method< const api::ZoneId >::type &callback)
void setShutdownZoneCallback (const Method< const api::ZoneId >::type &callback)
void setStartZoneCallback (const Method< const api::ZoneId >::type &callback)
void setLockZoneCallback (const Method< const api::ZoneId >::type &callback)
void setUnlockZoneCallback (const Method< const api::ZoneId >::type &callback)
void setGrantDeviceCallback (const Method< const api::GrantDeviceIn >::type &callback)
void setRevokeDeviceCallback (const Method< const api::RevokeDeviceIn >::type &callback)
void setSwitchToDefaultCallback (const Method< api::Void >::type &callback)
void setCreateFileCallback (const Method< const api::CreateFileIn, api::CreateFileOut >::type &callback)
Private Attributes
std::unique_ptr< ipc::Service > mService
ZonesManager * mZonesManagerPtr
Detailed Description
Definition at line 38 of file host-ipc-connection.hpp.
Constructor & Destructor Documentation
vasum::HostIPCConnection::HostIPCConnection (ipc::epoll::EventPoll & eventPoll, ZonesManager * zm)
Definition at line 38 of file host-ipc-connection.cpp.
References vasum::ZonesManager::disconnectedCallback(), vasum::ZonesManager::handleCreateFileCall(), vasum::ZonesManager::handleCreateNetdevMacvlanCall(), vasum::ZonesManager::handleCreateNetdevPhysCall(), vasum::ZonesManager::handleCreateNetdevVethCall(), vasum::ZonesManager::handleCreateZoneCall(), vasum::ZonesManager::handleDeclareFileCall(), vasum::ZonesManager::handleDeclareLinkCall(), vasum::ZonesManager::handleDeclareMountCall(), vasum::ZonesManager::handleDeleteNetdevIpAddressCall(), vasum::ZonesManager::handleDestroyNetdevCall(), vasum::ZonesManager::handleDestroyZoneCall(), vasum::ZonesManager::handleGetActiveZoneIdCall(), vasum::ZonesManager::handleGetDeclarationsCall(), vasum::ZonesManager::handleGetNetdevAttrsCall(), vasum::ZonesManager::handleGetNetdevListCall(), vasum::ZonesManager::handleGetZoneIdsCall(), vasum::ZonesManager::handleGetZoneInfoCall(), vasum::ZonesManager::handleGrantDeviceCall(), vasum::ZonesManager::handleLockQueueCall(), vasum::ZonesManager::handleLockZoneCall(), vasum::ZonesManager::handleRemoveDeclarationCall(), vasum::ZonesManager::handleRevokeDeviceCall(), vasum::ZonesManager::handleSetActiveZoneCall(), vasum::ZonesManager::handleSetNetdevAttrsCall(), vasum::ZonesManager::handleShutdownZoneCall(), vasum::ZonesManager::handleStartZoneCall(), vasum::ZonesManager::handleSwitchToDefaultCall(), vasum::ZonesManager::handleUnlockQueueCall(), vasum::ZonesManager::handleUnlockZoneCall(), vasum::api::IPC_CONNECTION_PREFIX, mService, mZonesManagerPtr, setCreateFileCallback(), setCreateNetdevMacvlanCallback(), setCreateNetdevPhysCallback(), setCreateNetdevVethCallback(), setCreateZoneCallback(), setDeclareFileCallback(), setDeclareLinkCallback(), setDeclareMountCallback(), setDeleteNetdevIpAddressCallback(), setDestroyNetdevCallback(), setDestroyZoneCallback(), setGetActiveZoneIdCallback(), setGetDeclarationsCallback(), setGetNetdevAttrsCallback(), setGetNetdevListCallback(), setGetZoneIdsCallback(), setGetZoneInfoCallback(), setGrantDeviceCallback(), setLockQueueCallback(), setLockZoneCallback(), setRemoveDeclarationCallback(), setRevokeDeviceCallback(), setSetActiveZoneCallback(), setSetNetdevAttrsCallback(), setShutdownZoneCallback(), setStartZoneCallback(), setSwitchToDefaultCallback(), setUnlockQueueCallback(), and setUnlockZoneCallback().
vasum::HostIPCConnection::~HostIPCConnection ()
Definition at line 140 of file host-ipc-connection.cpp.
Member Function Documentation
void vasum::HostIPCConnection::setCreateFileCallback (const Method< const api::CreateFileIn, api::CreateFileOut >::type & callback) private
Definition at line 375 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_CREATE_FILE, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setCreateNetdevMacvlanCallback (const Method< const api::CreateNetDevMacvlanIn >::type & callback) private
Definition at line 223 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_CREATE_NETDEV_MACVLAN, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setCreateNetdevPhysCallback (const Method< const api::CreateNetDevPhysIn >::type & callback) private
Definition at line 231 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_CREATE_NETDEV_PHYS, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setCreateNetdevVethCallback (const Method< const api::CreateNetDevVethIn >::type & callback) private
Definition at line 215 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_CREATE_NETDEV_VETH, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setCreateZoneCallback (const Method< const api::CreateZoneIn >::type & callback) private
Definition at line 303 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_CREATE_ZONE, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setDeclareFileCallback (const Method< const api::DeclareFileIn, api::Declaration >::type & callback) private
Definition at line 255 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_DECLARE_FILE, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setDeclareLinkCallback (const Method< const api::DeclareLinkIn, api::Declaration >::type & callback) private
Definition at line 271 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_DECLARE_LINK, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setDeclareMountCallback (const Method< const api::DeclareMountIn, api::Declaration >::type & callback) private
Definition at line 263 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_DECLARE_MOUNT, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setDeleteNetdevIpAddressCallback (const Method< const api::DeleteNetdevIpAddressIn >::type & callback) private
Definition at line 247 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_DELETE_NETDEV_IP_ADDRESS, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setDestroyNetdevCallback (const Method< const api::DestroyNetDevIn >::type & callback) private
Definition at line 239 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_DESTROY_NETDEV, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setDestroyZoneCallback (const Method< const api::ZoneId >::type & callback) private
Definition at line 311 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_DESTROY_ZONE, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setGetActiveZoneIdCallback (const Method< api::ZoneId >::type & callback) private
Definition at line 175 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_GET_ACTIVE_ZONE_ID, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setGetDeclarationsCallback (const Method< const api::ZoneId, api::Declarations >::type & callback) private
Definition at line 279 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_GET_DECLARATIONS, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setGetNetdevAttrsCallback (const Method< const api::GetNetDevAttrsIn, api::GetNetDevAttrs >::type & callback) private
Definition at line 199 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_GET_NETDEV_ATTRS, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setGetNetdevListCallback (const Method< const api::ZoneId, api::NetDevList >::type & callback) private
Definition at line 207 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_GET_NETDEV_LIST, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setGetZoneConnectionsCallback (const Method< api::Connections >::type & callback) private
void vasum::HostIPCConnection::setGetZoneIdsCallback (const Method< api::ZoneIds >::type & callback) private
Definition at line 167 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_GET_ZONE_ID_LIST, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setGetZoneInfoCallback (const Method< const api::ZoneId, api::ZoneInfoOut >::type & callback) private
Definition at line 183 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_GET_ZONE_INFO, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setGrantDeviceCallback (const Method< const api::GrantDeviceIn >::type & callback) private
Definition at line 351 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_GRANT_DEVICE, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setLockQueueCallback (const Method< api::Void >::type & callback) private
Definition at line 151 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_LOCK_QUEUE, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setLockZoneCallback (const Method< const api::ZoneId >::type & callback) private
Definition at line 335 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_LOCK_ZONE, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setRemoveDeclarationCallback (const Method< const api::RemoveDeclarationIn >::type & callback) private
Definition at line 287 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_REMOVE_DECLARATION, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setRevokeDeviceCallback (const Method< const api::RevokeDeviceIn >::type & callback) private
Definition at line 359 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_REVOKE_DEVICE, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setSetActiveZoneCallback (const Method< const api::ZoneId >::type & callback) private
Definition at line 295 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_SET_ACTIVE_ZONE, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setSetNetdevAttrsCallback (const Method< const api::SetNetDevAttrsIn >::type & callback) private
Definition at line 191 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_SET_NETDEV_ATTRS, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setShutdownZoneCallback (const Method< const api::ZoneId >::type & callback) private
Definition at line 319 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_SHUTDOWN_ZONE, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setStartZoneCallback (const Method< const api::ZoneId >::type & callback) private
Definition at line 327 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_START_ZONE, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setSwitchToDefaultCallback (const Method< api::Void >::type & callback) private
Definition at line 367 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_SWITCH_TO_DEFAULT, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setUnlockQueueCallback (const Method< api::Void >::type & callback) private
Definition at line 159 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_UNLOCK_QUEUE, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::setUnlockZoneCallback (const Method< const api::ZoneId >::type & callback) private
Definition at line 343 of file host-ipc-connection.cpp.
References vasum::api::ipc::METHOD_UNLOCK_ZONE, and mService.
Referenced by HostIPCConnection().
void vasum::HostIPCConnection::signalZoneConnectionState (const api::ConnectionState & connectionState)
void vasum::HostIPCConnection::start ()
Definition at line 144 of file host-ipc-connection.cpp.
References mService.
Referenced by vasum::ZonesManager::ZonesManager().
Member Data Documentation
std::unique_ptr<ipc::Service> vasum::HostIPCConnection::mService private
Definition at line 89 of file host-ipc-connection.hpp.
Referenced by HostIPCConnection(), setCreateFileCallback(), setCreateNetdevMacvlanCallback(), setCreateNetdevPhysCallback(), setCreateNetdevVethCallback(), setCreateZoneCallback(), setDeclareFileCallback(), setDeclareLinkCallback(), setDeclareMountCallback(), setDeleteNetdevIpAddressCallback(), setDestroyNetdevCallback(), setDestroyZoneCallback(), setGetActiveZoneIdCallback(), setGetDeclarationsCallback(), setGetNetdevAttrsCallback(), setGetNetdevListCallback(), setGetZoneIdsCallback(), setGetZoneInfoCallback(), setGrantDeviceCallback(), setLockQueueCallback(), setLockZoneCallback(), setRemoveDeclarationCallback(), setRevokeDeviceCallback(), setSetActiveZoneCallback(), setSetNetdevAttrsCallback(), setShutdownZoneCallback(), setStartZoneCallback(), setSwitchToDefaultCallback(), setUnlockQueueCallback(), setUnlockZoneCallback(), and start().
ZonesManager* vasum::HostIPCConnection::mZonesManagerPtr private
Definition at line 90 of file host-ipc-connection.hpp.
Referenced by HostIPCConnection().
The documentation for this class was generated from the following files:
/home/lkostyra/eclipse_workspaces/code/vasum/server/host-ipc-connection.hpp
/home/lkostyra/eclipse_workspaces/code/vasum/server/host-ipc-connection.cpp