Vasum: vasum::ipc::Service Class Reference
vasum::ipc::Service Class Reference
#include <service.hpp>
Public Member Functions
Service (epoll::EventPoll &eventPoll, const std::string &path, const PeerCallback &addPeerCallback=nullptr, const PeerCallback &removePeerCallback=nullptr)
~Service ()
Service (const Service &)=delete
Service & operator= (const Service &)=delete
void start ()
bool isStarted ()
void stop ()
void setNewPeerCallback (const PeerCallback &newPeerCallback)
void setRemovedPeerCallback (const PeerCallback &removedPeerCallback)
template<typename SentDataType , typename ReceivedDataType >
void setMethodHandler (const MethodID methodID, const typename MethodHandler< SentDataType, ReceivedDataType >::type &method)
template<typename ReceivedDataType >
void setSignalHandler (const MethodID methodID, const typename SignalHandler< ReceivedDataType >::type &handler)
void removeMethod (const MethodID methodID)
template<typename SentDataType , typename ReceivedDataType >
std::shared_ptr< ReceivedDataType > callSync (const MethodID methodID, const PeerID peerID, const std::shared_ptr< SentDataType > &data, unsigned int timeoutMS=500)
template<typename SentDataType , typename ReceivedDataType >
void callAsync (const MethodID methodID, const PeerID peerID, const std::shared_ptr< SentDataType > &data, const typename ResultHandler< ReceivedDataType >::type &resultCallback)
template<typename SentDataType >
void signal (const MethodID methodID, const std::shared_ptr< SentDataType > &data)
Private Member Functions
void handle (const FileDescriptor fd, const epoll::Events pollEvents)
Private Attributes
epoll::EventPoll & mEventPoll
Processor mProcessor
Acceptor mAcceptor
Detailed Description
This class wraps communication via UX sockets. It uses serialization mechanism from libConfig.
For message format
See Also
ipc::Processor
Definition at line 47 of file service.hpp.
Constructor & Destructor Documentation
vasum::ipc::Service::Service (epoll::EventPoll & eventPoll, const std::string & path, const PeerCallback & addPeerCallback = nullptr, const PeerCallback & removePeerCallback = nullptr)
Parameters
eventPoll event poll
path path to the socket
Definition at line 36 of file service.cpp.
References setNewPeerCallback(), and setRemovedPeerCallback().
vasum::ipc::Service::~Service ()
Definition at line 50 of file service.cpp.
References stop().
vasum::ipc::Service::Service (const Service &) delete
Member Function Documentation
template<typename SentDataType , typename ReceivedDataType > void vasum::ipc::Service::callAsync (const MethodID methodID, const PeerID peerID, const std::shared_ptr< SentDataType > & data, const typename ResultHandler< ReceivedDataType >::type & resultCallback)
Asynchronous method call. The return callback will be called on return data arrival. It will be run in the PROCESSOR thread.
Parameters
methodID API dependent id of the method
data data to send
resultCallback callback for result serialization and handling
Definition at line 201 of file service.hpp.
References vasum::ipc::Processor::callAsync(), data, and mProcessor.
template<typename SentDataType , typename ReceivedDataType > std::shared_ptr< ReceivedDataType > vasum::ipc::Service::callSync (const MethodID methodID, const PeerID peerID, const std::shared_ptr< SentDataType > & data, unsigned int timeoutMS = 500)
Synchronous method call.
Parameters
methodID API dependent id of the method
data data to send
Returns
result data
Definition at line 189 of file service.hpp.
References vasum::ipc::Processor::callSync(), data, and mProcessor.
void vasum::ipc::Service::handle (const FileDescriptor fd, const epoll::Events pollEvents) private
Definition at line 93 of file service.cpp.
References vasum::ipc::Processor::handleInput(), vasum::ipc::Processor::handleLostConnection(), isStarted(), and mProcessor.
Referenced by setNewPeerCallback().
bool vasum::ipc::Service::isStarted ()
Returns
is the communication thread running
Definition at line 77 of file service.cpp.
References vasum::ipc::Processor::isStarted(), and mProcessor.
Referenced by handle().
Service& vasum::ipc::Service::operator= (const Service &) delete
void vasum::ipc::Service::removeMethod (const MethodID methodID)
Removes the callback
Parameters
methodID API dependent id of the method
Definition at line 140 of file service.cpp.
References mProcessor, and vasum::ipc::Processor::removeMethod().
template<typename SentDataType , typename ReceivedDataType > void vasum::ipc::Service::setMethodHandler (const MethodID methodID, const typename MethodHandler< SentDataType, ReceivedDataType >::type & method)
Saves the callback connected to the method id. When a message with the given method id is received the data will be parsed and passed to this callback.
Parameters
methodID API dependent id of the method
method method handling implementation
Definition at line 173 of file service.hpp.
References mProcessor, and vasum::ipc::Processor::setMethodHandler().
void vasum::ipc::Service::setNewPeerCallback (const PeerCallback & newPeerCallback)
Set the callback called for each new connection to a peer
Parameters
newPeerCallback the callback
Definition at line 113 of file service.cpp.
References vasum::epoll::EventPoll::addFD(), handle(), mEventPoll, mProcessor, and vasum::ipc::Processor::setNewPeerCallback().
Referenced by Service().
void vasum::ipc::Service::setRemovedPeerCallback (const PeerCallback & removedPeerCallback)
Set the callback called when connection to a peer is lost
Parameters
removedPeerCallback the callback
Definition at line 128 of file service.cpp.
References mEventPoll, mProcessor, vasum::epoll::EventPoll::removeFD(), and vasum::ipc::Processor::setRemovedPeerCallback().
Referenced by Service().
template<typename ReceivedDataType > void vasum::ipc::Service::setSignalHandler (const MethodID methodID, const typename SignalHandler< ReceivedDataType >::type & handler)
Saves the callback connected to the method id. When a message with the given method id is received the data will be parsed and passed to this callback.
Parameters
methodID API dependent id of the method
handler handling implementation
Template Parameters
ReceivedDataType data type to serialize
Definition at line 181 of file service.hpp.
References mProcessor, and vasum::ipc::Processor::setSignalHandler().
template<typename SentDataType > void vasum::ipc::Service::signal (const MethodID methodID, const std::shared_ptr< SentDataType > & data)
Send a signal to the peer. There is no return value from the peer Sends any data only if a peer registered this a signal
Parameters
methodID API dependent id of the method
data data to sent
Template Parameters
SentDataType data type to send
Definition at line 215 of file service.hpp.
References data, mProcessor, and vasum::ipc::Processor::signal().
void vasum::ipc::Service::start ()
Starts processing
Definition at line 60 of file service.cpp.
References vasum::epoll::EventPoll::addFD(), vasum::ipc::Acceptor::getConnectionFD(), vasum::ipc::Processor::getEventFD(), vasum::ipc::Acceptor::handleConnection(), vasum::ipc::Processor::handleEvent(), vasum::ipc::Processor::isStarted(), mAcceptor, mEventPoll, mProcessor, and vasum::ipc::Processor::start().
void vasum::ipc::Service::stop ()
Stops all working threads
Definition at line 82 of file service.cpp.
References vasum::ipc::Acceptor::getConnectionFD(), vasum::ipc::Processor::getEventFD(), vasum::ipc::Processor::isStarted(), mAcceptor, mEventPoll, mProcessor, vasum::epoll::EventPoll::removeFD(), and vasum::ipc::Processor::stop().
Referenced by ~Service().
Member Data Documentation
Acceptor vasum::ipc::Service::mAcceptor private
Definition at line 166 of file service.hpp.
Referenced by start(), and stop().
epoll::EventPoll& vasum::ipc::Service::mEventPoll private
Definition at line 164 of file service.hpp.
Referenced by setNewPeerCallback(), setRemovedPeerCallback(), start(), and stop().
Processor vasum::ipc::Service::mProcessor private
Definition at line 165 of file service.hpp.
Referenced by callAsync(), callSync(), handle(), isStarted(), removeMethod(), setMethodHandler(), setNewPeerCallback(), setRemovedPeerCallback(), setSignalHandler(), signal(), start(), and stop().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/common/ipc/service.hpp
/home/dariusz/task/security-containers/common/ipc/service.cpp