Vasum: vasum::epoll::EventPoll Class Reference
vasum::epoll::EventPoll Class Reference
#include <event-poll.hpp>
Public Types
typedef std::function< void(int
fd, Events events)> Callback
Public Member Functions
EventPoll ()
~EventPoll ()
int getPollFD () const
void addFD (const int fd, const Events events, Callback &&callback)
void modifyFD (const int fd, const Events events)
void removeFD (const int fd)
bool dispatchIteration (const int timeoutMs)
Private Types
typedef std::recursive_mutex Mutex
Private Member Functions
bool addFDInternal (const int fd, const Events events)
bool modifyFDInternal (const int fd, const Events events)
void removeFDInternal (const int fd)
Private Attributes
const int mPollFD
Mutex mMutex
std::unordered_map< int,
std::shared_ptr< Callback > > mCallbacks
Detailed Description
Definition at line 38 of file event-poll.hpp.
Member Typedef Documentation
typedef std::function<void(int fd, Events events)> vasum::epoll::EventPoll::Callback
Definition at line 40 of file event-poll.hpp.
typedef std::recursive_mutex vasum::epoll::EventPoll::Mutex private
Definition at line 60 of file event-poll.hpp.
Constructor & Destructor Documentation
vasum::epoll::EventPoll::EventPoll ()
Definition at line 39 of file event-poll.cpp.
References vasum::getSystemErrorMessage(), and mPollFD.
vasum::epoll::EventPoll::~EventPoll ()
Definition at line 48 of file event-poll.cpp.
References vasum::utils::close(), mCallbacks, and mPollFD.
Member Function Documentation
void vasum::epoll::EventPoll::addFD (const int fd, const Events events, Callback && callback)
Definition at line 65 of file event-poll.cpp.
References addFDInternal(), mCallbacks, and mMutex.
Referenced by vasum::ipc::Client::setNewPeerCallback(), vasum::ipc::Service::setNewPeerCallback(), vasum::ipc::Client::start(), vasum::ipc::Service::start(), and vasum::epoll::ThreadDispatcher::ThreadDispatcher().
bool vasum::epoll::EventPoll::addFDInternal (const int fd, const Events events) private
Definition at line 142 of file event-poll.cpp.
References vasum::getSystemErrorMessage(), and mPollFD.
Referenced by addFD().
bool vasum::epoll::EventPoll::dispatchIteration (const int timeoutMs)
Dispatch at most one signalled FD
Parameters
timeoutMs how long should wait in case of no pending events (0 - return immediately, -1 - wait forever)
Returns
false on timeout
Definition at line 104 of file event-poll.cpp.
References vasum::epoll::eventsToString(), vasum::getSystemErrorMessage(), mCallbacks, mMutex, and mPollFD.
Referenced by vasum::epoll::GlibDispatcher::GlibDispatcher(), and vasum::epoll::ThreadDispatcher::ThreadDispatcher().
int vasum::epoll::EventPoll::getPollFD () const
Definition at line 60 of file event-poll.cpp.
References mPollFD.
Referenced by vasum::epoll::GlibDispatcher::GlibDispatcher().
void vasum::epoll::EventPoll::modifyFD (const int fd, const Events events)
Definition at line 82 of file event-poll.cpp.
References modifyFDInternal().
bool vasum::epoll::EventPoll::modifyFDInternal (const int fd, const Events events) private
Definition at line 156 of file event-poll.cpp.
References vasum::getSystemErrorMessage(), and mPollFD.
Referenced by modifyFD().
void vasum::epoll::EventPoll::removeFD (const int fd)
Definition at line 90 of file event-poll.cpp.
References mCallbacks, mMutex, and removeFDInternal().
Referenced by vasum::ipc::Client::setRemovedPeerCallback(), vasum::ipc::Service::setRemovedPeerCallback(), vasum::ipc::Client::stop(), vasum::ipc::Service::stop(), and vasum::epoll::ThreadDispatcher::~ThreadDispatcher().
void vasum::epoll::EventPoll::removeFDInternal (const int fd) private
Definition at line 170 of file event-poll.cpp.
References vasum::getSystemErrorMessage(), and mPollFD.
Referenced by removeFD().
Member Data Documentation
std::unordered_map<int, std::shared_ptr<Callback> > vasum::epoll::EventPoll::mCallbacks private
Definition at line 64 of file event-poll.hpp.
Referenced by addFD(), dispatchIteration(), removeFD(), and ~EventPoll().
Mutex vasum::epoll::EventPoll::mMutex private
Definition at line 63 of file event-poll.hpp.
Referenced by addFD(), dispatchIteration(), and removeFD().
const int vasum::epoll::EventPoll::mPollFD private
Definition at line 62 of file event-poll.hpp.
Referenced by addFDInternal(), dispatchIteration(), EventPoll(), getPollFD(), modifyFDInternal(), removeFDInternal(), and ~EventPoll().
The documentation for this class was generated from the following files:
/home/dariusz/task/security-containers/common/epoll/event-poll.hpp
/home/dariusz/task/security-containers/common/epoll/event-poll.cpp