Vasum: vasum::Zone Class Reference
vasum::Zone Class Reference
#include <zone.hpp>
Public Types
typedef netdev::Attrs NetdevAttrs
typedef std::function< void(bool
succeeded)> StartAsyncResultCallback
Public Member Functions
Zone (const std::string &zoneId, const std::string &zonesPath, const std::string &zoneTemplatePath, const std::string &dbPath, const std::string &zoneTemplateDir, const std::string &baseRunMountPointPath)
Zone (const Zone &)=delete
Zone & operator= (const Zone &)=delete
~Zone ()
const std::string & getId () const
int getPrivilege () const
void restore ()
void start ()
void stop (bool saveState)
bool activateVT ()
void goForeground ()
void goBackground ()
void setDetachOnExit ()
void setDestroyOnExit ()
bool isRunning ()
bool isStopped ()
void suspend ()
void resume ()
bool isPaused ()
bool isSwitchToDefaultAfterTimeoutAllowed () const
int getVT () const
int createFile (const std::string &path, const std::int32_t flags, const std::int32_t mode)
std::string declareFile (const int32_t &type, const std::string &path, const int32_t &flags, const int32_t &mode)
std::string declareMount (const std::string &source, const std::string &target, const std::string &type, const int64_t &flags, const std::string &data)
std::string declareLink (const std::string &source, const std::string &target)
std::vector< std::string > getDeclarations () const
void removeDeclaration (const std::string &declarationId)
std::string getRootPath () const
void createNetdevVeth (const std::string &zoneDev, const std::string &hostDev)
void createNetdevMacvlan (const std::string &zoneDev, const std::string &hostDev, const uint32_t &mode)
void moveNetdev (const std::string &devId)
void destroyNetdev (const std::string &devId)
void setNetdevAttrs (const std::string &netdev, const NetdevAttrs &attrs)
NetdevAttrs getNetdevAttrs (const std::string &netdev)
std::vector< std::string > getNetdevList ()
void deleteNetdevIpAddress (const std::string &netdev, const std::string &ip)
void setSchedulerLevel (SchedulerLevel sched)
std::int64_t getSchedulerQuota ()
Private Member Functions
void onNameLostCallback ()
void saveDynamicConfig ()
void updateRequestedState (const std::string &state)
void setSchedulerParams (std::uint64_t cpuShares, std::uint64_t vcpuPeriod, std::int64_t vcpuQuota)
Private Attributes
ZoneConfig mConfig
ZoneDynamicConfig mDynamicConfig
std::unique_ptr< ZoneProvision > mProvision
std::recursive_mutex mReconnectMutex
std::string mRunMountPoint
std::string mRootPath
std::string mDbPath
lxc::LxcZone mZone
const std::string mId
bool mDetachOnExit
bool mDestroyOnExit
Detailed Description
Definition at line 50 of file zone.hpp.
Member Typedef Documentation
typedef netdev::Attrs vasum::Zone::NetdevAttrs
Definition at line 53 of file zone.hpp.
typedef std::function<void(bool succeeded)> vasum::Zone::StartAsyncResultCallback
Definition at line 74 of file zone.hpp.
Constructor & Destructor Documentation
vasum::Zone::Zone (const std::string & zoneId, const std::string & zonesPath, const std::string & zoneTemplatePath, const std::string & dbPath, const std::string & zoneTemplateDir, const std::string & baseRunMountPointPath)
Zone constructor
Parameters
zoneId zone id
zonesPath directory where zones are defined (configs, rootfs etc)
zoneTemplatePath path for zones config template
dbPath path to dynamic config db file
zoneTemplateDir directory where templates are stored
baseRunMountPointPath base directory for run mount point
Definition at line 63 of file zone.cpp.
References utils::CArrayBuilder< T >::add(), utils::CArrayBuilder< T >::c_array(), vasum::lxc::LxcZone::create(), utils::getAbsolutePath(), vasum::getZoneDbPrefix(), vasum::ZoneDynamicConfig::ipv4, vasum::ZoneDynamicConfig::ipv4Gateway, vasum::lxc::LxcZone::isDefined(), mConfig, mDynamicConfig, mId, mProvision, mRootPath, mRunMountPoint, mZone, vasum::ZoneDynamicConfig::runMountPoint, vasum::ZoneConfig::validLinkPrefixes, vasum::ZoneDynamicConfig::vt, and vasum::ZoneConfig::zoneTemplate.
vasum::Zone::Zone (const Zone &) delete
vasum::Zone::~Zone ()
Definition at line 114 of file zone.cpp.
References vasum::lxc::LxcZone::destroy(), mDestroyOnExit, mDetachOnExit, mId, mZone, and vasum::lxc::LxcZone::stop().
Member Function Documentation
bool vasum::Zone::activateVT ()
Activate this zone's VT
Returns
Was activation successful?
Definition at line 269 of file zone.cpp.
References utils::activateVT(), mDynamicConfig, mReconnectMutex, and vasum::ZoneDynamicConfig::vt.
Referenced by vasum::ZonesManager::focusInternal().
int vasum::Zone::createFile (const std::string & path, const std::int32_t flags, const std::int32_t mode)
Create file inside zone, return its fd
Parameters
path Path where the file should be created
flags Flags used when opening the file. See common/lxc/zone.hpp for more info.
mode Permissions with which file is created
Returns
Created files fd
Definition at line 380 of file zone.cpp.
References vasum::lxc::LxcZone::createFile(), and mZone.
Referenced by vasum::ZonesManager::handleCreateFileCall().
void vasum::Zone::createNetdevMacvlan (const std::string & zoneDev, const std::string & hostDev, const uint32_t & mode)
Create macvlan network device
Definition at line 287 of file zone.cpp.
References vasum::netdev::createMacvlan(), vasum::lxc::LxcZone::getInitPid(), mReconnectMutex, and mZone.
Referenced by vasum::ZonesManager::handleCreateNetdevMacvlanCall().
void vasum::Zone::createNetdevVeth (const std::string & zoneDev, const std::string & hostDev)
Create veth network device
Definition at line 280 of file zone.cpp.
References vasum::netdev::createVeth(), vasum::lxc::LxcZone::getInitPid(), mReconnectMutex, and mZone.
Referenced by vasum::ZonesManager::handleCreateNetdevVethCall().
std::string vasum::Zone::declareFile (const int32_t & type, const std::string & path, const int32_t & flags, const int32_t & mode)
Declare file, directory or pipe that will be created while zone startup
Definition at line 389 of file zone.cpp.
References mProvision.
Referenced by vasum::ZonesManager::handleDeclareFileCall().
std::string vasum::Zone::declareLink (const std::string & source, const std::string & target)
Declare link that will be created while zone startup
Definition at line 406 of file zone.cpp.
References mProvision.
Referenced by vasum::ZonesManager::handleDeclareLinkCall().
std::string vasum::Zone::declareMount (const std::string & source, const std::string & target, const std::string & type, const int64_t & flags, const std::string & data)
Declare mount that will be created while zone startup
Definition at line 397 of file zone.cpp.
References mProvision.
Referenced by vasum::ZonesManager::handleDeclareMountCall().
void vasum::Zone::deleteNetdevIpAddress (const std::string & netdev, const std::string & ip)
Remove ipv4/ipv6 address from network device
Definition at line 440 of file zone.cpp.
References vasum::netdev::deleteIpAddress(), vasum::lxc::LxcZone::getInitPid(), mReconnectMutex, and mZone.
Referenced by vasum::ZonesManager::handleDeleteNetdevIpAddressCall().
void vasum::Zone::destroyNetdev (const std::string & devId)
Destroy network device in zone
Definition at line 301 of file zone.cpp.
References vasum::netdev::destroyNetdev(), vasum::lxc::LxcZone::getInitPid(), mReconnectMutex, and mZone.
Referenced by vasum::ZonesManager::handleDestroyNetdevCall().
std::vector< std::string > vasum::Zone::getDeclarations () const
Gets all declarations
Definition at line 412 of file zone.cpp.
References mProvision.
Referenced by vasum::ZonesManager::handleGetDeclarationsCall().
const std::string & vasum::Zone::getId () const
Get the zone id
Definition at line 137 of file zone.cpp.
References mId, and mReconnectMutex.
Referenced by vasum::ZonesManager::focusInternal(), and vasum::ZonesManager::handleGetZoneInfoCall().
Zone::NetdevAttrs vasum::Zone::getNetdevAttrs (const std::string & netdev)
Get network device attributes
Definition at line 428 of file zone.cpp.
References vasum::netdev::getAttrs(), vasum::lxc::LxcZone::getInitPid(), mReconnectMutex, and mZone.
Referenced by vasum::ZonesManager::handleGetNetdevAttrsCall().
std::vector< std::string > vasum::Zone::getNetdevList ()
Get network device list
Definition at line 434 of file zone.cpp.
References vasum::lxc::LxcZone::getInitPid(), vasum::netdev::listNetdev(), mReconnectMutex, and mZone.
Referenced by vasum::ZonesManager::handleGetNetdevListCall().
int vasum::Zone::getPrivilege () const
Get the zone privilege
Definition at line 143 of file zone.cpp.
References mConfig, and vasum::ZoneConfig::privilege.
std::string vasum::Zone::getRootPath () const
Get zone root path
Definition at line 264 of file zone.cpp.
References mRootPath.
Referenced by vasum::ZonesManager::handleGetZoneInfoCall().
std::int64_t vasum::Zone::getSchedulerQuota ()
Returns
Scheduler CFS quota, TODO: this function is only for UNIT TESTS
Definition at line 446 of file zone.cpp.
References vasum::lxc::getCgroup(), and mId.
int vasum::Zone::getVT () const
Get id of VT
Definition at line 258 of file zone.cpp.
References mDynamicConfig, mReconnectMutex, and vasum::ZoneDynamicConfig::vt.
Referenced by vasum::ZonesManager::handleGetZoneInfoCall().
void vasum::Zone::goBackground ()
Setup this zone to be put in the background. I.e. set appropriate scheduler level.
Definition at line 313 of file zone.cpp.
References vasum::BACKGROUND, mReconnectMutex, and setSchedulerLevel().
Referenced by vasum::ZonesManager::handleLockZoneCall().
void vasum::Zone::goForeground ()
Setup this zone to be put in the foreground. I.e. set appropriate scheduler level.
Definition at line 307 of file zone.cpp.
References vasum::FOREGROUND, mReconnectMutex, and setSchedulerLevel().
Referenced by start(), and stop().
bool vasum::Zone::isPaused ()
Returns
Is the zone in a paused state?
Definition at line 369 of file zone.cpp.
References vasum::lxc::LxcZone::FROZEN, vasum::lxc::LxcZone::getState(), mReconnectMutex, and mZone.
Referenced by vasum::ZonesManager::handleGetZoneInfoCall(), vasum::ZonesManager::handleGrantDeviceCall(), vasum::ZonesManager::handleRevokeDeviceCall(), vasum::ZonesManager::handleUnlockZoneCall(), and vasum::ZonesManager::isPaused().
bool vasum::Zone::isRunning ()
Returns
Is the zone running?
Definition at line 331 of file zone.cpp.
References vasum::lxc::LxcZone::getState(), mReconnectMutex, mZone, and vasum::lxc::LxcZone::RUNNING.
Referenced by vasum::ZonesManager::focusInternal(), vasum::ZonesManager::handleGetZoneInfoCall(), vasum::ZonesManager::handleGrantDeviceCall(), vasum::ZonesManager::handleLockZoneCall(), vasum::ZonesManager::handleRevokeDeviceCall(), vasum::ZonesManager::isRunning(), setSchedulerLevel(), start(), and stop().
bool vasum::Zone::isStopped ()
Check if the zone is stopped. It's NOT equivalent to !isRunning, because it checks different internal zone states. There are other states, (e.g. paused) when the zone isn't running nor stopped.
Returns
Is the zone stopped?
Definition at line 337 of file zone.cpp.
References vasum::lxc::LxcZone::getState(), mReconnectMutex, mZone, and vasum::lxc::LxcZone::STOPPED.
Referenced by vasum::ZonesManager::handleGetZoneInfoCall(), vasum::ZonesManager::isStopped(), and stop().
bool vasum::Zone::isSwitchToDefaultAfterTimeoutAllowed () const
Returns
Is switching to default zone after timeout allowed?
Definition at line 375 of file zone.cpp.
References mConfig, and vasum::ZoneConfig::switchToDefaultAfterTimeout.
void vasum::Zone::moveNetdev (const std::string & devId)
Move network device to zone
Definition at line 295 of file zone.cpp.
References vasum::lxc::LxcZone::getInitPid(), vasum::netdev::movePhys(), mReconnectMutex, and mZone.
Referenced by vasum::ZonesManager::handleCreateNetdevPhysCall().
void vasum::Zone::onNameLostCallback () private
Zone& vasum::Zone::operator= (const Zone &) delete
void vasum::Zone::removeDeclaration (const std::string & declarationId)
Remove declaration
Definition at line 417 of file zone.cpp.
References mProvision.
Referenced by vasum::ZonesManager::handleRemoveDeclarationCall().
void vasum::Zone::restore ()
Restore zone to the previous state
Definition at line 163 of file zone.cpp.
References mDynamicConfig, mId, mReconnectMutex, vasum::ZoneDynamicConfig::requestedState, start(), and suspend().
void vasum::Zone::resume ()
Resume zone.
Definition at line 356 of file zone.cpp.
References mId, mReconnectMutex, mZone, vasum::lxc::LxcZone::unfreeze(), and updateRequestedState().
Referenced by vasum::ZonesManager::handleUnlockZoneCall().
void vasum::Zone::saveDynamicConfig () private
Definition at line 148 of file zone.cpp.
References vasum::getZoneDbPrefix(), mDbPath, mDynamicConfig, and mId.
Referenced by updateRequestedState().
void vasum::Zone::setDestroyOnExit ()
Set if zone should be destroyed on exit.
Definition at line 325 of file zone.cpp.
References mDestroyOnExit, and mReconnectMutex.
void vasum::Zone::setDetachOnExit ()
Set if zone should be detached on exit.
Definition at line 319 of file zone.cpp.
References mDetachOnExit, and mReconnectMutex.
void vasum::Zone::setNetdevAttrs (const std::string & netdev, const NetdevAttrs & attrs)
Set network device attributes
Definition at line 422 of file zone.cpp.
References vasum::lxc::LxcZone::getInitPid(), mReconnectMutex, mZone, and vasum::netdev::setAttrs().
Referenced by vasum::ZonesManager::handleSetNetdevAttrsCall().
void vasum::Zone::setSchedulerLevel (SchedulerLevel sched)
Sets the zones scheduler CFS quota.
Definition at line 456 of file zone.cpp.
References vasum::BACKGROUND, vasum::ZoneConfig::cpuQuotaBackground, vasum::ZoneConfig::cpuQuotaForeground, vasum::FOREGROUND, isRunning(), mConfig, mId, and setSchedulerParams().
Referenced by goBackground(), and goForeground().
void vasum::Zone::setSchedulerParams (std::uint64_t cpuShares, std::uint64_t vcpuPeriod, std::int64_t vcpuQuota) private
Definition at line 478 of file zone.cpp.
References mId, and vasum::lxc::setCgroup().
Referenced by setSchedulerLevel().
void vasum::Zone::start ()
Boot the zone to the background.
Definition at line 184 of file zone.cpp.
References utils::CArrayBuilder< T >::add(), utils::CArrayBuilder< T >::c_array(), utils::CArrayBuilder< T >::empty(), goForeground(), vasum::ZoneConfig::initWithArgs, isRunning(), mConfig, mDynamicConfig, mId, mProvision, mReconnectMutex, mZone, vasum::lxc::LxcZone::start(), updateRequestedState(), and vasum::ZoneDynamicConfig::vt.
Referenced by restore().
void vasum::Zone::stop (bool saveState)
Try to shutdown the zone, if failed, destroy it.
Parameters
saveState save zone's state
Definition at line 227 of file zone.cpp.
References goForeground(), isRunning(), isStopped(), mConfig, mId, mProvision, mReconnectMutex, mZone, vasum::lxc::LxcZone::shutdown(), vasum::ZoneConfig::shutdownTimeout, vasum::lxc::LxcZone::stop(), and updateRequestedState().
void vasum::Zone::suspend ()
Suspends an active zone, the process is frozen without further access to CPU resources and I/O, but the memory used by the zone at the hypervisor level will stay allocated
Definition at line 343 of file zone.cpp.
References vasum::lxc::LxcZone::freeze(), mId, mReconnectMutex, mZone, and updateRequestedState().
Referenced by vasum::ZonesManager::handleLockZoneCall(), and restore().
void vasum::Zone::updateRequestedState (const std::string & state) private
Definition at line 153 of file zone.cpp.
References mDynamicConfig, mId, vasum::ZoneDynamicConfig::requestedState, and saveDynamicConfig().
Referenced by resume(), start(), stop(), and suspend().
Member Data Documentation
ZoneConfig vasum::Zone::mConfig private
Definition at line 275 of file zone.hpp.
Referenced by getPrivilege(), isSwitchToDefaultAfterTimeoutAllowed(), setSchedulerLevel(), start(), stop(), and Zone().
std::string vasum::Zone::mDbPath private
Definition at line 281 of file zone.hpp.
Referenced by saveDynamicConfig().
bool vasum::Zone::mDestroyOnExit private
Definition at line 285 of file zone.hpp.
Referenced by setDestroyOnExit(), and ~Zone().
bool vasum::Zone::mDetachOnExit private
Definition at line 284 of file zone.hpp.
Referenced by setDetachOnExit(), and ~Zone().
ZoneDynamicConfig vasum::Zone::mDynamicConfig private
Definition at line 276 of file zone.hpp.
Referenced by activateVT(), getVT(), restore(), saveDynamicConfig(), start(), updateRequestedState(), and Zone().
const std::string vasum::Zone::mId private
Definition at line 283 of file zone.hpp.
Referenced by getId(), getSchedulerQuota(), restore(), resume(), saveDynamicConfig(), setSchedulerLevel(), setSchedulerParams(), start(), stop(), suspend(), updateRequestedState(), Zone(), and ~Zone().
std::unique_ptr<ZoneProvision> vasum::Zone::mProvision private
Definition at line 277 of file zone.hpp.
Referenced by declareFile(), declareLink(), declareMount(), getDeclarations(), removeDeclaration(), start(), stop(), and Zone().
std::recursive_mutex vasum::Zone::mReconnectMutex mutable private
Definition at line 278 of file zone.hpp.
Referenced by activateVT(), createNetdevMacvlan(), createNetdevVeth(), deleteNetdevIpAddress(), destroyNetdev(), getId(), getNetdevAttrs(), getNetdevList(), getVT(), goBackground(), goForeground(), isPaused(), isRunning(), isStopped(), moveNetdev(), restore(), resume(), setDestroyOnExit(), setDetachOnExit(), setNetdevAttrs(), start(), stop(), and suspend().
std::string vasum::Zone::mRootPath private
Definition at line 280 of file zone.hpp.
Referenced by getRootPath(), and Zone().
std::string vasum::Zone::mRunMountPoint private
Definition at line 279 of file zone.hpp.
Referenced by Zone().
lxc::LxcZone vasum::Zone::mZone private
Definition at line 282 of file zone.hpp.
Referenced by createFile(), createNetdevMacvlan(), createNetdevVeth(), deleteNetdevIpAddress(), destroyNetdev(), getNetdevAttrs(), getNetdevList(), isPaused(), isRunning(), isStopped(), moveNetdev(), resume(), setNetdevAttrs(), start(), stop(), suspend(), Zone(), and ~Zone().
The documentation for this class was generated from the following files:
/home/lkostyra/eclipse_workspaces/code/vasum/server/zone.hpp
/home/lkostyra/eclipse_workspaces/code/vasum/server/zone.cpp