Vasum: vasum::HostDbusConnection Class Reference
vasum::HostDbusConnection Class Reference
#include <host-dbus-connection.hpp>
Public Types
typedef std::function< void(const
std::string &target, const
std::string &targetBusName,
const std::string
&targetObjectPath, const
std::string &targetInterface,
const std::string
&targetMethod, GVariant
*parameters,
dbus::MethodResultBuilder::Pointer
result)> ProxyCallCallback
Public Member Functions
HostDbusConnection (ZonesManager *zm)
~HostDbusConnection ()
void setProxyCallCallback (const ProxyCallCallback &callback)
void proxyCallAsync (const std::string &busName, const std::string &objectPath, const std::string &interface, const std::string &method, GVariant *parameters, const dbus::DbusConnection::AsyncMethodCallCallback &callback)
Private Member Functions
void onNameAcquired ()
void onNameLost ()
bool waitForName (const unsigned int timeoutMs)
void onMessageCall (const std::string &objectPath, const std::string &interface, const std::string &methodName, GVariant *parameters, dbus::MethodResultBuilder::Pointer result)
void onClientVanished (const std::string &name)
void onSignalCall (const std::string &senderBusName, const std::string &objectPath, const std::string &interface, const std::string &signalName, GVariant *parameters)
Private Attributes
dbus::DbusConnection::Pointer mDbusConnection
std::mutex mNameMutex
std::condition_variable mNameCondition
bool mNameAcquired
bool mNameLost
dbus::DbusConnection::SubscriptionId mSubscriptionId
ProxyCallCallback mProxyCallCallback
ZonesManager * mZonesManagerPtr
Detailed Description
Definition at line 44 of file host-dbus-connection.hpp.
Member Typedef Documentation
typedef std::function<void(const std::string& target, const std::string& targetBusName, const std::string& targetObjectPath, const std::string& targetInterface, const std::string& targetMethod, GVariant* parameters, dbus::MethodResultBuilder::Pointer result)> vasum::HostDbusConnection::ProxyCallCallback
Definition at line 59 of file host-dbus-connection.hpp.
Constructor & Destructor Documentation
vasum::HostDbusConnection::HostDbusConnection (ZonesManager * zm)
Definition at line 50 of file host-dbus-connection.cpp.
References vasum::api::dbus::BUS_NAME, vasum::api::dbus::DEFINITION, vasum::api::dbus::INTERFACE, mDbusConnection, mSubscriptionId, vasum::api::dbus::OBJECT_PATH, onClientVanished(), onMessageCall(), onNameAcquired(), onNameLost(), onSignalCall(), and waitForName().
vasum::HostDbusConnection::~HostDbusConnection ()
Definition at line 84 of file host-dbus-connection.cpp.
References mDbusConnection, and mSubscriptionId.
Member Function Documentation
void vasum::HostDbusConnection::onClientVanished (const std::string & name) private
Definition at line 410 of file host-dbus-connection.cpp.
References vasum::api::DBUS_CONNECTION_PREFIX, vasum::ZonesManager::disconnectedCallback(), and mZonesManagerPtr.
Referenced by HostDbusConnection().
void vasum::HostDbusConnection::onMessageCall (const std::string & objectPath, const std::string & interface, const std::string & methodName, GVariant * parameters, dbus::MethodResultBuilder::Pointer result) private
Definition at line 125 of file host-dbus-connection.cpp.
References data, vasum::ZonesManager::handleCreateFileCall(), vasum::ZonesManager::handleCreateNetdevMacvlanCall(), vasum::ZonesManager::handleCreateNetdevPhysCall(), vasum::ZonesManager::handleCreateNetdevVethCall(), vasum::ZonesManager::handleCreateZoneCall(), vasum::ZonesManager::handleDeclareFileCall(), vasum::ZonesManager::handleDeclareLinkCall(), vasum::ZonesManager::handleDeclareMountCall(), vasum::ZonesManager::handleDeleteNetdevIpAddressCall(), vasum::ZonesManager::handleDestroyNetdevCall(), vasum::ZonesManager::handleDestroyZoneCall(), vasum::ZonesManager::handleGetActiveZoneIdCall(), vasum::ZonesManager::handleGetDeclarationsCall(), vasum::ZonesManager::handleGetNetdevAttrsCall(), vasum::ZonesManager::handleGetNetdevListCall(), vasum::ZonesManager::handleGetZoneIdsCall(), vasum::ZonesManager::handleGetZoneInfoCall(), vasum::ZonesManager::handleGrantDeviceCall(), vasum::ZonesManager::handleLockQueueCall(), vasum::ZonesManager::handleLockZoneCall(), vasum::ZonesManager::handleRemoveDeclarationCall(), vasum::ZonesManager::handleRevokeDeviceCall(), vasum::ZonesManager::handleSetActiveZoneCall(), vasum::ZonesManager::handleSetNetdevAttrsCall(), vasum::ZonesManager::handleShutdownZoneCall(), vasum::ZonesManager::handleStartZoneCall(), vasum::ZonesManager::handleSwitchToDefaultCall(), vasum::ZonesManager::handleUnlockQueueCall(), vasum::ZonesManager::handleUnlockZoneCall(), vasum::api::dbus::INTERFACE, vasum::api::dbus::METHOD_CREATE_FILE, vasum::api::dbus::METHOD_CREATE_NETDEV_MACVLAN, vasum::api::dbus::METHOD_CREATE_NETDEV_PHYS, vasum::api::dbus::METHOD_CREATE_NETDEV_VETH, vasum::api::dbus::METHOD_CREATE_ZONE, vasum::api::dbus::METHOD_DECLARE_FILE, vasum::api::dbus::METHOD_DECLARE_LINK, vasum::api::dbus::METHOD_DECLARE_MOUNT, vasum::api::dbus::METHOD_DELETE_NETDEV_IP_ADDRESS, vasum::api::dbus::METHOD_DESTROY_NETDEV, vasum::api::dbus::METHOD_DESTROY_ZONE, vasum::api::dbus::METHOD_GET_ACTIVE_ZONE_ID, vasum::api::dbus::METHOD_GET_DECLARATIONS, vasum::api::dbus::METHOD_GET_NETDEV_ATTRS, vasum::api::dbus::METHOD_GET_NETDEV_LIST, vasum::api::dbus::METHOD_GET_ZONE_ID_LIST, vasum::api::dbus::METHOD_GET_ZONE_INFO, vasum::api::dbus::METHOD_GRANT_DEVICE, vasum::api::dbus::METHOD_LOCK_QUEUE, vasum::api::dbus::METHOD_LOCK_ZONE, vasum::api::dbus::METHOD_PROXY_CALL, vasum::api::dbus::METHOD_REMOVE_DECLARATION, vasum::api::dbus::METHOD_REVOKE_DEVICE, vasum::api::dbus::METHOD_SET_ACTIVE_ZONE, vasum::api::dbus::METHOD_SET_NETDEV_ATTRS, vasum::api::dbus::METHOD_SHUTDOWN_ZONE, vasum::api::dbus::METHOD_START_ZONE, vasum::api::dbus::METHOD_SWITCH_TO_DEFAULT, vasum::api::dbus::METHOD_UNLOCK_QUEUE, vasum::api::dbus::METHOD_UNLOCK_ZONE, mProxyCallCallback, mZonesManagerPtr, and vasum::api::dbus::OBJECT_PATH.
Referenced by HostDbusConnection().
void vasum::HostDbusConnection::onNameAcquired () private
Definition at line 101 of file host-dbus-connection.cpp.
References mNameAcquired, mNameCondition, and mNameMutex.
Referenced by HostDbusConnection().
void vasum::HostDbusConnection::onNameLost () private
Definition at line 108 of file host-dbus-connection.cpp.
References mNameAcquired, mNameCondition, mNameLost, and mNameMutex.
Referenced by HostDbusConnection().
void vasum::HostDbusConnection::onSignalCall (const std::string & senderBusName, const std::string & objectPath, const std::string & interface, const std::string & signalName, GVariant * parameters) private
Definition at line 416 of file host-dbus-connection.cpp.
References vasum::api::dbus::INTERFACE, and vasum::api::dbus::OBJECT_PATH.
Referenced by HostDbusConnection().
void vasum::HostDbusConnection::proxyCallAsync (const std::string & busName, const std::string & objectPath, const std::string & interface, const std::string & method, GVariant * parameters, const dbus::DbusConnection::AsyncMethodCallCallback & callback)
Make a proxy call
Definition at line 427 of file host-dbus-connection.cpp.
References mDbusConnection.
void vasum::HostDbusConnection::setProxyCallCallback (const ProxyCallCallback & callback)
Register proxy call callback
Definition at line 120 of file host-dbus-connection.cpp.
References mProxyCallCallback.
bool vasum::HostDbusConnection::waitForName (const unsigned int timeoutMs) private
Definition at line 89 of file host-dbus-connection.cpp.
References mNameAcquired, mNameCondition, mNameLost, and mNameMutex.
Referenced by HostDbusConnection().
Member Data Documentation
dbus::DbusConnection::Pointer vasum::HostDbusConnection::mDbusConnection private
Definition at line 77 of file host-dbus-connection.hpp.
Referenced by HostDbusConnection(), proxyCallAsync(), and ~HostDbusConnection().
bool vasum::HostDbusConnection::mNameAcquired private
Definition at line 80 of file host-dbus-connection.hpp.
Referenced by onNameAcquired(), onNameLost(), and waitForName().
std::condition_variable vasum::HostDbusConnection::mNameCondition private
Definition at line 79 of file host-dbus-connection.hpp.
Referenced by onNameAcquired(), onNameLost(), and waitForName().
bool vasum::HostDbusConnection::mNameLost private
Definition at line 81 of file host-dbus-connection.hpp.
Referenced by onNameLost(), and waitForName().
std::mutex vasum::HostDbusConnection::mNameMutex private
Definition at line 78 of file host-dbus-connection.hpp.
Referenced by onNameAcquired(), onNameLost(), and waitForName().
ProxyCallCallback vasum::HostDbusConnection::mProxyCallCallback private
Definition at line 83 of file host-dbus-connection.hpp.
Referenced by onMessageCall(), and setProxyCallCallback().
dbus::DbusConnection::SubscriptionId vasum::HostDbusConnection::mSubscriptionId private
Definition at line 82 of file host-dbus-connection.hpp.
Referenced by HostDbusConnection(), and ~HostDbusConnection().
ZonesManager* vasum::HostDbusConnection::mZonesManagerPtr private
Definition at line 84 of file host-dbus-connection.hpp.
Referenced by onClientVanished(), and onMessageCall().
The documentation for this class was generated from the following files:
/home/lkostyra/eclipse_workspaces/code/vasum/server/host-dbus-connection.hpp
/home/lkostyra/eclipse_workspaces/code/vasum/server/host-dbus-connection.cpp