Vasum: utils::CArrayBuilder< T > Class Template Reference
utils::CArrayBuilder< T > Class Template Reference
#include <c-array.hpp>
Public Member Functions
CArrayBuilder ()
CArrayBuilder & add (const T &v)
const T * c_array () const
size_t size () const
bool empty () const
const T * begin () const
const T * end () const
Private Attributes
std::vector< T > mArray
Detailed Description
template<typename T>
class utils::CArrayBuilder< T >
Definition at line 33 of file c-array.hpp.
Constructor & Destructor Documentation
template<typename T > utils::CArrayBuilder< T >::CArrayBuilder () inline
Definition at line 35 of file c-array.hpp.
Member Function Documentation
template<typename T > CArrayBuilder& utils::CArrayBuilder< T >::add (const T & v) inline
Definition at line 37 of file c-array.hpp.
References utils::CArrayBuilder< T >::mArray.
Referenced by vasum::cli::console_zone(), vasum::lxc::LxcZone::create(), vasum::lxc::LxcZone::shutdown(), vasum::Zone::start(), vasum::lxc::LxcZone::start(), and vasum::Zone::Zone().
template<typename T > const T* utils::CArrayBuilder< T >::begin () const inline
Definition at line 55 of file c-array.hpp.
References utils::CArrayBuilder< T >::mArray.
template<typename T > const T* utils::CArrayBuilder< T >::c_array () const inline
Definition at line 43 of file c-array.hpp.
References utils::CArrayBuilder< T >::mArray.
Referenced by vasum::lxc::LxcZone::create(), vasum::lxc::LxcZone::shutdown(), vasum::Zone::start(), vasum::lxc::LxcZone::start(), and vasum::Zone::Zone().
template<typename T > bool utils::CArrayBuilder< T >::empty () const inline
Definition at line 51 of file c-array.hpp.
References utils::CArrayBuilder< T >::size().
Referenced by vasum::Zone::start().
template<typename T > const T* utils::CArrayBuilder< T >::end () const inline
Definition at line 59 of file c-array.hpp.
References utils::CArrayBuilder< T >::mArray.
template<typename T > size_t utils::CArrayBuilder< T >::size () const inline
Definition at line 47 of file c-array.hpp.
References utils::CArrayBuilder< T >::mArray.
Referenced by utils::CArrayBuilder< T >::empty().
Member Data Documentation
template<typename T > std::vector<T> utils::CArrayBuilder< T >::mArray private
Definition at line 63 of file c-array.hpp.
Referenced by utils::CArrayBuilder< T >::add(), utils::CArrayBuilder< T >::begin(), utils::CArrayBuilder< T >::c_array(), utils::CArrayBuilder< T >::end(), and utils::CArrayBuilder< T >::size().
The documentation for this class was generated from the following file:
/home/lkostyra/eclipse_workspaces/code/vasum/common/utils/c-array.hpp