Vasum: vasum::utils Namespace Reference
vasum::utils Namespace Reference
Classes
class CArrayBuilder
class CallbackGuard
class CallbackWrapper
class CountingMap
class EventFD
class ScopedGlibLoop
class Glib
class Latch
class SameThreadGuard
class ScopedGError
class ValueLatch
class Worker
Typedefs
typedef CArrayBuilder< const
char * > CStringArrayBuilder
Enumerations
enum RunLevel : int { RUNLEVEL_POWEROFF = 0, RUNLEVEL_REBOOT = 6 }
Functions
template<class Callback >
CallbackWrapper< Callback > * createCallbackWrapper (const Callback &callback, const CallbackGuard::Tracker &tracker)
template<class Callback >
void deleteCallbackWrapper (void *pointer)
template<class Callback >
const Callback & getCallbackFromPointer (const void *pointer)
bool setSuppGroups (const std::vector< std::string > &groups)
bool dropRoot (uid_t uid, gid_t gid, const std::vector< unsigned int > &caps)
bool launchAsRoot (const std::function< bool()> &func)
bool joinToNs (int nsPid, int ns)
int passNemaspacedFd (int nsPid, int ns, const std::function< int()> &fdFactory)
bool waitPid (pid_t pid, int &status)
void close (int fd)
void write (int fd, const void *bufferPtr, const size_t size, int timeoutMS)
void read (int fd, void *bufferPtr, const size_t size, int timeoutMS)
unsigned int getMaxFDNumber ()
void setMaxFDNumber (unsigned int limit)
unsigned int getFDNumber ()
void waitForFile (const std::string &filename, const unsigned int timeoutMs)
std::string readFileContent (const std::string &path)
bool readFileContent (const std::string &path, std::string &result)
bool saveFileContent (const std::string &path, const std::string &content)
bool readFirstLineOfFile (const std::string &path, std::string &ret)
bool removeFile (const std::string &path)
bool isCharDevice (const std::string &path)
bool mountRun (const std::string &path)
bool mount (const std::string &source, const std::string &target, const std::string &filesystemtype, unsigned long mountflags, const std::string &data)
bool umount (const std::string &path)
bool isMountPoint (const std::string &path, bool &result)
bool hasSameMountPoint (const std::string &path1, const std::string &path2, bool &result)
bool moveFile (const std::string &src, const std::string &dst)
bool copyDirContents (const std::string &src, const std::string &dst)
bool createDir (const std::string &path, uid_t uid, uid_t gid, boost::filesystem::perms mode)
bool createDirs (const std::string &path, mode_t mode)
bool createEmptyDir (const std::string &path)
bool createFile (const std::string &path, int flags, mode_t mode)
bool createFifo (const std::string &path, mode_t mode)
bool copyFile (const std::string &src, const std::string &dest)
bool createLink (const std::string &src, const std::string &dest)
bool listDir (const std::string &path, std::vector< std::string > &files)
bool getFreeLoopDevice (std::string &ret)
bool mountImage (const std::string &image, const std::string &path, const std::string &loopdev)
bool umountImage (const std::string &path, const std::string &loopdev)
bool copyImageContents (const std::string &img, const std::string &dst)
bool setRunLevel (RunLevel runLevel)
template<class T >
void make_clean (T &value)
template<class T >
T make_clean ()
template<class... Paths>
std::string createFilePath (const Paths &...paths)
std::string dirName (std::string path)
std::string getAbsolutePath (const std::string &path, const std::string &base)
std::ostream & operator<< (std::ostream &os, const ScopedGError &e)
void signalBlock (const int signalToBlock)
std::string getTypeName (const std::type_info &ti)
template<class T >
std::string getTypeName (const T &t)
bool activateVT (const int &vt)
bool executeAndWait (const std::function< void()> &func, int &status)
bool executeAndWait (const std::function< void()> &func)
bool executeAndWait (const char *fname, const char *const *argv, int &status)
bool executeAndWait (const char *fname, const char *const *argv)
Variables
const unsigned int GRANULARITY = 100
Typedef Documentation
typedef CArrayBuilder<const char*> vasum::utils::CStringArrayBuilder
Definition at line 67 of file c-array.hpp.
Enumeration Type Documentation
enum vasum::utils::RunLevel : int
Enumerator
RUNLEVEL_POWEROFF
RUNLEVEL_REBOOT
Definition at line 32 of file initctl.hpp.
Function Documentation
bool vasum::utils::activateVT (const int & vt)
Definition at line 45 of file vt.cpp.
References close().
Referenced by vasum::Zone::activateVT().
void vasum::utils::close (int fd)
Close the file descriptor.
Definition at line 93 of file fd-utils.cpp.
References vasum::getSystemErrorMessage().
Referenced by activateVT(), vasum::ipc::Socket::connectSocket(), createFile(), vasum::ipc::Socket::createZoneSocket(), joinToNs(), passNemaspacedFd(), setRunLevel(), umountImage(), vasum::utils::EventFD::~EventFD(), vasum::epoll::EventPoll::~EventPoll(), and vasum::ipc::Socket::~Socket().
bool vasum::utils::copyDirContents (const std::string & src, const std::string & dst)
Recursively copy contents of src dir to dst dir.
Definition at line 337 of file fs.cpp.
Referenced by copyImageContents().
bool vasum::utils::copyFile (const std::string & src, const std::string & dest)
Copy an file
Definition at line 463 of file fs.cpp.
Referenced by vasum::ZoneProvision::file().
bool vasum::utils::copyImageContents (const std::string & img, const std::string & dst)
Mounts an image and copies its contents to dst directory.
Definition at line 174 of file img.cpp.
References copyDirContents(), createEmptyDir(), createFilePath(), dirName(), getFreeLoopDevice(), mountImage(), and umountImage().
Referenced by vasum::ZonesManager::createZone().
template<class Callback > CallbackWrapper<Callback>* vasum::utils::createCallbackWrapper (const Callback & callback, const CallbackGuard::Tracker & tracker)
Creates callback wrapper. Useful for C callback api.
Definition at line 63 of file callback-wrapper.hpp.
Referenced by vasum::utils::Glib::addTimerEvent(), vasum::ipc::IPCGSource::create(), vasum::InputMonitor::createGIOChannel(), and vasum::epoll::GlibDispatcher::GlibDispatcher().
bool vasum::utils::createDir (const std::string & path, uid_t uid, uid_t gid, boost::filesystem::perms mode)
Creates a directory with specific UID, GID and permissions set.
Definition at line 342 of file fs.cpp.
Referenced by createDirs(), and vasum::Server::prepareEnvironment().
bool vasum::utils::createDirs (const std::string & path, mode_t mode)
Recursively creates a directory with specific permissions set.
Definition at line 380 of file fs.cpp.
References createDir().
Referenced by vasum::ZoneProvision::file().
bool vasum::utils::createEmptyDir (const std::string & path)
Creates an empty directory, ready to serve as mount point. Succeeds either if path did not exist and was created successfully, or if already existing dir under the same path is empty and is not a mount point.
Definition at line 410 of file fs.cpp.
Referenced by copyImageContents().
bool vasum::utils::createFifo (const std::string & path, mode_t mode)
Creates an FIFO special file
Definition at line 453 of file fs.cpp.
Referenced by vasum::ZoneProvision::file().
bool vasum::utils::createFile (const std::string & path, int flags, mode_t mode)
Creates an empty file
Definition at line 438 of file fs.cpp.
References close(), and vasum::getSystemErrorMessage().
Referenced by vasum::ZoneProvision::file().
template<class... Paths> std::string vasum::utils::createFilePath (const Paths &... paths)
Definition at line 37 of file paths.hpp.
Referenced by copyImageContents(), vasum::ZonesManager::createZone(), vasum::ZonesManager::destroyZone(), getAbsolutePath(), and vasum::ZonesManager::insertZone().
bool vasum::utils::createLink (const std::string & src, const std::string & dest)
Create hard link
Definition at line 495 of file fs.cpp.
References vasum::getSystemErrorMessage().
Referenced by vasum::ZoneProvision::link().
template<class Callback > void vasum::utils::deleteCallbackWrapper (void * pointer)
Deletes callback wrapper. Useful for C callback api.
Definition at line 73 of file callback-wrapper.hpp.
Referenced by vasum::epoll::GlibDispatcher::GlibDispatcher().
std::string vasum::utils::dirName (std::string path) inline
Definition at line 96 of file paths.hpp.
Referenced by copyImageContents(), isMountPoint(), and moveFile().
bool vasum::utils::dropRoot (uid_t uid, gid_t gid, const std::vector< unsigned int > & caps)
Set effective and permited capabilities on the current process and drop root privileges.
Definition at line 157 of file environment.cpp.
Referenced by vasum::Server::prepareEnvironment().
bool vasum::utils::executeAndWait (const std::function< void()> & func, int & status)
Execute function in child process
Definition at line 71 of file execute.cpp.
References vasum::getSystemErrorMessage(), and waitPid().
Referenced by vasum::lxc::LxcZone::create(), executeAndWait(), launchAsRoot(), passNemaspacedFd(), vasum::lxc::LxcZone::shutdown(), and vasum::lxc::LxcZone::start().
bool vasum::utils::executeAndWait (const std::function< void()> & func)
Definition at line 87 of file execute.cpp.
References executeAndWait().
bool vasum::utils::executeAndWait (const char * fname, const char *const * argv, int & status)
Definition at line 97 of file execute.cpp.
References executeAndWait().
bool vasum::utils::executeAndWait (const char * fname, const char *const * argv)
Execute binary
Definition at line 111 of file execute.cpp.
References executeAndWait().
std::string vasum::utils::getAbsolutePath (const std::string & path, const std::string & base) inline
Definition at line 113 of file paths.hpp.
References createFilePath().
Referenced by vasum::ZoneAdmin::ZoneAdmin().
template<class Callback > const Callback& vasum::utils::getCallbackFromPointer (const void * pointer)
Recovers callback from wrapper pointer. Useful for C callback api.
Definition at line 82 of file callback-wrapper.hpp.
unsigned int vasum::utils::getFDNumber ()
Returns
number of opened file descriptors by this process
Definition at line 192 of file fd-utils.cpp.
bool vasum::utils::getFreeLoopDevice (std::string & ret)
Returns string with first free loop device.
Definition at line 118 of file img.cpp.
Referenced by copyImageContents().
unsigned int vasum::utils::getMaxFDNumber ()
Returns
the max number of file descriptors for this process.
Definition at line 171 of file fd-utils.cpp.
References vasum::getSystemErrorMessage().
std::string vasum::utils::getTypeName (const std::type_info & ti)
Definition at line 35 of file typeinfo.cpp.
Referenced by getTypeName(), and main().
template<class T > std::string vasum::utils::getTypeName (const T & t)
Definition at line 36 of file typeinfo.hpp.
References getTypeName().
bool vasum::utils::hasSameMountPoint (const std::string & path1, const std::string & path2, bool & result)
Checks whether the given paths are under the same mount point
Definition at line 211 of file fs.cpp.
Referenced by isMountPoint(), and moveFile().
bool vasum::utils::isCharDevice (const std::string & path)
Checks if a char device exists
Definition at line 133 of file fs.cpp.
bool vasum::utils::isMountPoint (const std::string & path, bool & result)
Check if given path is a mount point
Definition at line 201 of file fs.cpp.
References dirName(), and hasSameMountPoint().
Referenced by vasum::ZoneConnectionTransport::ZoneConnectionTransport().
bool vasum::utils::joinToNs (int nsPid, int ns)
Join to namespace
Definition at line 198 of file environment.cpp.
References close(), and vasum::getSystemErrorMessage().
Referenced by passNemaspacedFd().
bool vasum::utils::launchAsRoot (const std::function< bool()> & func)
Launch func as root user.
This function forks, sets UID 0 to child process and calls func.
Definition at line 178 of file environment.cpp.
References executeAndWait(), and vasum::getSystemErrorMessage().
Referenced by vasum::ZonesManager::createZone().
bool vasum::utils::listDir (const std::string & path, std::vector< std::string > & files)
List all (including '.' and '..' entries) dir entries
template<class T > void vasum::utils::make_clean (T & value)
Definition at line 35 of file make-clean.hpp.
Referenced by make_clean().
template<class T > T vasum::utils::make_clean ()
Definition at line 42 of file make-clean.hpp.
References make_clean().
bool vasum::utils::mount (const std::string & source, const std::string & target, const std::string & filesystemtype, unsigned long mountflags, const std::string & data)
Creates mount point
Definition at line 162 of file fs.cpp.
References vasum::getSystemErrorMessage().
Referenced by vasum::ZoneProvision::mount().
bool vasum::utils::mountImage (const std::string & image, const std::string & loopdev, const std::string & path)
Mount an ext4 image from file on a given path by using a loop device.
Definition at line 142 of file img.cpp.
Referenced by copyImageContents().
bool vasum::utils::mountRun (const std::string & path)
Mounts run as a tmpfs on a given path
Definition at line 156 of file fs.cpp.
Referenced by vasum::ZoneConnectionTransport::ZoneConnectionTransport().
bool vasum::utils::moveFile (const std::string & src, const std::string & dst)
Moves the file either by rename if under the same mount point or by copy&delete if under a different one. The destination has to be a full path including file name.
Definition at line 229 of file fs.cpp.
References dirName(), and hasSameMountPoint().
Referenced by vasum::ZonesManager::handleFileMoveCall().
std::ostream& vasum::utils::operator<< (std::ostream & os, const ScopedGError & e)
Writes out the error message
Parameters
os the output stream
e error to write out
Definition at line 70 of file scoped-gerror.cpp.
int vasum::utils::passNemaspacedFd (int nsPid, int ns, const std::function< int()> & fdFactory)
Pass file descriptor from namespace of some process
Definition at line 221 of file environment.cpp.
References close(), executeAndWait(), vasum::getSystemErrorMessage(), and joinToNs().
Referenced by vasum::netlink::Netlink::open().
void vasum::utils::read (int fd, void * bufferPtr, const size_t size, int timeoutMS = 500)
Read from a file descriptor, throw on error.
Parameters
fd file descriptor
bufferPtr pointer to the data buffer
size size of the data to read
timeoutMS timeout in milliseconds
Definition at line 139 of file fd-utils.cpp.
References vasum::getSystemErrorMessage().
Referenced by vasum::ipc::Socket::read(), and vasum::utils::EventFD::receive().
std::string vasum::utils::readFileContent (const std::string & path)
Reads the content of a file; Throws exception on error
Definition at line 52 of file fs.cpp.
bool vasum::utils::readFileContent (const std::string & path, std::string & content)
Reads the content of a file
Definition at line 61 of file fs.cpp.
bool vasum::utils::readFirstLineOfFile (const std::string & path, std::string & ret)
Read a line from file Its goal is to read a kernel config files (eg. from /proc, /sys/)
Definition at line 104 of file fs.cpp.
Referenced by vasum::lxc::getCgroup(), and Client::vsm_lookup_zone_by_pid().
bool vasum::utils::removeFile (const std::string & path)
Remove file
Definition at line 120 of file fs.cpp.
Referenced by vasum::ZonesManager::destroyZone().
bool vasum::utils::saveFileContent (const std::string & path, const std::string & content)
Save the content to the file
Definition at line 89 of file fs.cpp.
Referenced by vasum::ZonesManager::insertZone(), and vasum::lxc::setCgroup().
void vasum::utils::setMaxFDNumber (unsigned int limit)
Set the software and hardware limit of file descriptors for this process.
Parameters
limit limit of file descriptors
Definition at line 181 of file fd-utils.cpp.
References vasum::getSystemErrorMessage().
bool vasum::utils::setRunLevel (RunLevel runLevel)
Definition at line 69 of file initctl.cpp.
References close(), and write().
Referenced by vasum::lxc::LxcZone::setRunLevel().
bool vasum::utils::setSuppGroups (const std::vector< std::string > & groups)
Set supplementary groups to the current process.
Definition at line 133 of file environment.cpp.
Referenced by vasum::Server::prepareEnvironment().
void vasum::utils::signalBlock (const int signalToBlock)
Definition at line 37 of file signal.cpp.
bool vasum::utils::umount (const std::string & path)
Umounts a filesystem
Definition at line 192 of file fs.cpp.
Referenced by vasum::ZoneProvision::umount(), umountImage(), and vasum::ZoneConnectionTransport::~ZoneConnectionTransport().
bool vasum::utils::umountImage (const std::string & path, const std::string & loopdev)
Umounts previously mounted image. This call will also free loop device used to mount specified path.
Definition at line 150 of file img.cpp.
References close(), and umount().
Referenced by copyImageContents().
void vasum::utils::waitForFile (const std::string & filename, const unsigned int timeoutMs)
Definition at line 40 of file file-wait.cpp.
References GRANULARITY.
Referenced by vasum::ZoneConnectionTransport::acquireAddress().
bool vasum::utils::waitPid (pid_t pid, int & status)
Wait until child processes ends
Definition at line 120 of file execute.cpp.
Referenced by executeAndWait(), and vasum::lxc::LxcZone::setRunLevel().
void vasum::utils::write (int fd, const void * bufferPtr, const size_t size, int timeoutMS = 500)
Write to a file descriptor, throw on error.
Parameters
fd file descriptor
bufferPtr pointer to the data buffer
size size of data to write
timeoutMS timeout in milliseconds
Definition at line 111 of file fd-utils.cpp.
References vasum::getSystemErrorMessage().
Referenced by vasum::utils::EventFD::send(), setRunLevel(), and vasum::ipc::Socket::write().
Variable Documentation
const unsigned int vasum::utils::GRANULARITY = 100
Definition at line 38 of file file-wait.cpp.
Referenced by waitForFile().