Vasum: /home/lkostyra/eclipse_workspaces/code/vasum/client/vasum-client.cpp File Reference
vasum-client.cpp File Reference
This file contains the public API for Vasum Client.
#include "config.hpp"
#include "vasum-client.h"
#include "vasum-client-impl.hpp"
#include <cassert>
Macros
#define API __attribute__((visibility("default")))
Functions
API VsmStatus vsm_lock_queue (VsmClient client)
API VsmStatus vsm_unlock_queue (VsmClient client)
API VsmStatus vsm_get_poll_fd (VsmClient client, int *fd)
API VsmStatus vsm_enter_eventloop (VsmClient client, int flags, int timeout)
API VsmStatus vsm_set_dispatcher_type (VsmClient client, VsmDispacherType dispacher)
API VsmStatus vsm_get_dispatcher_type (VsmClient client, VsmDispacherType *dispacher)
API VsmClient vsm_client_create ()
API VsmStatus vsm_connect (VsmClient client)
API VsmStatus vsm_connect_custom (VsmClient client, const char *address)
API VsmStatus vsm_disconnect (VsmClient client)
API void vsm_array_string_free (VsmArrayString astring)
API void vsm_string_free (VsmString string)
API void vsm_zone_free (VsmZone zone)
API void vsm_netdev_free (VsmNetdev netdev)
API void vsm_client_free (VsmClient client)
API const char * vsm_get_status_message (VsmClient client)
API VsmStatus vsm_get_status (VsmClient client)
API VsmStatus vsm_get_zone_dbuses (VsmClient client, VsmArrayString *keys, VsmArrayString *values)
API VsmStatus vsm_get_zone_ids (VsmClient client, VsmArrayString *array)
API VsmStatus vsm_get_active_zone_id (VsmClient client, VsmString *id)
API VsmStatus vsm_get_zone_rootpath (VsmClient client, const char *id, VsmString *rootpath)
API VsmStatus vsm_lookup_zone_by_pid (VsmClient client, int pid, VsmString *id)
API VsmStatus vsm_lookup_zone_by_id (VsmClient client, const char *id, VsmZone *zone)
API VsmStatus vsm_lookup_zone_by_terminal_id (VsmClient client, int terminal, VsmString *id)
API VsmStatus vsm_set_active_zone (VsmClient client, const char *id)
API VsmStatus vsm_create_zone (VsmClient client, const char *id, const char *tname)
API VsmStatus vsm_destroy_zone (VsmClient client, const char *id, int)
API VsmStatus vsm_shutdown_zone (VsmClient client, const char *id)
API VsmStatus vsm_start_zone (VsmClient client, const char *id)
API VsmStatus vsm_lock_zone (VsmClient client, const char *id)
API VsmStatus vsm_unlock_zone (VsmClient client, const char *id)
API VsmStatus vsm_add_state_callback (VsmClient client, VsmZoneDbusStateCallback zoneDbusStateCallback, void *data, VsmSubscriptionId *subscriptionId)
API VsmStatus vsm_del_state_callback (VsmClient client, VsmSubscriptionId subscriptionId)
API VsmStatus vsm_grant_device (VsmClient client, const char *id, const char *device, uint32_t flags)
API VsmStatus vsm_revoke_device (VsmClient client, const char *id, const char *device)
API VsmStatus vsm_zone_get_netdevs (VsmClient client, const char *zone, VsmArrayString *netdevIds)
API VsmStatus vsm_netdev_get_ipv4_addr (VsmClient client, const char *zone, const char *netdevId, struct in_addr *addr)
API VsmStatus vsm_netdev_get_ipv6_addr (VsmClient client, const char *zone, const char *netdevId, struct in6_addr *addr)
API VsmStatus vsm_netdev_set_ipv4_addr (VsmClient client, const char *zone, const char *netdevId, struct in_addr *addr, int prefix)
API VsmStatus vsm_netdev_set_ipv6_addr (VsmClient client, const char *zone, const char *netdevId, struct in6_addr *addr, int prefix)
API VsmStatus vsm_netdev_del_ipv4_addr (VsmClient client, const char *zone, const char *netdevId, struct in_addr *addr, int prefix)
API VsmStatus vsm_netdev_del_ipv6_addr (VsmClient client, const char *zone, const char *netdevId, struct in6_addr *addr, int prefix)
API VsmStatus vsm_netdev_up (VsmClient client, const char *zone, const char *netdevId)
API VsmStatus vsm_netdev_down (VsmClient client, const char *zone, const char *netdevId)
API VsmStatus vsm_create_netdev_veth (VsmClient client, const char *zone, const char *zoneDev, const char *hostDev)
API VsmStatus vsm_create_netdev_macvlan (VsmClient client, const char *zone, const char *zoneDev, const char *hostDev, enum macvlan_mode mode)
API VsmStatus vsm_create_netdev_phys (VsmClient client, const char *zone, const char *devId)
API VsmStatus vsm_lookup_netdev_by_name (VsmClient client, const char *zone, const char *netdevId, VsmNetdev *netdev)
API VsmStatus vsm_destroy_netdev (VsmClient client, const char *zone, const char *devId)
API VsmStatus vsm_declare_file (VsmClient client, const char *zone, VsmFileType type, const char *path, int32_t flags, mode_t mode)
API VsmStatus vsm_declare_mount (VsmClient client, const char *source, const char *zone, const char *target, const char *type, uint64_t flags, const char *data)
API VsmStatus vsm_declare_link (VsmClient client, const char *source, const char *zone, const char *target)
API VsmStatus vsm_list_declarations (VsmClient client, const char *zone, VsmArrayString *declarations)
API VsmStatus vsm_remove_declaration (VsmClient client, const char *zone, VsmString declaration)
Detailed Description
This file contains the public API for Vasum Client.
Author
Mateusz Malicki (m.mal.nosp@m.icki.nosp@m.2@sam.nosp@m.sung.nosp@m..com)
Definition in file vasum-client.cpp.
Macro Definition Documentation
#define API __attribute__((visibility("default")))
Definition at line 33 of file vasum-client.cpp.
Function Documentation
API VsmStatus vsm_add_state_callback (VsmClient client, VsmZoneDbusStateCallback zoneDbusStateCallback, void * data, VsmSubscriptionId * subscriptionId)
Register dbus state change callback function.
Note
The callback function will be invoked on a different thread.
Parameters
[in] client vasum-server's client
[in] zoneDbusStateCallback callback function
[in] data some extra data that will be passed to callback function
[out] subscriptionId subscription identifier that can be used to unsubscribe signal, pointer can be NULL.
Returns
status of this function call
Definition at line 215 of file vasum-client.cpp.
API void vsm_array_string_free (VsmArrayString astring)
Release VsmArrayString.
Parameters
[in] astring VsmArrayString
Definition at line 99 of file vasum-client.cpp.
References vsm_string_free().
Referenced by vasum::cli::get_zone_ids(), vasum::cli::get_zones_status(), and vasum::cli::zone_get_netdevs().
API VsmClient vsm_client_create ()
Create a new vasum-server's client.
Returns
Created client pointer or NULL on failure.
Definition at line 78 of file vasum-client.cpp.
Referenced by vasum::cli::CommandLineInterface::connect().
API void vsm_client_free (VsmClient client)
Release client resources.
Parameters
[in] client vasum-server's client
Definition at line 128 of file vasum-client.cpp.
Referenced by vasum::cli::CommandLineInterface::connect(), and vasum::cli::CommandLineInterface::disconnect().
API VsmStatus vsm_connect (VsmClient client)
Connect client to the vasum-server.
Parameters
[in] client vasum-server's client
Returns
status of this function call
Definition at line 84 of file vasum-client.cpp.
Referenced by vasum::cli::CommandLineInterface::connect().
API VsmStatus vsm_connect_custom (VsmClient client, const char * address)
Connect client to the vasum-server via custom address.
Parameters
[in] client vasum-server's client
[in] address dbus address
Returns
status of this function call
Definition at line 89 of file vasum-client.cpp.
API VsmStatus vsm_create_netdev_macvlan (VsmClient client, const char * zone, const char * zoneDev, const char * hostDev, enum macvlan_mode mode)
Create macvlab in zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] zoneDev in host network device id
[in] hostDev in zone network device id
Returns
status of this function call
Definition at line 322 of file vasum-client.cpp.
Referenced by vasum::cli::create_netdev_macvlan().
API VsmStatus vsm_create_netdev_phys (VsmClient client, const char * zone, const char * devId)
Create/move phys netdev in/to zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] devId network device id
Returns
status of this function call
Definition at line 331 of file vasum-client.cpp.
Referenced by vasum::cli::create_netdev_phys().
API VsmStatus vsm_create_netdev_veth (VsmClient client, const char * zone, const char * zoneDev, const char * hostDev)
Create veth netdev in zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] zoneDev in host network device id
[in] hostDev in zone network device id
Returns
status of this function call
Definition at line 314 of file vasum-client.cpp.
Referenced by vasum::cli::create_netdev_veth().
API VsmStatus vsm_create_zone (VsmClient client, const char * id, const char * tname)
Create and add zone
Parameters
[in] client vasum-server's client
[in] id zone id
[in] tname template name, NULL is equivalent to "default"
Returns
status of this function call
Definition at line 185 of file vasum-client.cpp.
Referenced by vasum::cli::create_zone().
API VsmStatus vsm_declare_file (VsmClient client, const char * zone, VsmFileType type, const char * path, int32_t flags, mode_t mode)
Create file, directory or pipe in zone
Declare file, directory or pipe that will be created while zone startup
Parameters
[in] client vasum-server's client
[in] type file type
[in] zone zone id
[in] path path to file
[in] flags if O_CREAT bit is set then file will be created in zone, otherwise file will by copied from host; it is meaningful only when O_CREAT is set
[in] mode mode of file
Returns
status of this function call
Definition at line 349 of file vasum-client.cpp.
API VsmStatus vsm_declare_link (VsmClient client, const char * source, const char * zone, const char * target)
Create link in zone
Declare link that will be created while zone startup Parameters are passed to link system function
Parameters
[in] client vasum-server's client
[in] source path to link source (in host)
[in] zone zone id
[in] target path to link name (in zone)
Returns
status of this function call
Definition at line 371 of file vasum-client.cpp.
API VsmStatus vsm_declare_mount (VsmClient client, const char * source, const char * zone, const char * target, const char * type, uint64_t flags, const char * data)
Create mount point in zone
Declare mount that will be created while zone startup Parameters are passed to mount system function
Parameters
[in] client vasum-server's client
[in] source device path (path in host)
[in] zone zone id
[in] target mount point (path in zone)
[in] type filesystem type
[in] flags mount flags as in mount function
[in] data additional data as in mount function
Returns
status of this function call
Definition at line 360 of file vasum-client.cpp.
API VsmStatus vsm_del_state_callback (VsmClient client, VsmSubscriptionId subscriptionId)
Unregister dbus state change callback function.
Parameters
[in] client vasum-server's client
[in] subscriptionId subscription identifier returned by vsm_add_state_callback
Returns
status of this function call
Definition at line 223 of file vasum-client.cpp.
API VsmStatus vsm_destroy_netdev (VsmClient client, const char * zone, const char * devId)
Remove netdev from zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] devId network device id
Returns
status of this function call
Definition at line 344 of file vasum-client.cpp.
Referenced by vasum::cli::destroy_netdev().
API VsmStatus vsm_destroy_zone (VsmClient client, const char * id, int force)
Remove zone
Parameters
[in] client vasum-server's client
[in] id zone id
[in] force if 0 data will be kept, otherwise data will be lost
Returns
status of this function call
Definition at line 190 of file vasum-client.cpp.
Referenced by vasum::cli::destroy_zone().
API VsmStatus vsm_disconnect (VsmClient client)
Disconnect client from vasum-server.
Parameters
[in] client vasum-server's client
Returns
status of this function call
Definition at line 94 of file vasum-client.cpp.
Referenced by vasum::cli::CommandLineInterface::disconnect().
API VsmStatus vsm_enter_eventloop (VsmClient client, int flags, int timeout)
Wait for an I/O event on a vsm client
vsm_enter_eventloop() waits for event on the vsm client
The call waits for a maximum time of timout milliseconds. Specifying a timeout of -1 makes vsm_enter_eventloop() wait indefinitely, while specifying a timeout equal to zero makes vsm_enter_eventloop() to return immediately even if no events are available.
Parameters
[in] client vasum-server's client
[in] flags Reserved
[in] timeout Timeout time (milisecond), -1 is infinite
Returns
status of this function call
Definition at line 63 of file vasum-client.cpp.
API VsmStatus vsm_get_active_zone_id (VsmClient client, VsmString * id)
Get active (foreground) zone name.
Parameters
[in] client vasum-server's client
[out] id active zone name
Returns
status of this function call
Remarks
Use vsm_string_free() to free memory occupied by id.
Definition at line 155 of file vasum-client.cpp.
Referenced by vasum::cli::get_active_zone_id(), and vasum::cli::get_zones_status().
API VsmStatus vsm_get_dispatcher_type (VsmClient client, VsmDispacherType * dispacher)
Get dispatching method
Parameters
[in] client vasum-server's client
[out] dispacher dispatching method
Returns
status of this function call
Definition at line 73 of file vasum-client.cpp.
API VsmStatus vsm_get_poll_fd (VsmClient client, int * fd)
Get file descriptor associated with event dispatcher of zone client
The function vsm_get_poll_fd() returns the file descriptor associated with the event dispatcher of vsm client. The file descriptor can be bound to another I/O multiplexing facilities like epoll, select, and poll.
Parameters
[in] client vsm client
[out] fd epoll file descriptor
Returns
status of this function call
Definition at line 58 of file vasum-client.cpp.
API VsmStatus vsm_get_status (VsmClient client)
Get status code of last vasum-server communication.
Parameters
[in] client vasum-server's client
Returns
status of this function call
Definition at line 140 of file vasum-client.cpp.
API const char* vsm_get_status_message (VsmClient client)
Get status message of the last vasum-server communication.
Parameters
[in] client vasum-server's client
Returns
last status message from vasum-server communication
Definition at line 135 of file vasum-client.cpp.
Referenced by vasum::cli::CommandLineInterface::connect(), vasum::cli::CommandLineInterface::disconnect(), and vasum::cli::CommandLineInterface::executeCallback().
API VsmStatus vsm_get_zone_dbuses (VsmClient client, VsmArrayString * keys, VsmArrayString * values)
Get dbus address of each zone.
Parameters
[in] client vasum-server's client
[out] keys array of zones name
[out] values array of zones dbus address
Returns
status of this function call
Postcondition
keys[i] corresponds to values[i]
Remarks
Use vsm_array_string_free() to free memory occupied by keys and values.
Definition at line 145 of file vasum-client.cpp.
API VsmStatus vsm_get_zone_ids (VsmClient client, VsmArrayString * array)
Get zones name.
Parameters
[in] client vasum-server's client
[out] array array of zones name
Returns
status of this function call
Remarks
Use vsm_array_string_free() to free memory occupied by array.
Definition at line 150 of file vasum-client.cpp.
Referenced by vasum::cli::get_zone_ids(), and vasum::cli::get_zones_status().
API VsmStatus vsm_get_zone_rootpath (VsmClient client, const char * id, VsmString * rootpath)
Get zone rootfs path.
Parameters
[in] client vasum-server's client
[in] id zone name
[out] rootpath zone rootfs path
Returns
status of this function call
Remarks
Use vsm_string_free() to free memory occupied by rootpath.
Definition at line 160 of file vasum-client.cpp.
API VsmStatus vsm_grant_device (VsmClient client, const char * zone, const char * device, uint32_t flags)
Grant access to device
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] device device path
[in] flags access flags
Returns
status of this function call
Definition at line 228 of file vasum-client.cpp.
Referenced by vasum::cli::grant_device().
API VsmStatus vsm_list_declarations (VsmClient client, const char * zone, VsmArrayString * declarations)
Get all declarations
Gets all declarations of resourcies (
See Also
vsm_declare_link,
vsm_declare_mount,
::vsm_declare_linki)
Parameters
[in] client vasum-server's client
[in] zone zone id
[out] declarations array of declarations id
Returns
status of this function call
Definition at line 379 of file vasum-client.cpp.
API VsmStatus vsm_lock_queue (VsmClient client)
Lock the command queue exclusively.
Parameters
[in] client vasum-server's client
Returns
status of this function call
Definition at line 48 of file vasum-client.cpp.
Referenced by vasum::cli::lock_queue().
API VsmStatus vsm_lock_zone (VsmClient client, const char * id)
Lock zone
Parameters
[in] client vasum-server's client
[in] id zone name
Returns
status of this function call
Definition at line 205 of file vasum-client.cpp.
Referenced by vasum::cli::lock_zone().
API VsmStatus vsm_lookup_netdev_by_name (VsmClient client, const char * zone, const char * netdevId, VsmNetdev * netdev)
Get netdev informations
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId network device id
[out] netdev netdev informations
Returns
status of this function call
Remarks
Use vsm_netdev_free() to free memory occupied by netdev.
Definition at line 336 of file vasum-client.cpp.
Referenced by vasum::cli::lookup_netdev_by_name().
API VsmStatus vsm_lookup_zone_by_id (VsmClient client, const char * id, VsmZone * zone)
Get zone informations of zone with given id.
Parameters
[in] client vasum-server's client
[in] id zone name
[out] zone zone informations
Returns
status of this function call
Remarks
Use vsm_zone_free() to free memory occupied by zone
Definition at line 170 of file vasum-client.cpp.
Referenced by vasum::cli::console_zone(), vasum::cli::get_zones_status(), and vasum::cli::lookup_zone_by_id().
API VsmStatus vsm_lookup_zone_by_pid (VsmClient client, int pid, VsmString * id)
Get zone name of process with given pid.
Parameters
[in] client vasum-server's client
[in] pid process id
[out] id active zone name
Returns
status of this function call
Remarks
Use vsm_string_free() to free memory occupied by id.
Definition at line 165 of file vasum-client.cpp.
API VsmStatus vsm_lookup_zone_by_terminal_id (VsmClient client, int terminal, VsmString * id)
Get zone name with given terminal.
Parameters
[in] client vasum-server's client
[in] terminal terminal id
[out] id zone name with given terminal
Returns
status of this function call
Remarks
Use vsm_string_free() to free memory occupied by id.
Definition at line 175 of file vasum-client.cpp.
API VsmStatus vsm_netdev_del_ipv4_addr (VsmClient client, const char * zone, const char * netdevId, struct in_addr * addr, int prefix)
Remove ipv4 address from netdev
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId network device id
[in] addr ipv4 address
[in] prefix bit-length of the network prefix
Returns
status of this function call
Definition at line 282 of file vasum-client.cpp.
API VsmStatus vsm_netdev_del_ipv6_addr (VsmClient client, const char * zone, const char * netdevId, struct in6_addr * addr, int prefix)
Remove ipv6 address from netdev
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId network device id
[in] addr ipv6 address
[in] prefix bit-length of the network prefix
Returns
status of this function call
Definition at line 291 of file vasum-client.cpp.
API VsmStatus vsm_netdev_down (VsmClient client, const char * zone, const char * netdevId)
Turn down a network device in the zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId netdev id
Returns
status of this function call
Definition at line 307 of file vasum-client.cpp.
Referenced by vasum::cli::netdev_down().
API void vsm_netdev_free (VsmNetdev netdev)
Release VsmNetdev
Parameters
netdev VsmNetdev
Definition at line 122 of file vasum-client.cpp.
References VsmNetdevStructure::name.
Referenced by vasum::cli::lookup_netdev_by_name().
API VsmStatus vsm_netdev_get_ipv4_addr (VsmClient client, const char * zone, const char * netdevId, struct in_addr * addr)
Get ipv4 address for given netdevId
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId netdev id
[out] addr ipv4 address
Returns
status of this function call
Definition at line 248 of file vasum-client.cpp.
Referenced by vasum::cli::netdev_get_ipv4_addr().
API VsmStatus vsm_netdev_get_ipv6_addr (VsmClient client, const char * zone, const char * netdevId, struct in6_addr * addr)
Get ipv6 address for given netdevId
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId netdev id
[out] addr ipv6 address
Returns
status of this function call
Definition at line 256 of file vasum-client.cpp.
Referenced by vasum::cli::netdev_get_ipv6_addr().
API VsmStatus vsm_netdev_set_ipv4_addr (VsmClient client, const char * zone, const char * netdevId, struct in_addr * addr, int prefix)
Set ipv4 address for given netdevId
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId netdev id
[in] addr ipv4 address
[in] prefix bit-length of the network prefix
Returns
status of this function call
Definition at line 264 of file vasum-client.cpp.
Referenced by vasum::cli::netdev_set_ipv4_addr().
API VsmStatus vsm_netdev_set_ipv6_addr (VsmClient client, const char * zone, const char * netdevId, struct in6_addr * addr, int prefix)
Set ipv6 address for given netdevId
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId netdev id
[in] addr ipv6 address
[in] prefix bit-length of the network prefix
Returns
status of this function call
Definition at line 273 of file vasum-client.cpp.
Referenced by vasum::cli::netdev_set_ipv6_addr().
API VsmStatus vsm_netdev_up (VsmClient client, const char * zone, const char * netdevId)
Turn up a network device in the zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] netdevId netdev id
Returns
status of this function call
Definition at line 300 of file vasum-client.cpp.
Referenced by vasum::cli::netdev_up().
API VsmStatus vsm_remove_declaration (VsmClient client, const char * zone, VsmString declaration)
Remove declaration
Removes given declaration by its id (
See Also
vsm_list_declarations)
Parameters
[in] client vasum-server's client
[in] zone zone id
[in] declaration declaration id
Returns
status of this function call
Definition at line 386 of file vasum-client.cpp.
API VsmStatus vsm_revoke_device (VsmClient client, const char * zone, const char * device)
Revoke access to device
Parameters
[in] client vasum-server's client
[in] zone zone name
[in] device device path
Returns
status of this function call
Definition at line 236 of file vasum-client.cpp.
Referenced by vasum::cli::revoke_device().
API VsmStatus vsm_set_active_zone (VsmClient client, const char * id)
Set active (foreground) zone.
Parameters
[in] client vasum-server's client
[in] id zone name
Returns
status of this function call
Definition at line 180 of file vasum-client.cpp.
Referenced by vasum::cli::set_active_zone().
API VsmStatus vsm_set_dispatcher_type (VsmClient client, VsmDispacherType dispacher)
Set dispatching method
Parameters
[in] client vasum-server's client
[in] dispacher dispatching method
Returns
status of this function call
Definition at line 68 of file vasum-client.cpp.
API VsmStatus vsm_shutdown_zone (VsmClient client, const char * id)
Shutdown zone
Parameters
[in] client vasum-server's client
[in] id zone name
Returns
status of this function call
Definition at line 195 of file vasum-client.cpp.
Referenced by vasum::cli::shutdown_zone().
API VsmStatus vsm_start_zone (VsmClient client, const char * id)
Start zone
Parameters
[in] client vasum-server's client
[in] id zone name
Returns
status of this function call
Definition at line 200 of file vasum-client.cpp.
Referenced by vasum::cli::start_zone().
API void vsm_string_free (VsmString string)
Release VsmString.
Parameters
string VsmString
Definition at line 110 of file vasum-client.cpp.
Referenced by vasum::cli::get_active_zone_id(), vasum::cli::get_zones_status(), and vsm_array_string_free().
API VsmStatus vsm_unlock_queue (VsmClient client)
Unlock the command queue.
Parameters
[in] client vasum-server's client
Returns
status of this function call
Definition at line 53 of file vasum-client.cpp.
Referenced by vasum::cli::unlock_queue().
API VsmStatus vsm_unlock_zone (VsmClient client, const char * id)
Unlock zone
Parameters
[in] client vasum-server's client
[in] id zone name
Returns
status of this function call
Definition at line 210 of file vasum-client.cpp.
Referenced by vasum::cli::unlock_zone().
API void vsm_zone_free (VsmZone zone)
Release VsmZone
Parameters
zone VsmZone
Definition at line 115 of file vasum-client.cpp.
References VsmZoneStructure::id, and VsmZoneStructure::rootfs_path.
Referenced by vasum::cli::console_zone(), vasum::cli::get_zones_status(), and vasum::cli::lookup_zone_by_id().
API VsmStatus vsm_zone_get_netdevs (VsmClient client, const char * zone, VsmArrayString * netdevIds)
Get array of netdev from given zone
Parameters
[in] client vasum-server's client
[in] zone zone name
[out] netdevIds array of netdev id
Returns
status of this function call
Remarks
Use vsm_array_string_free() to free memory occupied by netdevIds.
Definition at line 241 of file vasum-client.cpp.
Referenced by vasum::cli::zone_get_netdevs().